//! Host tests for `siopreg.rs`: the period tables and the NVRAM layout, and a reference
//! test of every define.

use super::*;
use crate::reftest;

#[test]
fn period_tables_cover_the_three_clocks() {
    for clock in [250, 125, 62] {
        assert!(SCF_PERIOD.iter().any(|p| p.clock == clock));
    }
    assert!(DT_SCF_PERIOD.iter().all(|p| p.clock == 62));
    // The 53c895A's clock (62) reaches 40 MHz (period 10) single-transition.
    assert_eq!(
        SCF_PERIOD[9],
        ScfPeriod {
            clock: 62,
            period: 10,
            scf: 1
        }
    );
    assert_eq!(core::mem::offset_of!(NvramSymbios, host), 26);
    assert_eq!(core::mem::offset_of!(NvramSymbios, target), 26 + 56);
    assert_eq!(core::mem::offset_of!(NvramSymbios, trailer), 362);
}

#[test]
#[ignore = "reads the C reference (just test-ref)"]
fn defines_match_the_reference() {
    let defs = reftest::defines("sys/dev/ic/siopreg.h");
    #[allow(clippy::unnecessary_cast)] // a column of mixed types
    let ours: &[(&str, i64)] = &[
        ("SIOP_SCNTL0", SIOP_SCNTL0 as i64),
        ("SCNTL0_ARB_MASK", SCNTL0_ARB_MASK as i64),
        ("SCNTL0_SARB", SCNTL0_SARB as i64),
        ("SCNTL0_FARB", SCNTL0_FARB as i64),
        ("SCNTL0_START", SCNTL0_START as i64),
        ("SCNTL0_WATM", SCNTL0_WATM as i64),
        ("SCNTL0_EPC", SCNTL0_EPC as i64),
        ("SCNTL0_AAP", SCNTL0_AAP as i64),
        ("SCNTL0_TRG", SCNTL0_TRG as i64),
        ("SIOP_SCNTL1", SIOP_SCNTL1 as i64),
        ("SCNTL1_EXC", SCNTL1_EXC as i64),
        ("SCNTL1_ADB", SCNTL1_ADB as i64),
        ("SCNTL1_DHP", SCNTL1_DHP as i64),
        ("SCNTL1_CON", SCNTL1_CON as i64),
        ("SCNTL1_RST", SCNTL1_RST as i64),
        ("SCNTL1_AESP", SCNTL1_AESP as i64),
        ("SCNTL1_IARB", SCNTL1_IARB as i64),
        ("SCNTL1_SST", SCNTL1_SST as i64),
        ("SIOP_SCNTL2", SIOP_SCNTL2 as i64),
        ("SCNTL2_SDU", SCNTL2_SDU as i64),
        ("SCNTL2_CHM", SCNTL2_CHM as i64),
        ("SCNTL2_SLPMD", SCNTL2_SLPMD as i64),
        ("SCNTL2_SLPHBEN", SCNTL2_SLPHBEN as i64),
        ("SCNTL2_WSS", SCNTL2_WSS as i64),
        ("SCNTL2_VUE0", SCNTL2_VUE0 as i64),
        ("SCNTL2_VUE1", SCNTL2_VUE1 as i64),
        ("SCNTL2_WSR", SCNTL2_WSR as i64),
        ("SIOP_SCNTL3", SIOP_SCNTL3 as i64),
        ("SCNTL3_ULTRA", SCNTL3_ULTRA as i64),
        ("SCNTL3_SCF_SHIFT", SCNTL3_SCF_SHIFT as i64),
        ("SCNTL3_SCF_MASK", SCNTL3_SCF_MASK as i64),
        ("SCNTL3_EWS", SCNTL3_EWS as i64),
        ("SCNTL3_CCF_SHIFT", SCNTL3_CCF_SHIFT as i64),
        ("SCNTL3_CCF_MASK", SCNTL3_CCF_MASK as i64),
        ("SIOP_SCID", SIOP_SCID as i64),
        ("SCID_RRE", SCID_RRE as i64),
        ("SCID_SRE", SCID_SRE as i64),
        ("SCID_ENCID_SHIFT", SCID_ENCID_SHIFT as i64),
        ("SCID_ENCID_MASK", SCID_ENCID_MASK as i64),
        ("SIOP_SXFER", SIOP_SXFER as i64),
        ("SXFER_TP_SHIFT", SXFER_TP_SHIFT as i64),
        ("SXFER_TP_MASK", SXFER_TP_MASK as i64),
        ("SXFER_MO_SHIFT", SXFER_MO_SHIFT as i64),
        ("SXFER_MO_MASK", SXFER_MO_MASK as i64),
        ("SIOP_SDID", SIOP_SDID as i64),
        ("SDID_ENCID_SHIFT", SDID_ENCID_SHIFT as i64),
        ("SDID_ENCID_MASK", SDID_ENCID_MASK as i64),
        ("SIOP_GPREG", SIOP_GPREG as i64),
        ("GPREG_GPIO4", GPREG_GPIO4 as i64),
        ("GPREG_GPIO3", GPREG_GPIO3 as i64),
        ("GPREG_GPIO2", GPREG_GPIO2 as i64),
        ("GPREG_GPIO1", GPREG_GPIO1 as i64),
        ("GPREG_GPIO0", GPREG_GPIO0 as i64),
        ("SIOP_SFBR", SIOP_SFBR as i64),
        ("SIOP_SOCL", SIOP_SOCL as i64),
        ("SIOP_SSID", SIOP_SSID as i64),
        ("SSID_VAL", SSID_VAL as i64),
        ("SSID_ENCID_SHIFT", SSID_ENCID_SHIFT as i64),
        ("SSID_ENCID_MASK", SSID_ENCID_MASK as i64),
        ("SIOP_SBCL", SIOP_SBCL as i64),
        ("SIOP_DSTAT", SIOP_DSTAT as i64),
        ("DSTAT_DFE", DSTAT_DFE as i64),
        ("DSTAT_MDPE", DSTAT_MDPE as i64),
        ("DSTAT_BF", DSTAT_BF as i64),
        ("DSTAT_ABRT", DSTAT_ABRT as i64),
        ("DSTAT_SSI", DSTAT_SSI as i64),
        ("DSTAT_SIR", DSTAT_SIR as i64),
        ("DSTAT_IID", DSTAT_IID as i64),
        ("SIOP_SSTAT0", SIOP_SSTAT0 as i64),
        ("SSTAT0_ILF", SSTAT0_ILF as i64),
        ("SSTAT0_ORF", SSTAT0_ORF as i64),
        ("SSTAT0_OLF", SSTAT0_OLF as i64),
        ("SSTAT0_AIP", SSTAT0_AIP as i64),
        ("SSTAT0_LOA", SSTAT0_LOA as i64),
        ("SSTAT0_WOA", SSTAT0_WOA as i64),
        ("SSTAT0_RST", SSTAT0_RST as i64),
        ("SSTAT0_SDP", SSTAT0_SDP as i64),
        ("SIOP_SSTAT1", SIOP_SSTAT1 as i64),
        ("SSTAT1_FFO_SHIFT", SSTAT1_FFO_SHIFT as i64),
        ("SSTAT1_FFO_MASK", SSTAT1_FFO_MASK as i64),
        ("SSTAT1_SDPL", SSTAT1_SDPL as i64),
        ("SSTAT1_MSG", SSTAT1_MSG as i64),
        ("SSTAT1_CD", SSTAT1_CD as i64),
        ("SSTAT1_IO", SSTAT1_IO as i64),
        ("SSTAT1_PHASE_MASK", SSTAT1_PHASE_MASK as i64),
        ("SSTAT1_PHASE_DATAOUT", SSTAT1_PHASE_DATAOUT as i64),
        ("SSTAT1_PHASE_DATAIN", SSTAT1_PHASE_DATAIN as i64),
        ("SSTAT1_PHASE_CMD", SSTAT1_PHASE_CMD as i64),
        ("SSTAT1_PHASE_STATUS", SSTAT1_PHASE_STATUS as i64),
        ("SSTAT1_PHASE_MSGOUT", SSTAT1_PHASE_MSGOUT as i64),
        ("SSTAT1_PHASE_MSGIN", SSTAT1_PHASE_MSGIN as i64),
        ("SIOP_SSTAT2", SIOP_SSTAT2 as i64),
        ("SSTAT2_ILF1", SSTAT2_ILF1 as i64),
        ("SSTAT2_ORF1", SSTAT2_ORF1 as i64),
        ("SSTAT2_OLF1", SSTAT2_OLF1 as i64),
        ("SSTAT2_FF4", SSTAT2_FF4 as i64),
        ("SSTAT2_SPL1", SSTAT2_SPL1 as i64),
        ("SSTAT2_DF", SSTAT2_DF as i64),
        ("SSTAT2_LDSC", SSTAT2_LDSC as i64),
        ("SSTAT2_SDP1", SSTAT2_SDP1 as i64),
        ("SIOP_DSA", SIOP_DSA as i64),
        ("SIOP_ISTAT", SIOP_ISTAT as i64),
        ("ISTAT_ABRT", ISTAT_ABRT as i64),
        ("ISTAT_SRST", ISTAT_SRST as i64),
        ("ISTAT_SIGP", ISTAT_SIGP as i64),
        ("ISTAT_SEM", ISTAT_SEM as i64),
        ("ISTAT_CON", ISTAT_CON as i64),
        ("ISTAT_INTF", ISTAT_INTF as i64),
        ("ISTAT_SIP", ISTAT_SIP as i64),
        ("ISTAT_DIP", ISTAT_DIP as i64),
        ("SIOP_CTEST0", SIOP_CTEST0 as i64),
        ("CTEST0_EHP", CTEST0_EHP as i64),
        ("SIOP_CTEST1", SIOP_CTEST1 as i64),
        ("SIOP_CTEST2", SIOP_CTEST2 as i64),
        ("CTEST2_SRTCH", CTEST2_SRTCH as i64),
        ("SIOP_CTEST3", SIOP_CTEST3 as i64),
        ("CTEST3_FLF", CTEST3_FLF as i64),
        ("CTEST3_CLF", CTEST3_CLF as i64),
        ("CTEST3_FM", CTEST3_FM as i64),
        ("CTEST3_WRIE", CTEST3_WRIE as i64),
        ("SIOP_TEMP", SIOP_TEMP as i64),
        ("SIOP_DFIFO", SIOP_DFIFO as i64),
        ("SIOP_CTEST4", SIOP_CTEST4 as i64),
        ("CTEST4_MUX", CTEST4_MUX as i64),
        ("CTEST4_BDIS", CTEST4_BDIS as i64),
        ("CTEST_ZMOD", CTEST_ZMOD as i64),
        ("CTEST_ZSD", CTEST_ZSD as i64),
        ("CTEST_SRTM", CTEST_SRTM as i64),
        ("CTEST_MPEE", CTEST_MPEE as i64),
        ("SIOP_CTEST5", SIOP_CTEST5 as i64),
        ("CTEST5_ADCK", CTEST5_ADCK as i64),
        ("CTEST5_BBCK", CTEST5_BBCK as i64),
        ("CTEST5_DFS", CTEST5_DFS as i64),
        ("CTEST5_MASR", CTEST5_MASR as i64),
        ("CTEST5_DDIR", CTEST5_DDIR as i64),
        ("CTEST5_BOMASK", CTEST5_BOMASK as i64),
        ("SIOP_CTEST6", SIOP_CTEST6 as i64),
        ("SIOP_DBC", SIOP_DBC as i64),
        ("SIOP_DCMD", SIOP_DCMD as i64),
        ("SIOP_DNAD", SIOP_DNAD as i64),
        ("SIOP_DSP", SIOP_DSP as i64),
        ("SIOP_DSPS", SIOP_DSPS as i64),
        ("SIOP_SCRATCHA", SIOP_SCRATCHA as i64),
        ("SIOP_DMODE", SIOP_DMODE as i64),
        ("DMODE_BL_SHIFT", DMODE_BL_SHIFT as i64),
        ("DMODE_BL_MASK", DMODE_BL_MASK as i64),
        ("DMODE_SIOM", DMODE_SIOM as i64),
        ("DMODE_DIOM", DMODE_DIOM as i64),
        ("DMODE_ERL", DMODE_ERL as i64),
        ("DMODE_ERMP", DMODE_ERMP as i64),
        ("DMODE_BOF", DMODE_BOF as i64),
        ("DMODE_MAN", DMODE_MAN as i64),
        ("SIOP_DIEN", SIOP_DIEN as i64),
        ("DIEN_MDPE", DIEN_MDPE as i64),
        ("DIEN_BF", DIEN_BF as i64),
        ("DIEN_AVRT", DIEN_AVRT as i64),
        ("DIEN_SSI", DIEN_SSI as i64),
        ("DIEN_SIR", DIEN_SIR as i64),
        ("DIEN_IID", DIEN_IID as i64),
        ("SIOP_SBR", SIOP_SBR as i64),
        ("SIOP_DCNTL", SIOP_DCNTL as i64),
        ("DCNTL_CLSE", DCNTL_CLSE as i64),
        ("DCNTL_PFF", DCNTL_PFF as i64),
        ("DCNTL_EA", DCNTL_EA as i64),
        ("DCNTL_PFEN", DCNTL_PFEN as i64),
        ("DCNTL_SSM", DCNTL_SSM as i64),
        ("DCNTL_IRQM", DCNTL_IRQM as i64),
        ("DCNTL_STD", DCNTL_STD as i64),
        ("DCNTL_IRQD", DCNTL_IRQD as i64),
        ("DCNTL_COM", DCNTL_COM as i64),
        ("SIOP_ADDER", SIOP_ADDER as i64),
        ("SIOP_SIEN0", SIOP_SIEN0 as i64),
        ("SIEN0_MA", SIEN0_MA as i64),
        ("SIEN0_CMP", SIEN0_CMP as i64),
        ("SIEN0_SEL", SIEN0_SEL as i64),
        ("SIEN0_RSL", SIEN0_RSL as i64),
        ("SIEN0_SGE", SIEN0_SGE as i64),
        ("SIEN0_UDC", SIEN0_UDC as i64),
        ("SIEN0_SRT", SIEN0_SRT as i64),
        ("SIEN0_PAR", SIEN0_PAR as i64),
        ("SIOP_SIEN1", SIOP_SIEN1 as i64),
        ("SIEN1_SBMC", SIEN1_SBMC as i64),
        ("SIEN1_STO", SIEN1_STO as i64),
        ("SIEN1_GEN", SIEN1_GEN as i64),
        ("SIEN1_HTH", SIEN1_HTH as i64),
        ("SIOP_SIST0", SIOP_SIST0 as i64),
        ("SIST0_MA", SIST0_MA as i64),
        ("SIST0_CMP", SIST0_CMP as i64),
        ("SIST0_SEL", SIST0_SEL as i64),
        ("SIST0_RSL", SIST0_RSL as i64),
        ("SIST0_SGE", SIST0_SGE as i64),
        ("SIST0_UDC", SIST0_UDC as i64),
        ("SIST0_RST", SIST0_RST as i64),
        ("SIST0_PAR", SIST0_PAR as i64),
        ("SIOP_SIST1", SIOP_SIST1 as i64),
        ("SIST1_SBMC", SIST1_SBMC as i64),
        ("SIST1_STO", SIST1_STO as i64),
        ("SIST1_GEN", SIST1_GEN as i64),
        ("SIST1_HTH", SIST1_HTH as i64),
        ("SIOP_SLPAR", SIOP_SLPAR as i64),
        ("SIOP_SWIDE", SIOP_SWIDE as i64),
        ("SIOP_MACNTL", SIOP_MACNTL as i64),
        ("SIOP_GPCNTL", SIOP_GPCNTL as i64),
        ("GPCNTL_ME", GPCNTL_ME as i64),
        ("GPCNTL_FE", GPCNTL_FE as i64),
        ("GPCNTL_IN4", GPCNTL_IN4 as i64),
        ("GPCNTL_IN3", GPCNTL_IN3 as i64),
        ("GPCNTL_IN2", GPCNTL_IN2 as i64),
        ("GPCNTL_IN1", GPCNTL_IN1 as i64),
        ("GPCNTL_IN0", GPCNTL_IN0 as i64),
        ("SIOP_STIME0", SIOP_STIME0 as i64),
        ("STIME0_HTH_SHIFT", STIME0_HTH_SHIFT as i64),
        ("STIME0_HTH_MASK", STIME0_HTH_MASK as i64),
        ("STIME0_SEL_SHIFT", STIME0_SEL_SHIFT as i64),
        ("STIME0_SEL_MASK", STIME0_SEL_MASK as i64),
        ("SIOP_STIME1", SIOP_STIME1 as i64),
        ("STIME1_HTHBA", STIME1_HTHBA as i64),
        ("STIME1_GENSF", STIME1_GENSF as i64),
        ("STIME1_HTHSF", STIME1_HTHSF as i64),
        ("STIME1_GEN_SHIFT", STIME1_GEN_SHIFT as i64),
        ("STIME1_GEN_MASK", STIME1_GEN_MASK as i64),
        ("SIOP_RESPID0", SIOP_RESPID0 as i64),
        ("SIOP_RESPID1", SIOP_RESPID1 as i64),
        ("SIOP_STEST0", SIOP_STEST0 as i64),
        ("SIOP_STEST1", SIOP_STEST1 as i64),
        ("STEST1_DOGE", STEST1_DOGE as i64),
        ("STEST1_DIGE", STEST1_DIGE as i64),
        ("STEST1_DBLEN", STEST1_DBLEN as i64),
        ("STEST1_DBLSEL", STEST1_DBLSEL as i64),
        ("SIOP_STEST2", SIOP_STEST2 as i64),
        ("STEST2_DIF", STEST2_DIF as i64),
        ("STEST2_EXT", STEST2_EXT as i64),
        ("SIOP_STEST3", SIOP_STEST3 as i64),
        ("STEST3_TE", STEST3_TE as i64),
        ("STEST3_HSC", STEST3_HSC as i64),
        ("SIOP_STEST4", SIOP_STEST4 as i64),
        ("STEST4_MODE_MASK", STEST4_MODE_MASK as i64),
        ("STEST4_MODE_DIF", STEST4_MODE_DIF as i64),
        ("STEST4_MODE_SE", STEST4_MODE_SE as i64),
        ("STEST4_MODE_LVD", STEST4_MODE_LVD as i64),
        ("STEST4_LOCK", STEST4_LOCK as i64),
        ("SIOP_SIDL", SIOP_SIDL as i64),
        ("SIOP_SODL", SIOP_SODL as i64),
        ("SIOP_SBDL", SIOP_SBDL as i64),
        ("SIOP_SCRATCHB", SIOP_SCRATCHB as i64),
        ("SIOP_SCRATCHC", SIOP_SCRATCHC as i64),
        ("SIOP_SCRATCHD", SIOP_SCRATCHD as i64),
        ("SIOP_SCRATCHE", SIOP_SCRATCHE as i64),
        ("SIOP_SCRATCHF", SIOP_SCRATCHF as i64),
        ("SIOP_SCRATCHG", SIOP_SCRATCHG as i64),
        ("SIOP_SCRATCHH", SIOP_SCRATCHH as i64),
        ("SIOP_SCRATCHI", SIOP_SCRATCHI as i64),
        ("SIOP_SCRATCHJ", SIOP_SCRATCHJ as i64),
        ("SIOP_SCNTL4", SIOP_SCNTL4 as i64),
        ("SCNTL4_XCLKS_ST", SCNTL4_XCLKS_ST as i64),
        ("SCNTL4_XCLKS_DT", SCNTL4_XCLKS_DT as i64),
        ("SCNTL4_XCLKH_ST", SCNTL4_XCLKH_ST as i64),
        ("SCNTL4_XCLKH_DT", SCNTL4_XCLKH_DT as i64),
        ("SCNTL4_AIPEN", SCNTL4_AIPEN as i64),
        ("SCNTL4_U3EN", SCNTL4_U3EN as i64),
        ("SIOP_DFBC", SIOP_DFBC as i64),
        ("SIOP_AIPCNTL0", SIOP_AIPCNTL0 as i64),
        ("AIPCNTL0_ERRLIVE", AIPCNTL0_ERRLIVE as i64),
        ("AIPCNTL0_ERR", AIPCNTL0_ERR as i64),
        ("AIPCNTL0_PARITYERRs", AIPCNTL0_PARITYERRs as i64),
        ("SIOP_AIPCNTL1", SIOP_AIPCNTL1 as i64),
        ("AIPCNTL1_DIS", AIPCNTL1_DIS as i64),
        ("AIPCNTL1_RSETERR", AIPCNTL1_RSETERR as i64),
        ("AIPCNTL1_FB", AIPCNTL1_FB as i64),
        ("AIPCNTL1_RSET", AIPCNTL1_RSET as i64),
        ("SIOP_NVRAM_SYM_SIZE", SIOP_NVRAM_SYM_SIZE as i64),
        ("SIOP_NVRAM_SYM_ADDRESS", SIOP_NVRAM_SYM_ADDRESS as i64),
        ("NVRAM_SYM_F_SCAM_ENABLE", NVRAM_SYM_F_SCAM_ENABLE as i64),
        (
            "NVRAM_SYM_F_PARITY_ENABLE",
            NVRAM_SYM_F_PARITY_ENABLE as i64,
        ),
        (
            "NVRAM_SYM_F_VERBOSE_MESSAGES",
            NVRAM_SYM_F_VERBOSE_MESSAGES as i64,
        ),
        ("NVRAM_SYM_F_CHS_MAPPING", NVRAM_SYM_F_CHS_MAPPING as i64),
        ("NVRAM_SYM_F1_SCAN_HI_LO", NVRAM_SYM_F1_SCAN_HI_LO as i64),
        (
            "NVRAM_SYM_TERM_CANT_PROGRAM",
            NVRAM_SYM_TERM_CANT_PROGRAM as i64,
        ),
        ("NVRAM_SYM_TERM_ENABLED", NVRAM_SYM_TERM_ENABLED as i64),
        ("NVRAM_SYM_TERM_DISABLED", NVRAM_SYM_TERM_DISABLED as i64),
        (
            "NVRAM_SYM_RMVBL_NO_SUPPORT",
            NVRAM_SYM_RMVBL_NO_SUPPORT as i64,
        ),
        (
            "NVRAM_SYM_RMVBL_BOOT_DEVICE",
            NVRAM_SYM_RMVBL_BOOT_DEVICE as i64,
        ),
        (
            "NVRAM_SYM_RMVBL_MEDIA_INSTALLED",
            NVRAM_SYM_RMVBL_MEDIA_INSTALLED as i64,
        ),
        (
            "NVRAM_SYM_HOST_F_SCAN_AT_BOOT",
            NVRAM_SYM_HOST_F_SCAN_AT_BOOT as i64,
        ),
        (
            "NVRAM_SYM_TARG_F_DISCONNECT_EN",
            NVRAM_SYM_TARG_F_DISCONNECT_EN as i64,
        ),
        (
            "NVRAM_SYM_TARG_F_SCAN_AT_BOOT",
            NVRAM_SYM_TARG_F_SCAN_AT_BOOT as i64,
        ),
        (
            "NVRAM_SYM_TARG_F_SCAN_LUNS",
            NVRAM_SYM_TARG_F_SCAN_LUNS as i64,
        ),
        ("NVRAM_SYM_TARG_F_TQ_EN", NVRAM_SYM_TARG_F_TQ_EN as i64),
        (
            "NVRAM_SYM_SCAM_DEFAULT_METHOD",
            NVRAM_SYM_SCAM_DEFAULT_METHOD as i64,
        ),
        (
            "NVRAM_SYM_SCAM_DONT_ASSIGN",
            NVRAM_SYM_SCAM_DONT_ASSIGN as i64,
        ),
        (
            "NVRAM_SYM_SCAM_SET_SPECIFIC_ID",
            NVRAM_SYM_SCAM_SET_SPECIFIC_ID as i64,
        ),
        (
            "NVRAM_SYM_SCAM_USE_ORDER_GIVEN",
            NVRAM_SYM_SCAM_USE_ORDER_GIVEN as i64,
        ),
        ("NVRAM_SYM_SCAM_UNKNOWN", NVRAM_SYM_SCAM_UNKNOWN as i64),
        (
            "NVRAM_SYM_SCAM_DEVICE_NOT_FOUND",
            NVRAM_SYM_SCAM_DEVICE_NOT_FOUND as i64,
        ),
        (
            "NVRAM_SYM_SCAM_ID_NOT_SET",
            NVRAM_SYM_SCAM_ID_NOT_SET as i64,
        ),
        ("NVRAM_SYM_SCAM_ID_VALID", NVRAM_SYM_SCAM_ID_VALID as i64),
        ("SIOP_NVRAM_TEK_SIZE", SIOP_NVRAM_TEK_SIZE as i64),
        (
            "SIOP_NVRAM_TEK_93c46_ADDRESS",
            SIOP_NVRAM_TEK_93c46_ADDRESS as i64,
        ),
        (
            "SIOP_NVRAM_TEK_24c16_ADDRESS",
            SIOP_NVRAM_TEK_24c16_ADDRESS as i64,
        ),
    ];
    for &(name, v) in ours {
        assert_eq!(reftest::int(&defs, name), Some(v), "{name}");
    }
}
