use super::*;

#[test]
fn capability_fields() {
    // CAP of QEMU's ich9-ahci: 6 ports, 32 command slots, NCQ, SSS, 64-bit, ISS gen 1.
    let cap: u32 = 0xc030_ff05;
    assert_eq!(ahci_reg_cap_np(cap), 6);
    assert_eq!(ahci_reg_cap_ncs(cap), 32);
    assert_ne!(cap & AHCI_REG_CAP_SNCQ, 0);
    assert_ne!(cap & AHCI_REG_CAP_S64A, 0);
    assert_eq!(ahci_reg_ccc_ctl_int(0x0000_0028), 5);
    assert_eq!(ahci_port_region(0), 0x100);
    assert_eq!(ahci_port_region(5), 0x380);
    assert_eq!(ahci_preg_cmd_ccs(0x0000_1f00), 31);
    assert_eq!(ahci_preg_serr_err(0x0401_0002), 0x0002);
    assert_eq!(ahci_preg_serr_diag(0x0401_0002), 0x0401);
}

#[test]
#[ignore = "needs OPENBSD_SRC (just test-ref)"]
fn values_match_the_c_header() {
    let defs = crate::reftest::defines("sys/dev/ic/ahcireg.h");
    let mut names = crate::reftest::assert_defines!(defs;
        AHCI_REG_CAP, AHCI_REG_CAP_SXS, AHCI_REG_CAP_EMS, AHCI_REG_CAP_CCCS, AHCI_REG_CAP_PSC,
        AHCI_REG_CAP_SSC, AHCI_REG_CAP_PMD, AHCI_REG_CAP_FBSS, AHCI_REG_CAP_SPM,
        AHCI_REG_CAP_SAM, AHCI_REG_CAP_SNZO, AHCI_REG_CAP_ISS, AHCI_REG_CAP_ISS_G1,
        AHCI_REG_CAP_ISS_G2, AHCI_REG_CAP_ISS_G3, AHCI_REG_CAP_SCLO, AHCI_REG_CAP_SAL,
        AHCI_REG_CAP_SALP, AHCI_REG_CAP_SSS, AHCI_REG_CAP_SMPS, AHCI_REG_CAP_SSNTF,
        AHCI_REG_CAP_SNCQ, AHCI_REG_CAP_S64A, AHCI_REG_GHC, AHCI_REG_GHC_HR, AHCI_REG_GHC_IE,
        AHCI_REG_GHC_MRSM, AHCI_REG_GHC_AE, AHCI_REG_IS, AHCI_REG_PI, AHCI_REG_VS,
        AHCI_REG_VS_0_95, AHCI_REG_VS_1_0, AHCI_REG_VS_1_1, AHCI_REG_VS_1_2, AHCI_REG_VS_1_3,
        AHCI_REG_VS_1_3_1, AHCI_REG_CCC_CTL, AHCI_REG_CCC_PORTS, AHCI_REG_EM_LOC,
        AHCI_REG_EM_CTL, AHCI_REG_CAP2, AHCI_REG_CAP2_DESO, AHCI_REG_CAP2_SADM,
        AHCI_REG_CAP2_SDS, AHCI_REG_CAP2_APST, AHCI_REG_CAP2_NVMP, AHCI_REG_CAP2_BOH,
        AHCI_PORT_SIZE, AHCI_PREG_CLB, AHCI_PREG_CLBU, AHCI_PREG_FB, AHCI_PREG_FBU,
        AHCI_PREG_IS, AHCI_PREG_IS_DHRS, AHCI_PREG_IS_PSS, AHCI_PREG_IS_DSS, AHCI_PREG_IS_SDBS,
        AHCI_PREG_IS_UFS, AHCI_PREG_IS_DPS, AHCI_PREG_IS_PCS, AHCI_PREG_IS_DMPS,
        AHCI_PREG_IS_PRCS, AHCI_PREG_IS_IPMS, AHCI_PREG_IS_OFS, AHCI_PREG_IS_INFS,
        AHCI_PREG_IS_IFS, AHCI_PREG_IS_HBDS, AHCI_PREG_IS_HBFS, AHCI_PREG_IS_TFES,
        AHCI_PREG_IS_CPDS, AHCI_PREG_IE, AHCI_PREG_IE_DHRE, AHCI_PREG_IE_PSE, AHCI_PREG_IE_DSE,
        AHCI_PREG_IE_SDBE, AHCI_PREG_IE_UFE, AHCI_PREG_IE_DPE, AHCI_PREG_IE_PCE,
        AHCI_PREG_IE_DMPE, AHCI_PREG_IE_PRCE, AHCI_PREG_IE_IPME, AHCI_PREG_IE_OFE,
        AHCI_PREG_IE_INFE, AHCI_PREG_IE_IFE, AHCI_PREG_IE_HBDE, AHCI_PREG_IE_HBFE,
        AHCI_PREG_IE_TFEE, AHCI_PREG_IE_CPDE, AHCI_PREG_CMD, AHCI_PREG_CMD_ST,
        AHCI_PREG_CMD_SUD, AHCI_PREG_CMD_POD, AHCI_PREG_CMD_CLO, AHCI_PREG_CMD_FRE,
        AHCI_PREG_CMD_MPSS, AHCI_PREG_CMD_FR, AHCI_PREG_CMD_CR, AHCI_PREG_CMD_CPS,
        AHCI_PREG_CMD_PMA, AHCI_PREG_CMD_HPCP, AHCI_PREG_CMD_MPSP, AHCI_PREG_CMD_CPD,
        AHCI_PREG_CMD_ESP, AHCI_PREG_CMD_ATAPI, AHCI_PREG_CMD_DLAE, AHCI_PREG_CMD_ALPE,
        AHCI_PREG_CMD_ASP, AHCI_PREG_CMD_ICC, AHCI_PREG_CMD_ICC_SLUMBER,
        AHCI_PREG_CMD_ICC_PARTIAL, AHCI_PREG_CMD_ICC_ACTIVE, AHCI_PREG_CMD_ICC_IDLE,
        AHCI_PREG_TFD, AHCI_PREG_TFD_STS, AHCI_PREG_TFD_STS_ERR, AHCI_PREG_TFD_STS_DRQ,
        AHCI_PREG_TFD_STS_BSY, AHCI_PREG_TFD_ERR, AHCI_PREG_SIG, AHCI_PREG_SSTS,
        AHCI_PREG_SSTS_DET, AHCI_PREG_SSTS_DET_NONE, AHCI_PREG_SSTS_DET_DEV_NE,
        AHCI_PREG_SSTS_DET_DEV, AHCI_PREG_SSTS_DET_PHYOFFLINE, AHCI_PREG_SSTS_SPD,
        AHCI_PREG_SSTS_SPD_NONE, AHCI_PREG_SSTS_SPD_GEN1, AHCI_PREG_SSTS_SPD_GEN2,
        AHCI_PREG_SSTS_SPD_GEN3, AHCI_PREG_SSTS_IPM, AHCI_PREG_SSTS_IPM_NONE,
        AHCI_PREG_SSTS_IPM_ACTIVE, AHCI_PREG_SSTS_IPM_PARTIAL, AHCI_PREG_SSTS_IPM_SLUMBER,
        AHCI_PREG_SCTL, AHCI_PREG_SCTL_DET, AHCI_PREG_SCTL_DET_NONE, AHCI_PREG_SCTL_DET_INIT,
        AHCI_PREG_SCTL_DET_DISABLE, AHCI_PREG_SCTL_SPD, AHCI_PREG_SCTL_SPD_ANY,
        AHCI_PREG_SCTL_SPD_GEN1, AHCI_PREG_SCTL_SPD_GEN2, AHCI_PREG_SCTL_SPD_GEN3,
        AHCI_PREG_SCTL_IPM, AHCI_PREG_SCTL_IPM_NONE, AHCI_PREG_SCTL_IPM_NOPARTIAL,
        AHCI_PREG_SCTL_IPM_NOSLUMBER, AHCI_PREG_SCTL_IPM_DISABLED, AHCI_PREG_SERR,
        AHCI_PREG_SERR_ERR_I, AHCI_PREG_SERR_ERR_M, AHCI_PREG_SERR_ERR_T, AHCI_PREG_SERR_ERR_C,
        AHCI_PREG_SERR_ERR_P, AHCI_PREG_SERR_ERR_E, AHCI_PREG_SERR_DIAG_N,
        AHCI_PREG_SERR_DIAG_I, AHCI_PREG_SERR_DIAG_W, AHCI_PREG_SERR_DIAG_B,
        AHCI_PREG_SERR_DIAG_D, AHCI_PREG_SERR_DIAG_C, AHCI_PREG_SERR_DIAG_H,
        AHCI_PREG_SERR_DIAG_S, AHCI_PREG_SERR_DIAG_T, AHCI_PREG_SERR_DIAG_F,
        AHCI_PREG_SERR_DIAG_X, AHCI_PREG_SACT, AHCI_PREG_CI, AHCI_PREG_CI_ALL_SLOTS,
        AHCI_PREG_SNTF, AHCI_PREG_FBS, AHCI_PREG_FBS_DWE, AHCI_PREG_FBS_ADO, AHCI_PREG_FBS_DEV,
        AHCI_PREG_FBS_SDE, AHCI_PREG_FBS_DEC, AHCI_PREG_FBS_EN, AHCI_CMD_LIST_FLAG_CFL,
        AHCI_CMD_LIST_FLAG_A, AHCI_CMD_LIST_FLAG_W, AHCI_CMD_LIST_FLAG_P, AHCI_CMD_LIST_FLAG_R,
        AHCI_CMD_LIST_FLAG_B, AHCI_CMD_LIST_FLAG_C, AHCI_CMD_LIST_FLAG_PMP,
        AHCI_CMD_LIST_FLAG_PMP_SHIFT, AHCI_PRDT_FLAG_INTR, AHCI_MAX_PRDT, AHCI_MAX_PORTS,
    );
    // The `%b` strings are not simple defines.
    names.extend([
        "AHCI_FMT_CAP",
        "AHCI_FMT_GHC",
        "AHCI_FMT_CAP2",
        "AHCI_PFMT_IS",
        "AHCI_PFMT_IE",
        "AHCI_PFMT_CMD",
        "AHCI_PFMT_TFD_STS",
        "AHCI_PFMT_SERR_ERR",
        "AHCI_PFMT_SERR_DIAG",
    ]);
    crate::reftest::assert_complete(&defs, "AHCI_", &names);
}
