//! Tests for `acpireg`.

use super::*;

#[test]
#[ignore = "needs OPENBSD_SRC (just test-ref)"]
fn values_match_the_c_header() {
    let defs = crate::reftest::defines("sys/dev/acpi/acpireg.h");
    // Not compared (the helper reads one line of `#define`): the string constants (`*_SIG`,
    // `ACPI_DEV_*`) and the function-like macros.
    crate::reftest::assert_defines!(defs;
    GAS_SYSTEM_MEMORY, GAS_SYSTEM_IOSPACE, GAS_PCI_CFG_SPACE, GAS_EMBEDDED, GAS_SMBUS,
    GAS_FUNCTIONAL_FIXED, GAS_ACCESS_UNDEFINED, GAS_ACCESS_BYTE, GAS_ACCESS_WORD,
    GAS_ACCESS_DWORD, GAS_ACCESS_QWORD, FADT_INT_DUAL_PIC, FADT_INT_MULTI_APIC, FADT_PM_UNSPEC,
    FADT_PM_DESKTOP, FADT_PM_MOBILE, FADT_PM_WORKSTATION, FADT_PM_ENT_SERVER,
    FADT_PM_SOHO_SERVER, FADT_PM_APPLIANCE, FADT_PM_PERF_SERVER, FADT_LEGACY_DEVICES,
    FADT_i8042, FADT_NO_VGA, FADT_NO_MSI, FADT_WBINVD, FADT_WBINVD_FLUSH, FADT_PROC_C1,
    FADT_P_LVL2_UP, FADT_PWR_BUTTON, FADT_SLP_BUTTON, FADT_FIX_RTC, FADT_RTC_S4,
    FADT_TMR_VAL_EXT, FADT_DCK_CAP, FADT_RESET_REG_SUP, FADT_SEALED_CASE, FADT_HEADLESS,
    FADT_CPU_SW_SLP, FADT_PCI_EXP_WAK, FADT_USE_PLATFORM_CLOCK, FADT_S4_RTC_STS_VALID,
    FADT_REMOTE_POWER_ON_CAPABLE, FADT_FORCE_APIC_CLUSTER_MODEL, FADT_FORCE_APIC_PHYS_DEST_MODE,
    FADT_HW_REDUCED_ACPI, FADT_POWER_S0_IDLE_CAPABLE, ACPI_APIC_PCAT_COMPAT, ACPI_MADT_LAPIC,
    ACPI_PROC_ENABLE, ACPI_MADT_IOAPIC, ACPI_MADT_OVERRIDE, ACPI_OVERRIDE_BUS_ISA,
    ACPI_OVERRIDE_POLARITY_BITS, ACPI_OVERRIDE_POLARITY_BUS, ACPI_OVERRIDE_POLARITY_HIGH,
    ACPI_OVERRIDE_POLARITY_LOW, ACPI_OVERRIDE_TRIGGER_BITS, ACPI_OVERRIDE_TRIGGER_BUS,
    ACPI_OVERRIDE_TRIGGER_EDGE, ACPI_OVERRIDE_TRIGGER_LEVEL, ACPI_MADT_NMI, ACPI_MADT_LAPIC_NMI,
    ACPI_MADT_LAPIC_OVERRIDE, ACPI_MADT_IO_SAPIC, ACPI_MADT_LOCAL_SAPIC, ACPI_MADT_PLATFORM_INT,
    ACPI_MADT_PLATFORM_PMI, ACPI_MADT_PLATFORM_INIT, ACPI_MADT_PLATFORM_CORR_ERROR,
    ACPI_MADT_PLATFORM_CPEI, ACPI_MADT_X2APIC, ACPI_MADT_X2APIC_NMI, ACPI_MADT_GICC,
    ACPI_MADT_OEM_RSVD, SPCR_16550, SPCR_16450, SPCR_ARM_PL011, SPCR_ARM_SBSA,
    FACS_LOCK_PENDING, FACS_LOCK_OWNED, FACS_S4BIOS_F, LPIT_DISABLED,
    LPIT_COUNTER_NOT_AVAILABLE, DMAR_ENDPOINT, DMAR_BRIDGE, DMAR_IOAPIC, DMAR_HPET, DMAR_DRHD,
    DMAR_RMRR, DMAR_ATSR, DMAR_RHSA, IVHD_RESVD, IVHD_ALL, IVHD_SEL, IVHD_SOR, IVHD_EOR,
    IVHD_ALIAS_SEL, IVHD_ALIAS_SOR, IVHD_EXT_SEL, IVHD_EXT_SOR, IVHD_SPECIAL, IVHD_ATS_DIS,
    IVHD_IOAPIC, IVHD_HPET, IVMD_EXCLRANGE, IVMD_IW, IVMD_IR, IVMD_UNITY, IVHD_PPRSUP,
    IVHD_PREFSUP, IVHD_COHERENT, IVHD_IOTLB, IVHD_ISOC, IVHD_RESPASSPW, IVHD_PASSPW,
    IVHD_HTTUNEN, IVHD_UNITID_SHIFT, IVHD_UNITID_MASK, IVHD_MSINUM_SHIFT, IVHD_MSINUM_MASK,
    IVRS_IVHD, IVRS_IVHD_EXT, IVRS_IVMD_ALL, IVRS_IVMD_SPECIFIED, IVRS_IVMD_RANGE, IVRS_ATSRNG,
    IVRS_VASIZE_SHIFT, IVRS_VASIZE_MASK, IVRS_PASIZE_SHIFT, IVRS_PASIZE_MASK, ACPI_IORT_ITS,
    ACPI_IORT_NAMED_COMPONENT, ACPI_IORT_ROOT_COMPLEX, ACPI_IORT_SMMU, ACPI_IORT_SMMU_V3,
    ACPI_IORT_SMMU_V1, ACPI_IORT_SMMU_V2, ACPI_IORT_SMMU_CORELINK_MMU400,
    ACPI_IORT_SMMU_CORELINK_MMU500, ACPI_IORT_SMMU_CORELINK_MMU401,
    ACPI_IORT_SMMU_CAVIUM_THUNDERX, ACPI_IORT_SMMU_DVM, ACPI_IORT_SMMU_COHERENT,
    ACPI_IORT_SMMU_INTR_EDGE, ACPI_IORT_SMMU_V3_PROX_DOM_VALID,
    ACPI_IORT_SMMU_V3_DEVID_MAP_VALID, ACPI_IORT_SMMU_V3_GENERIC,
    ACPI_IORT_SMMU_V3_HISILICON_HI161X, ACPI_IORT_SMMU_V3_CAVIUM_CN99X,
    ACPI_IORT_MAPPING_SINGLE, ACPI_FREQUENCY, ACPI_PM1_STATUS, ACPI_PM1_TMR_STS,
    ACPI_PM1_BM_STS, ACPI_PM1_GBL_STS, ACPI_PM1_PWRBTN_STS, ACPI_PM1_SLPBTN_STS,
    ACPI_PM1_RTC_STS, ACPI_PM1_PCIEXP_WAKE_STS, ACPI_PM1_WAK_STS, ACPI_PM1_ENABLE,
    ACPI_PM1_TMR_EN, ACPI_PM1_GBL_EN, ACPI_PM1_PWRBTN_EN, ACPI_PM1_SLPBTN_EN, ACPI_PM1_RTC_EN,
    ACPI_PM1_PCIEXP_WAKE_DIS, ACPI_PM1_CONTROL, ACPI_PM1_SCI_EN, ACPI_PM1_BM_RLD,
    ACPI_PM1_GBL_RLS, ACPI_PM1_SLP_TYPX_MASK, ACPI_PM1_SLP_EN, ACPI_PM2_CONTROL,
    ACPI_PM2_ARB_DIS, ACPI_OPREG_SYSMEM, ACPI_OPREG_SYSIO, ACPI_OPREG_PCICFG, ACPI_OPREG_EC,
    ACPI_OPREG_SMBUS, ACPI_OPREG_CMOS, ACPI_OPREG_PCIBAR, ACPI_OPREG_IPMI, ACPI_OPREG_GPIO,
    ACPI_OPREG_GSB, ACPI_STATE_S0, ACPI_STATE_S1, ACPI_STATE_S2, ACPI_STATE_S3, ACPI_STATE_S4,
    ACPI_STATE_S5, ACPI_STATE_D0, ACPI_STATE_D1, ACPI_STATE_D2, ACPI_STATE_D3,
    );
}

#[test]
fn table_sizes_are_the_c_sizes() {
    assert_eq!(size_of::<AcpiTableHeader>(), 36);
    assert_eq!(size_of::<AcpiGas>(), 12);
    assert_eq!(size_of::<AcpiFacs>(), 64);
    assert_eq!(size_of::<AcpiFadt>(), 268);
    assert_eq!(size_of::<AcpiRsdp>(), 36);
    assert_eq!(size_of::<AcpiLpitEntry>(), 56);
}

#[test]
fn field_offsets() {
    use core::mem::offset_of;
    assert_eq!(offset_of!(AcpiFadt, sci_int), 46);
    assert_eq!(offset_of!(AcpiFadt, flags), 112);
    assert_eq!(offset_of!(AcpiFadt, reset_reg), 116);
    assert_eq!(offset_of!(AcpiFadt, x_dsdt), 140);
    assert_eq!(offset_of!(AcpiFacs, x_wakeup_vector), 24);
    assert_eq!(offset_of!(AcpiRsdp, rsdp_xsdt), 24);
}

#[test]
fn signatures() {
    assert_eq!(RSDP_SIG, b"RSD PTR ");
    assert_eq!(FADT_SIG, b"FACP");
    assert_eq!(MADT_SIG, b"APIC");
}

#[test]
fn address_macros() {
    let addr = 0x0123_0456_0007_0008u64;
    assert_eq!(acpi_pci_seg(addr), 0x0123);
    assert_eq!(acpi_pci_bus(addr), 0x04);
    assert_eq!(acpi_pci_dev(addr), 0x56);
    assert_eq!(acpi_pci_fn(addr), 0x0007);
    assert_eq!(acpi_pci_reg(addr), 0x0008);
    assert_eq!(acpi_adr_pcidev(0x001f_0003), 0x1f);
    assert_eq!(acpi_adr_pcifun(0x001f_0003), 3);
    assert_eq!(acpi_pm1_slp_typx(5), 0x1400);
    assert_eq!(acpi_pm1_slp_typx(7) & !ACPI_PM1_SLP_TYPX_MASK, 0);
}
