/*	$OpenBSD: init_sysent.c,v 1.291 2026/08/12 15:05:21 naddy Exp $	*/

//! System call switch table.
//!
//! DO NOT EDIT: this file is automatically generated by `cargo xtask gen-syscalls`
//! (`tools/xtask/src/syscalls.rs`, what `kern/makesyscalls.sh` does for the C tree)
//! from `sys/kern/syscalls.master`.
//! created from; OpenBSD: syscalls.master,v 1.273 2026/08/12 15:04:45 naddy Exp
//!
//! Upstream: sys/kern/init_sysent.c @ 3ce1f3f79392
//!
//! ## Deviations
//! - An entry points at its `sys_*` function only when `sys/kern` or `sys/uvm` defines
//!   it (`pub fn sys_<name>(`); the others are `sys_nosys` with a note, so the table
//!   always compiles. Rerun the generator after porting a syscall.

use crate::kern::kern_descrip::{
    sys_close, sys_closefrom, sys_dup, sys_dup2, sys_dup3, sys_fcntl, sys_flock, sys_fpathconf,
    sys_fstat, sys_getdtablecount,
};
use crate::kern::kern_exec::sys_execve;
use crate::kern::kern_exit::sys_exit;
use crate::kern::kern_prot::{
    sys___get_tcb, sys___set_tcb, sys_getegid, sys_geteuid, sys_getgid, sys_getgroups,
    sys_getlogin_r, sys_getpgid, sys_getpgrp, sys_getpid, sys_getppid, sys_getresgid,
    sys_getresuid, sys_getsid, sys_getthrid, sys_getthrname, sys_getuid, sys_issetugid,
    sys_setegid, sys_seteuid, sys_setgid, sys_setgroups, sys_setlogin, sys_setpgid, sys_setregid,
    sys_setresgid, sys_setresuid, sys_setreuid, sys_setsid, sys_setthrname, sys_setuid,
};
use crate::kern::kern_resource::{
    sys_getpriority, sys_getrlimit, sys_getrusage, sys_setpriority, sys_setrlimit,
};
use crate::kern::kern_sig::sys_nosys;
use crate::kern::kern_sig::{
    sys___thrsigdivert, sys_kill, sys_sigaction, sys_sigaltstack, sys_sigpending, sys_sigprocmask,
    sys_sigreturn, sys_sigsuspend, sys_thrkill,
};
use crate::kern::kern_sysctl::sys_sysctl;
use crate::kern::sys_generic::{sys_ioctl, sys_read, sys_readv, sys_write, sys_writev};
use crate::kern::sys_pipe::{sys_pipe, sys_pipe2};
use crate::kern::vfs_getcwd::sys___getcwd;
use crate::kern::vfs_syscalls::{
    sys___pledge_open, sys___realpath, sys_access, sys_chdir, sys_chflags, sys_chflagsat,
    sys_chmod, sys_chown, sys_chroot, sys_faccessat, sys_fchdir, sys_fchflags, sys_fchmod,
    sys_fchmodat, sys_fchown, sys_fchownat, sys_fhopen, sys_fhstat, sys_fhstatfs, sys_fstatat,
    sys_fstatfs, sys_fsync, sys_ftruncate, sys_futimens, sys_futimes, sys_getdents, sys_getfh,
    sys_getfsstat, sys_lchown, sys_link, sys_linkat, sys_lseek, sys_lstat, sys_mkdir, sys_mkdirat,
    sys_mkfifo, sys_mkfifoat, sys_mknod, sys_mknodat, sys_mount, sys_open, sys_openat,
    sys_pathconf, sys_pathconfat, sys_pread, sys_preadv, sys_pwrite, sys_pwritev, sys_quotactl,
    sys_readlink, sys_readlinkat, sys_rename, sys_renameat, sys_revoke, sys_rmdir, sys_stat,
    sys_statfs, sys_symlink, sys_symlinkat, sys_sync, sys_truncate, sys_umask, sys_unlink,
    sys_unlinkat, sys_unmount, sys_unveil, sys_utimensat, sys_utimes,
};
use crate::sys::syscall::SYS_MAXSYSCALL;
use crate::sys::syscallargs::{
    SysAccept4Args, SysAcceptArgs, SysAccessArgs, SysAdjfreqArgs, SysAdjtimeArgs, SysBindArgs,
    SysChdirArgs, SysChflagsArgs, SysChflagsatArgs, SysChmodArgs, SysChownArgs, SysChrootArgs,
    SysClockGetresArgs, SysClockGettimeArgs, SysClockSettimeArgs, SysCloseArgs, SysClosefromArgs,
    SysConnectArgs, SysDup2Args, SysDup3Args, SysDupArgs, SysExecveArgs, SysExitArgs,
    SysFaccessatArgs, SysFchdirArgs, SysFchflagsArgs, SysFchmodArgs, SysFchmodatArgs,
    SysFchownArgs, SysFchownatArgs, SysFcntlArgs, SysFhopenArgs, SysFhstatArgs, SysFhstatfsArgs,
    SysFlockArgs, SysFpathconfArgs, SysFstatArgs, SysFstatatArgs, SysFstatfsArgs, SysFsyncArgs,
    SysFtruncateArgs, SysFutexArgs, SysFutimensArgs, SysFutimesArgs, SysGetcwdArgs,
    SysGetdentsArgs, SysGetentropyArgs, SysGetfhArgs, SysGetfsstatArgs, SysGetgroupsArgs,
    SysGetitimerArgs, SysGetloginRArgs, SysGetpeernameArgs, SysGetpgidArgs, SysGetpriorityArgs,
    SysGetresgidArgs, SysGetresuidArgs, SysGetrlimitArgs, SysGetrusageArgs, SysGetsidArgs,
    SysGetsocknameArgs, SysGetsockoptArgs, SysGetthrnameArgs, SysGettimeofdayArgs, SysIoctlArgs,
    SysKbindArgs, SysKeventArgs, SysKillArgs, SysKqueue1Args, SysLchownArgs, SysLinkArgs,
    SysLinkatArgs, SysListenArgs, SysLseekArgs, SysLstatArgs, SysMadviseArgs, SysMimmutableArgs,
    SysMinheritArgs, SysMkdirArgs, SysMkdiratArgs, SysMkfifoArgs, SysMkfifoatArgs, SysMknodArgs,
    SysMknodatArgs, SysMlockArgs, SysMlockallArgs, SysMmapArgs, SysMountArgs, SysMprotectArgs,
    SysMqueryArgs, SysMsyncArgs, SysMunlockArgs, SysMunmapArgs, SysNanosleepArgs, SysObreakArgs,
    SysOpenArgs, SysOpenatArgs, SysPathconfArgs, SysPathconfatArgs, SysPinsyscallsArgs,
    SysPipe2Args, SysPipeArgs, SysPledgeArgs, SysPledgeOpenArgs, SysPollArgs, SysPpollArgs,
    SysPreadArgs, SysPreadvArgs, SysProfilArgs, SysPselectArgs, SysPwriteArgs, SysPwritevArgs,
    SysQuotactlArgs, SysReadArgs, SysReadlinkArgs, SysReadlinkatArgs, SysReadvArgs,
    SysRealpathArgs, SysRebootArgs, SysRecvfromArgs, SysRecvmmsgArgs, SysRecvmsgArgs,
    SysRenameArgs, SysRenameatArgs, SysRevokeArgs, SysRmdirArgs, SysSelectArgs, SysSendmmsgArgs,
    SysSendmsgArgs, SysSendsyslogArgs, SysSendtoArgs, SysSetTcbArgs, SysSetegidArgs,
    SysSeteuidArgs, SysSetgidArgs, SysSetgroupsArgs, SysSetitimerArgs, SysSetloginArgs,
    SysSetpgidArgs, SysSetpriorityArgs, SysSetregidArgs, SysSetresgidArgs, SysSetresuidArgs,
    SysSetreuidArgs, SysSetrlimitArgs, SysSetrtableArgs, SysSetsockoptArgs, SysSetthrnameArgs,
    SysSettimeofdayArgs, SysSetuidArgs, SysShutdownArgs, SysSigactionArgs, SysSigaltstackArgs,
    SysSigprocmaskArgs, SysSigreturnArgs, SysSigsuspendArgs, SysSocketArgs, SysSocketpairArgs,
    SysStatArgs, SysStatfsArgs, SysSwapctlArgs, SysSymlinkArgs, SysSymlinkatArgs, SysSysarchArgs,
    SysSysctlArgs, SysTforkArgs, SysThrexitArgs, SysThrkillArgs, SysThrsigdivertArgs,
    SysThrsleepArgs, SysThrwakeupArgs, SysTruncateArgs, SysUmaskArgs, SysUnlinkArgs,
    SysUnlinkatArgs, SysUnmountArgs, SysUnveilArgs, SysUtimensatArgs, SysUtimesArgs, SysUtraceArgs,
    SysWait4Args, SysWaitidArgs, SysWriteArgs, SysWritevArgs, SysYpconnectArgs,
};
use crate::sys::systm::{SY_NOLOCK, Sysent};
use crate::uvm::uvm_mmap::{
    sys_kbind, sys_madvise, sys_mimmutable, sys_minherit, sys_mlock, sys_mlockall, sys_mmap,
    sys_mprotect, sys_mquery, sys_msync, sys_munlock, sys_munlockall, sys_munmap, sys_pinsyscalls,
};
use crate::uvm::uvm_unix::sys_obreak;

/// `sysent[]`: the system call switch table, indexed by `SYS_*`.
pub static SYSENT: [Sysent; SYS_MAXSYSCALL] = [
    Sysent::new(0, 0, 0, sys_nosys), // 0 = unimplemented syscall
    Sysent::new(1, size_of::<SysExitArgs>(), 0, sys_exit), // 1 = exit
    Sysent::new(0, 0, 0, sys_nosys), // 2 = fork (sys_fork not ported)
    Sysent::new(3, size_of::<SysReadArgs>(), SY_NOLOCK, sys_read), // 3 = read
    Sysent::new(3, size_of::<SysWriteArgs>(), SY_NOLOCK, sys_write), // 4 = write
    Sysent::new(3, size_of::<SysOpenArgs>(), SY_NOLOCK, sys_open), // 5 = open
    Sysent::new(1, size_of::<SysCloseArgs>(), SY_NOLOCK, sys_close), // 6 = close
    Sysent::new(2, size_of::<SysGetentropyArgs>(), SY_NOLOCK, sys_nosys), // 7 = getentropy (sys_getentropy not ported)
    Sysent::new(2, size_of::<SysTforkArgs>(), 0, sys_nosys), // 8 = __tfork (sys___tfork not ported)
    Sysent::new(2, size_of::<SysLinkArgs>(), 0, sys_link),   // 9 = link
    Sysent::new(1, size_of::<SysUnlinkArgs>(), 0, sys_unlink), // 10 = unlink
    Sysent::new(4, size_of::<SysWait4Args>(), 0, sys_nosys), // 11 = wait4 (sys_wait4 not ported)
    Sysent::new(1, size_of::<SysChdirArgs>(), 0, sys_chdir), // 12 = chdir
    Sysent::new(1, size_of::<SysFchdirArgs>(), 0, sys_fchdir), // 13 = fchdir
    Sysent::new(3, size_of::<SysMknodArgs>(), 0, sys_mknod), // 14 = mknod
    Sysent::new(2, size_of::<SysChmodArgs>(), 0, sys_chmod), // 15 = chmod
    Sysent::new(3, size_of::<SysChownArgs>(), 0, sys_chown), // 16 = chown
    Sysent::new(1, size_of::<SysObreakArgs>(), 0, sys_obreak), // 17 = break
    Sysent::new(0, 0, SY_NOLOCK, sys_getdtablecount),        // 18 = getdtablecount
    Sysent::new(2, size_of::<SysGetrusageArgs>(), 0, sys_getrusage), // 19 = getrusage
    Sysent::new(0, 0, SY_NOLOCK, sys_getpid),                // 20 = getpid
    Sysent::new(4, size_of::<SysMountArgs>(), 0, sys_mount), // 21 = mount
    Sysent::new(2, size_of::<SysUnmountArgs>(), 0, sys_unmount), // 22 = unmount
    Sysent::new(1, size_of::<SysSetuidArgs>(), 0, sys_setuid), // 23 = setuid
    Sysent::new(0, 0, SY_NOLOCK, sys_getuid),                // 24 = getuid
    Sysent::new(0, 0, SY_NOLOCK, sys_geteuid),               // 25 = geteuid
    Sysent::new(0, 0, 0, sys_nosys),                         // 26 = unimplemented ptrace
    Sysent::new(3, size_of::<SysRecvmsgArgs>(), SY_NOLOCK, sys_nosys), // 27 = recvmsg (sys_recvmsg not ported)
    Sysent::new(3, size_of::<SysSendmsgArgs>(), SY_NOLOCK, sys_nosys), // 28 = sendmsg (sys_sendmsg not ported)
    Sysent::new(6, size_of::<SysRecvfromArgs>(), SY_NOLOCK, sys_nosys), // 29 = recvfrom (sys_recvfrom not ported)
    Sysent::new(3, size_of::<SysAcceptArgs>(), SY_NOLOCK, sys_nosys), // 30 = accept (sys_accept not ported)
    Sysent::new(3, size_of::<SysGetpeernameArgs>(), SY_NOLOCK, sys_nosys), // 31 = getpeername (sys_getpeername not ported)
    Sysent::new(3, size_of::<SysGetsocknameArgs>(), SY_NOLOCK, sys_nosys), // 32 = getsockname (sys_getsockname not ported)
    Sysent::new(2, size_of::<SysAccessArgs>(), 0, sys_access),             // 33 = access
    Sysent::new(2, size_of::<SysChflagsArgs>(), 0, sys_chflags),           // 34 = chflags
    Sysent::new(2, size_of::<SysFchflagsArgs>(), 0, sys_fchflags),         // 35 = fchflags
    Sysent::new(0, 0, 0, sys_sync),                                        // 36 = sync
    Sysent::new(0, 0, 0, sys_nosys),                                       // 37 = obsolete msyscall
    Sysent::new(2, size_of::<SysStatArgs>(), SY_NOLOCK, sys_stat),         // 38 = stat
    Sysent::new(0, 0, SY_NOLOCK, sys_getppid),                             // 39 = getppid
    Sysent::new(2, size_of::<SysLstatArgs>(), SY_NOLOCK, sys_lstat),       // 40 = lstat
    Sysent::new(1, size_of::<SysDupArgs>(), SY_NOLOCK, sys_dup),           // 41 = dup
    Sysent::new(4, size_of::<SysFstatatArgs>(), SY_NOLOCK, sys_fstatat),   // 42 = fstatat
    Sysent::new(0, 0, SY_NOLOCK, sys_getegid),                             // 43 = getegid
    Sysent::new(0, 0, 0, sys_nosys), // 44 = unimplemented oprofil
    Sysent::new(0, 0, 0, sys_nosys), // 45 = unimplemented ktrace
    Sysent::new(3, size_of::<SysSigactionArgs>(), 0, sys_sigaction), // 46 = sigaction
    Sysent::new(0, 0, SY_NOLOCK, sys_getgid), // 47 = getgid
    Sysent::new(
        2,
        size_of::<SysSigprocmaskArgs>(),
        SY_NOLOCK,
        sys_sigprocmask,
    ), // 48 = sigprocmask
    Sysent::new(6, size_of::<SysMmapArgs>(), SY_NOLOCK, sys_mmap), // 49 = mmap
    Sysent::new(1, size_of::<SysSetloginArgs>(), 0, sys_setlogin), // 50 = setlogin
    Sysent::new(0, 0, 0, sys_nosys), // 51 = unimplemented acct
    Sysent::new(0, 0, 0, sys_sigpending), // 52 = sigpending
    Sysent::new(2, size_of::<SysFstatArgs>(), SY_NOLOCK, sys_fstat), // 53 = fstat
    Sysent::new(3, size_of::<SysIoctlArgs>(), SY_NOLOCK, sys_ioctl), // 54 = ioctl
    Sysent::new(1, size_of::<SysRebootArgs>(), 0, sys_nosys), // 55 = reboot (sys_reboot not ported)
    Sysent::new(1, size_of::<SysRevokeArgs>(), 0, sys_revoke), // 56 = revoke
    Sysent::new(2, size_of::<SysSymlinkArgs>(), 0, sys_symlink), // 57 = symlink
    Sysent::new(3, size_of::<SysReadlinkArgs>(), 0, sys_readlink), // 58 = readlink
    Sysent::new(3, size_of::<SysExecveArgs>(), 0, sys_execve), // 59 = execve
    Sysent::new(1, size_of::<SysUmaskArgs>(), SY_NOLOCK, sys_umask), // 60 = umask
    Sysent::new(1, size_of::<SysChrootArgs>(), 0, sys_chroot), // 61 = chroot
    Sysent::new(3, size_of::<SysGetfsstatArgs>(), 0, sys_getfsstat), // 62 = getfsstat
    Sysent::new(2, size_of::<SysStatfsArgs>(), 0, sys_statfs), // 63 = statfs
    Sysent::new(2, size_of::<SysFstatfsArgs>(), 0, sys_fstatfs), // 64 = fstatfs
    Sysent::new(2, size_of::<SysFhstatfsArgs>(), 0, sys_fhstatfs), // 65 = fhstatfs
    Sysent::new(0, 0, 0, sys_nosys), // 66 = vfork (sys_vfork not ported)
    Sysent::new(2, size_of::<SysGettimeofdayArgs>(), SY_NOLOCK, sys_nosys), // 67 = gettimeofday (sys_gettimeofday not ported)
    Sysent::new(2, size_of::<SysSettimeofdayArgs>(), SY_NOLOCK, sys_nosys), // 68 = settimeofday (sys_settimeofday not ported)
    Sysent::new(3, size_of::<SysSetitimerArgs>(), SY_NOLOCK, sys_nosys), // 69 = setitimer (sys_setitimer not ported)
    Sysent::new(2, size_of::<SysGetitimerArgs>(), SY_NOLOCK, sys_nosys), // 70 = getitimer (sys_getitimer not ported)
    Sysent::new(5, size_of::<SysSelectArgs>(), SY_NOLOCK, sys_nosys), // 71 = select (sys_select not ported)
    Sysent::new(6, size_of::<SysKeventArgs>(), SY_NOLOCK, sys_nosys), // 72 = kevent (sys_kevent not ported)
    Sysent::new(2, size_of::<SysMunmapArgs>(), SY_NOLOCK, sys_munmap), // 73 = munmap
    Sysent::new(3, size_of::<SysMprotectArgs>(), SY_NOLOCK, sys_mprotect), // 74 = mprotect
    Sysent::new(3, size_of::<SysMadviseArgs>(), 0, sys_madvise),      // 75 = madvise
    Sysent::new(2, size_of::<SysUtimesArgs>(), 0, sys_utimes),        // 76 = utimes
    Sysent::new(2, size_of::<SysFutimesArgs>(), 0, sys_futimes),      // 77 = futimes
    Sysent::new(6, size_of::<SysMqueryArgs>(), 0, sys_mquery),        // 78 = mquery
    Sysent::new(2, size_of::<SysGetgroupsArgs>(), SY_NOLOCK, sys_getgroups), // 79 = getgroups
    Sysent::new(2, size_of::<SysSetgroupsArgs>(), 0, sys_setgroups),  // 80 = setgroups
    Sysent::new(0, 0, 0, sys_getpgrp),                                // 81 = getpgrp
    Sysent::new(2, size_of::<SysSetpgidArgs>(), 0, sys_setpgid),      // 82 = setpgid
    Sysent::new(5, size_of::<SysFutexArgs>(), SY_NOLOCK, sys_nosys), // 83 = futex (sys_futex not ported)
    Sysent::new(4, size_of::<SysUtimensatArgs>(), 0, sys_utimensat), // 84 = utimensat
    Sysent::new(2, size_of::<SysFutimensArgs>(), 0, sys_futimens),   // 85 = futimens
    Sysent::new(3, size_of::<SysKbindArgs>(), SY_NOLOCK, sys_kbind), // 86 = kbind
    Sysent::new(2, size_of::<SysClockGettimeArgs>(), SY_NOLOCK, sys_nosys), // 87 = clock_gettime (sys_clock_gettime not ported)
    Sysent::new(2, size_of::<SysClockSettimeArgs>(), SY_NOLOCK, sys_nosys), // 88 = clock_settime (sys_clock_settime not ported)
    Sysent::new(2, size_of::<SysClockGetresArgs>(), SY_NOLOCK, sys_nosys), // 89 = clock_getres (sys_clock_getres not ported)
    Sysent::new(2, size_of::<SysDup2Args>(), SY_NOLOCK, sys_dup2),         // 90 = dup2
    Sysent::new(2, size_of::<SysNanosleepArgs>(), SY_NOLOCK, sys_nosys), // 91 = nanosleep (sys_nanosleep not ported)
    Sysent::new(3, size_of::<SysFcntlArgs>(), SY_NOLOCK, sys_fcntl),     // 92 = fcntl
    Sysent::new(4, size_of::<SysAccept4Args>(), SY_NOLOCK, sys_nosys), // 93 = accept4 (sys_accept4 not ported)
    Sysent::new(5, size_of::<SysThrsleepArgs>(), SY_NOLOCK, sys_nosys), // 94 = __thrsleep (sys___thrsleep not ported)
    Sysent::new(1, size_of::<SysFsyncArgs>(), 0, sys_fsync),            // 95 = fsync
    Sysent::new(3, size_of::<SysSetpriorityArgs>(), 0, sys_setpriority), // 96 = setpriority
    Sysent::new(3, size_of::<SysSocketArgs>(), SY_NOLOCK, sys_nosys), // 97 = socket (sys_socket not ported)
    Sysent::new(3, size_of::<SysConnectArgs>(), SY_NOLOCK, sys_nosys), // 98 = connect (sys_connect not ported)
    Sysent::new(3, size_of::<SysGetdentsArgs>(), 0, sys_getdents),     // 99 = getdents
    Sysent::new(2, size_of::<SysGetpriorityArgs>(), 0, sys_getpriority), // 100 = getpriority
    Sysent::new(2, size_of::<SysPipe2Args>(), SY_NOLOCK, sys_pipe2),   // 101 = pipe2
    Sysent::new(3, size_of::<SysDup3Args>(), SY_NOLOCK, sys_dup3),     // 102 = dup3
    Sysent::new(1, size_of::<SysSigreturnArgs>(), 0, sys_sigreturn),   // 103 = sigreturn
    Sysent::new(3, size_of::<SysBindArgs>(), SY_NOLOCK, sys_nosys), // 104 = bind (sys_bind not ported)
    Sysent::new(5, size_of::<SysSetsockoptArgs>(), SY_NOLOCK, sys_nosys), // 105 = setsockopt (sys_setsockopt not ported)
    Sysent::new(2, size_of::<SysListenArgs>(), SY_NOLOCK, sys_nosys), // 106 = listen (sys_listen not ported)
    Sysent::new(4, size_of::<SysChflagsatArgs>(), 0, sys_chflagsat),  // 107 = chflagsat
    Sysent::new(2, size_of::<SysPledgeArgs>(), SY_NOLOCK, sys_nosys), // 108 = pledge (sys_pledge not ported)
    Sysent::new(4, size_of::<SysPpollArgs>(), SY_NOLOCK, sys_nosys), // 109 = ppoll (sys_ppoll not ported)
    Sysent::new(6, size_of::<SysPselectArgs>(), SY_NOLOCK, sys_nosys), // 110 = pselect (sys_pselect not ported)
    Sysent::new(1, size_of::<SysSigsuspendArgs>(), SY_NOLOCK, sys_sigsuspend), // 111 = sigsuspend
    Sysent::new(3, size_of::<SysSendsyslogArgs>(), SY_NOLOCK, sys_nosys), // 112 = sendsyslog (sys_sendsyslog not ported)
    Sysent::new(0, 0, 0, sys_nosys), // 113 = unimplemented fktrace
    Sysent::new(2, size_of::<SysUnveilArgs>(), 0, sys_unveil), // 114 = unveil
    Sysent::new(2, size_of::<SysRealpathArgs>(), SY_NOLOCK, sys___realpath), // 115 = __realpath
    Sysent::new(5, size_of::<SysRecvmmsgArgs>(), SY_NOLOCK, sys_nosys), // 116 = recvmmsg (sys_recvmmsg not ported)
    Sysent::new(4, size_of::<SysSendmmsgArgs>(), SY_NOLOCK, sys_nosys), // 117 = sendmmsg (sys_sendmmsg not ported)
    Sysent::new(5, size_of::<SysGetsockoptArgs>(), SY_NOLOCK, sys_nosys), // 118 = getsockopt (sys_getsockopt not ported)
    Sysent::new(3, size_of::<SysThrkillArgs>(), 0, sys_thrkill),          // 119 = thrkill
    Sysent::new(3, size_of::<SysReadvArgs>(), SY_NOLOCK, sys_readv),      // 120 = readv
    Sysent::new(3, size_of::<SysWritevArgs>(), SY_NOLOCK, sys_writev),    // 121 = writev
    Sysent::new(2, size_of::<SysKillArgs>(), 0, sys_kill),                // 122 = kill
    Sysent::new(3, size_of::<SysFchownArgs>(), 0, sys_fchown),            // 123 = fchown
    Sysent::new(2, size_of::<SysFchmodArgs>(), 0, sys_fchmod),            // 124 = fchmod
    Sysent::new(
        3,
        size_of::<SysPledgeOpenArgs>(),
        SY_NOLOCK,
        sys___pledge_open,
    ), // 125 = __pledge_open
    Sysent::new(2, size_of::<SysSetreuidArgs>(), 0, sys_setreuid),        // 126 = setreuid
    Sysent::new(2, size_of::<SysSetregidArgs>(), 0, sys_setregid),        // 127 = setregid
    Sysent::new(2, size_of::<SysRenameArgs>(), 0, sys_rename),            // 128 = rename
    Sysent::new(0, 0, 0, sys_nosys), // 129 = obsolete otruncate
    Sysent::new(0, 0, 0, sys_nosys), // 130 = obsolete oftruncate
    Sysent::new(2, size_of::<SysFlockArgs>(), SY_NOLOCK, sys_flock), // 131 = flock
    Sysent::new(2, size_of::<SysMkfifoArgs>(), 0, sys_mkfifo), // 132 = mkfifo
    Sysent::new(6, size_of::<SysSendtoArgs>(), SY_NOLOCK, sys_nosys), // 133 = sendto (sys_sendto not ported)
    Sysent::new(2, size_of::<SysShutdownArgs>(), SY_NOLOCK, sys_nosys), // 134 = shutdown (sys_shutdown not ported)
    Sysent::new(4, size_of::<SysSocketpairArgs>(), SY_NOLOCK, sys_nosys), // 135 = socketpair (sys_socketpair not ported)
    Sysent::new(2, size_of::<SysMkdirArgs>(), 0, sys_mkdir),              // 136 = mkdir
    Sysent::new(1, size_of::<SysRmdirArgs>(), 0, sys_rmdir),              // 137 = rmdir
    Sysent::new(0, 0, 0, sys_nosys), // 138 = obsolete t32_utimes
    Sysent::new(0, 0, 0, sys_nosys), // 139 = obsolete 4.2 sigreturn
    Sysent::new(2, size_of::<SysAdjtimeArgs>(), SY_NOLOCK, sys_nosys), // 140 = adjtime (sys_adjtime not ported)
    Sysent::new(2, size_of::<SysGetloginRArgs>(), 0, sys_getlogin_r),  // 141 = getlogin_r
    Sysent::new(3, size_of::<SysGetthrnameArgs>(), 0, sys_getthrname), // 142 = getthrname
    Sysent::new(2, size_of::<SysSetthrnameArgs>(), 0, sys_setthrname), // 143 = setthrname
    Sysent::new(0, 0, 0, sys_nosys),                                   // 144 = obsolete ogetrlimit
    Sysent::new(0, 0, 0, sys_nosys),                                   // 145 = obsolete osetrlimit
    Sysent::new(0, 0, 0, sys_nosys),                                   // 146 = obsolete pinsyscall
    Sysent::new(0, 0, 0, sys_setsid),                                  // 147 = setsid
    Sysent::new(4, size_of::<SysQuotactlArgs>(), 0, sys_quotactl),     // 148 = quotactl
    Sysent::new(0, 0, 0, sys_nosys),                                   // 149 = obsolete oquota
    Sysent::new(1, size_of::<SysYpconnectArgs>(), SY_NOLOCK, sys_nosys), // 150 = ypconnect (sys_ypconnect not ported)
    Sysent::new(0, 0, 0, sys_nosys),                                     // 151 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                     // 152 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                     // 153 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                     // 154 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                     // 155 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 156 = obsolete ogetdirentries
    Sysent::new(0, 0, 0, sys_nosys), // 157 = obsolete statfs25
    Sysent::new(4, size_of::<SysPinsyscallsArgs>(), 0, sys_pinsyscalls), // 158 = pinsyscalls
    Sysent::new(2, size_of::<SysMimmutableArgs>(), 0, sys_mimmutable), // 159 = mimmutable
    Sysent::new(4, size_of::<SysWaitidArgs>(), 0, sys_nosys), // 160 = waitid (sys_waitid not ported)
    Sysent::new(2, size_of::<SysGetfhArgs>(), 0, sys_getfh),  // 161 = getfh
    Sysent::new(0, 0, 0, sys_nosys),                          // 162 = obsolete ogetdomainname
    Sysent::new(0, 0, 0, sys_nosys),                          // 163 = obsolete osetdomainname
    Sysent::new(0, 0, 0, sys_nosys),                          // 164 = obsolete __tmpfd
    Sysent::new(2, size_of::<SysSysarchArgs>(), 0, sys_nosys), // 165 = sysarch (sys_sysarch not ported)
    Sysent::new(3, size_of::<SysLseekArgs>(), SY_NOLOCK, sys_lseek), // 166 = lseek
    Sysent::new(2, size_of::<SysTruncateArgs>(), 0, sys_truncate), // 167 = truncate
    Sysent::new(2, size_of::<SysFtruncateArgs>(), 0, sys_ftruncate), // 168 = ftruncate
    Sysent::new(4, size_of::<SysPreadArgs>(), SY_NOLOCK, sys_pread), // 169 = pread
    Sysent::new(4, size_of::<SysPwriteArgs>(), SY_NOLOCK, sys_pwrite), // 170 = pwrite
    Sysent::new(4, size_of::<SysPreadvArgs>(), SY_NOLOCK, sys_preadv), // 171 = preadv
    Sysent::new(4, size_of::<SysPwritevArgs>(), SY_NOLOCK, sys_pwritev), // 172 = pwritev
    Sysent::new(0, 0, 0, sys_nosys),                           // 173 = obsolete pad_pread
    Sysent::new(0, 0, 0, sys_nosys),                           // 174 = obsolete pad_pwrite
    Sysent::new(6, size_of::<SysProfilArgs>(), 0, sys_nosys), // 175 = profil (sys_profil not ported)
    Sysent::new(0, 0, 0, sys_nosys),                          // 176 = unimplemented ntp_adjtime
    Sysent::new(0, 0, 0, sys_nosys),                          // 177 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                          // 178 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                          // 179 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                          // 180 = unimplemented
    Sysent::new(1, size_of::<SysSetgidArgs>(), 0, sys_setgid), // 181 = setgid
    Sysent::new(1, size_of::<SysSetegidArgs>(), 0, sys_setegid), // 182 = setegid
    Sysent::new(1, size_of::<SysSeteuidArgs>(), 0, sys_seteuid), // 183 = seteuid
    Sysent::new(0, 0, 0, sys_nosys),                          // 184 = obsolete lfs_bmapv
    Sysent::new(0, 0, 0, sys_nosys),                          // 185 = obsolete lfs_markv
    Sysent::new(0, 0, 0, sys_nosys),                          // 186 = obsolete lfs_segclean
    Sysent::new(0, 0, 0, sys_nosys),                          // 187 = obsolete lfs_segwait
    Sysent::new(0, 0, 0, sys_nosys),                          // 188 = obsolete stat35
    Sysent::new(0, 0, 0, sys_nosys),                          // 189 = obsolete fstat35
    Sysent::new(4, size_of::<SysPathconfatArgs>(), 0, sys_pathconfat), // 190 = pathconfat
    Sysent::new(2, size_of::<SysPathconfArgs>(), 0, sys_pathconf), // 191 = pathconf
    Sysent::new(2, size_of::<SysFpathconfArgs>(), 0, sys_fpathconf), // 192 = fpathconf
    Sysent::new(3, size_of::<SysSwapctlArgs>(), 0, sys_nosys), // 193 = swapctl (sys_swapctl not ported)
    Sysent::new(2, size_of::<SysGetrlimitArgs>(), SY_NOLOCK, sys_getrlimit), // 194 = getrlimit
    Sysent::new(2, size_of::<SysSetrlimitArgs>(), SY_NOLOCK, sys_setrlimit), // 195 = setrlimit
    Sysent::new(0, 0, 0, sys_nosys),                           // 196 = obsolete ogetdirentries48
    Sysent::new(0, 0, 0, sys_nosys),                           // 197 = obsolete pad_mmap
    Sysent::new(0, 0, 0, sys_nosys),                           // 198 = obsolete __syscall
    Sysent::new(0, 0, 0, sys_nosys),                           // 199 = obsolete pad_lseek
    Sysent::new(0, 0, 0, sys_nosys),                           // 200 = obsolete pad_truncate
    Sysent::new(0, 0, 0, sys_nosys),                           // 201 = obsolete pad_ftruncate
    Sysent::new(6, size_of::<SysSysctlArgs>(), SY_NOLOCK, sys_sysctl), // 202 = sysctl
    Sysent::new(2, size_of::<SysMlockArgs>(), 0, sys_mlock),   // 203 = mlock
    Sysent::new(2, size_of::<SysMunlockArgs>(), 0, sys_munlock), // 204 = munlock
    Sysent::new(0, 0, 0, sys_nosys),                           // 205 = unimplemented sys_undelete
    Sysent::new(0, 0, 0, sys_nosys),                           // 206 = obsolete t32_futimes
    Sysent::new(1, size_of::<SysGetpgidArgs>(), 0, sys_getpgid), // 207 = getpgid
    Sysent::new(0, 0, 0, sys_nosys),                           // 208 = obsolete nnpfspioctl
    Sysent::new(3, size_of::<SysUtraceArgs>(), SY_NOLOCK, sys_nosys), // 209 = utrace (sys_utrace not ported)
    Sysent::new(0, 0, 0, sys_nosys),                                  // 210 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 211 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 212 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 213 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 214 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 215 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 216 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 217 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 218 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 219 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 220 = unimplemented semctl
    Sysent::new(0, 0, 0, sys_nosys),                                  // 221 = unimplemented semget
    Sysent::new(0, 0, 0, sys_nosys),                                  // 222 = obsolete semop35
    Sysent::new(0, 0, 0, sys_nosys),                                  // 223 = obsolete semconfig35
    Sysent::new(0, 0, 0, sys_nosys),                                  // 224 = unimplemented msgctl
    Sysent::new(0, 0, 0, sys_nosys),                                  // 225 = unimplemented msgget
    Sysent::new(0, 0, 0, sys_nosys),                                  // 226 = unimplemented msgsnd
    Sysent::new(0, 0, 0, sys_nosys),                                  // 227 = unimplemented msgrcv
    Sysent::new(0, 0, 0, sys_nosys),                                  // 228 = unimplemented shmat
    Sysent::new(0, 0, 0, sys_nosys),                                  // 229 = unimplemented shmctl
    Sysent::new(0, 0, 0, sys_nosys),                                  // 230 = unimplemented shmdt
    Sysent::new(0, 0, 0, sys_nosys),                                  // 231 = obsolete shmget35
    Sysent::new(0, 0, 0, sys_nosys), // 232 = obsolete t32_clock_gettime
    Sysent::new(0, 0, 0, sys_nosys), // 233 = obsolete t32_clock_settime
    Sysent::new(0, 0, 0, sys_nosys), // 234 = obsolete t32_clock_getres
    Sysent::new(0, 0, 0, sys_nosys), // 235 = unimplemented timer_create
    Sysent::new(0, 0, 0, sys_nosys), // 236 = unimplemented timer_delete
    Sysent::new(0, 0, 0, sys_nosys), // 237 = unimplemented timer_settime
    Sysent::new(0, 0, 0, sys_nosys), // 238 = unimplemented timer_gettime
    Sysent::new(0, 0, 0, sys_nosys), // 239 = unimplemented timer_getoverrun
    Sysent::new(0, 0, 0, sys_nosys), // 240 = obsolete t32_nanosleep
    Sysent::new(0, 0, 0, sys_nosys), // 241 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 242 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 243 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 244 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 245 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 246 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 247 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 248 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 249 = unimplemented
    Sysent::new(3, size_of::<SysMinheritArgs>(), SY_NOLOCK, sys_minherit), // 250 = minherit
    Sysent::new(0, 0, 0, sys_nosys), // 251 = obsolete rfork
    Sysent::new(3, size_of::<SysPollArgs>(), SY_NOLOCK, sys_nosys), // 252 = poll (sys_poll not ported)
    Sysent::new(0, 0, SY_NOLOCK, sys_issetugid),                    // 253 = issetugid
    Sysent::new(3, size_of::<SysLchownArgs>(), 0, sys_lchown),      // 254 = lchown
    Sysent::new(1, size_of::<SysGetsidArgs>(), 0, sys_getsid),      // 255 = getsid
    Sysent::new(3, size_of::<SysMsyncArgs>(), 0, sys_msync),        // 256 = msync
    Sysent::new(0, 0, 0, sys_nosys),                                // 257 = obsolete semctl35
    Sysent::new(0, 0, 0, sys_nosys),                                // 258 = obsolete shmctl35
    Sysent::new(0, 0, 0, sys_nosys),                                // 259 = obsolete msgctl35
    Sysent::new(0, 0, 0, sys_nosys),                                // 260 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                // 261 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                // 262 = unimplemented
    Sysent::new(1, size_of::<SysPipeArgs>(), SY_NOLOCK, sys_pipe),  // 263 = pipe
    Sysent::new(2, size_of::<SysFhopenArgs>(), 0, sys_fhopen),      // 264 = fhopen
    Sysent::new(0, 0, 0, sys_nosys),                                // 265 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                // 266 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                // 267 = obsolete pad_preadv
    Sysent::new(0, 0, 0, sys_nosys),                                // 268 = obsolete pad_pwritev
    Sysent::new(0, 0, SY_NOLOCK, sys_nosys), // 269 = kqueue (sys_kqueue not ported)
    Sysent::new(1, size_of::<SysKqueue1Args>(), SY_NOLOCK, sys_nosys), // 270 = kqueue1 (sys_kqueue1 not ported)
    Sysent::new(1, size_of::<SysMlockallArgs>(), 0, sys_mlockall),     // 271 = mlockall
    Sysent::new(0, 0, 0, sys_munlockall),                              // 272 = munlockall
    Sysent::new(0, 0, 0, sys_nosys), // 273 = unimplemented sys_getpeereid
    Sysent::new(0, 0, 0, sys_nosys), // 274 = unimplemented sys_extattrctl
    Sysent::new(0, 0, 0, sys_nosys), // 275 = unimplemented sys_extattr_set_file
    Sysent::new(0, 0, 0, sys_nosys), // 276 = unimplemented sys_extattr_get_file
    Sysent::new(0, 0, 0, sys_nosys), // 277 = unimplemented sys_extattr_delete_file
    Sysent::new(0, 0, 0, sys_nosys), // 278 = unimplemented sys_extattr_set_fd
    Sysent::new(0, 0, 0, sys_nosys), // 279 = unimplemented sys_extattr_get_fd
    Sysent::new(0, 0, 0, sys_nosys), // 280 = unimplemented sys_extattr_delete_fd
    Sysent::new(3, size_of::<SysGetresuidArgs>(), SY_NOLOCK, sys_getresuid), // 281 = getresuid
    Sysent::new(3, size_of::<SysSetresuidArgs>(), 0, sys_setresuid), // 282 = setresuid
    Sysent::new(3, size_of::<SysGetresgidArgs>(), SY_NOLOCK, sys_getresgid), // 283 = getresgid
    Sysent::new(3, size_of::<SysSetresgidArgs>(), 0, sys_setresgid), // 284 = setresgid
    Sysent::new(0, 0, 0, sys_nosys), // 285 = obsolete sys_omquery
    Sysent::new(0, 0, 0, sys_nosys), // 286 = obsolete pad_mquery
    Sysent::new(1, size_of::<SysClosefromArgs>(), SY_NOLOCK, sys_closefrom), // 287 = closefrom
    Sysent::new(2, size_of::<SysSigaltstackArgs>(), 0, sys_sigaltstack), // 288 = sigaltstack
    Sysent::new(0, 0, 0, sys_nosys), // 289 = unimplemented shmget
    Sysent::new(0, 0, 0, sys_nosys), // 290 = unimplemented semop
    Sysent::new(0, 0, 0, sys_nosys), // 291 = obsolete t32_stat
    Sysent::new(0, 0, 0, sys_nosys), // 292 = obsolete t32_fstat
    Sysent::new(0, 0, 0, sys_nosys), // 293 = obsolete t32_lstat
    Sysent::new(2, size_of::<SysFhstatArgs>(), 0, sys_fhstat), // 294 = fhstat
    Sysent::new(0, 0, 0, sys_nosys), // 295 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 296 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 297 = unimplemented
    Sysent::new(0, 0, SY_NOLOCK, sys_nosys), // 298 = sched_yield (sys_sched_yield not ported)
    Sysent::new(0, 0, SY_NOLOCK, sys_getthrid), // 299 = getthrid
    Sysent::new(0, 0, 0, sys_nosys), // 300 = obsolete t32___thrsleep
    Sysent::new(2, size_of::<SysThrwakeupArgs>(), SY_NOLOCK, sys_nosys), // 301 = __thrwakeup (sys___thrwakeup not ported)
    Sysent::new(1, size_of::<SysThrexitArgs>(), 0, sys_nosys), // 302 = __threxit (sys___threxit not ported)
    Sysent::new(
        3,
        size_of::<SysThrsigdivertArgs>(),
        SY_NOLOCK,
        sys___thrsigdivert,
    ), // 303 = __thrsigdivert
    Sysent::new(2, size_of::<SysGetcwdArgs>(), 0, sys___getcwd), // 304 = __getcwd
    Sysent::new(2, size_of::<SysAdjfreqArgs>(), SY_NOLOCK, sys_nosys), // 305 = adjfreq (sys_adjfreq not ported)
    Sysent::new(0, 0, 0, sys_nosys),                                   // 306 = obsolete getfsstat53
    Sysent::new(0, 0, 0, sys_nosys),                                   // 307 = obsolete statfs53
    Sysent::new(0, 0, 0, sys_nosys),                                   // 308 = obsolete fstatfs53
    Sysent::new(0, 0, 0, sys_nosys),                                   // 309 = obsolete fhstatfs53
    Sysent::new(1, size_of::<SysSetrtableArgs>(), SY_NOLOCK, sys_nosys), // 310 = setrtable (sys_setrtable not ported)
    Sysent::new(0, 0, SY_NOLOCK, sys_nosys), // 311 = getrtable (sys_getrtable not ported)
    Sysent::new(0, 0, 0, sys_nosys),         // 312 = obsolete t32_getdirentries
    Sysent::new(4, size_of::<SysFaccessatArgs>(), 0, sys_faccessat), // 313 = faccessat
    Sysent::new(4, size_of::<SysFchmodatArgs>(), 0, sys_fchmodat), // 314 = fchmodat
    Sysent::new(5, size_of::<SysFchownatArgs>(), 0, sys_fchownat), // 315 = fchownat
    Sysent::new(0, 0, 0, sys_nosys),         // 316 = obsolete t32_fstatat
    Sysent::new(5, size_of::<SysLinkatArgs>(), 0, sys_linkat), // 317 = linkat
    Sysent::new(3, size_of::<SysMkdiratArgs>(), 0, sys_mkdirat), // 318 = mkdirat
    Sysent::new(3, size_of::<SysMkfifoatArgs>(), 0, sys_mkfifoat), // 319 = mkfifoat
    Sysent::new(4, size_of::<SysMknodatArgs>(), 0, sys_mknodat), // 320 = mknodat
    Sysent::new(4, size_of::<SysOpenatArgs>(), SY_NOLOCK, sys_openat), // 321 = openat
    Sysent::new(4, size_of::<SysReadlinkatArgs>(), 0, sys_readlinkat), // 322 = readlinkat
    Sysent::new(4, size_of::<SysRenameatArgs>(), 0, sys_renameat), // 323 = renameat
    Sysent::new(3, size_of::<SysSymlinkatArgs>(), 0, sys_symlinkat), // 324 = symlinkat
    Sysent::new(3, size_of::<SysUnlinkatArgs>(), 0, sys_unlinkat), // 325 = unlinkat
    Sysent::new(0, 0, 0, sys_nosys),         // 326 = obsolete t32_utimensat
    Sysent::new(0, 0, 0, sys_nosys),         // 327 = obsolete t32_futimens
    Sysent::new(0, 0, 0, sys_nosys),         // 328 = obsolete __tfork51
    Sysent::new(1, size_of::<SysSetTcbArgs>(), SY_NOLOCK, sys___set_tcb), // 329 = __set_tcb
    Sysent::new(0, 0, SY_NOLOCK, sys___get_tcb), // 330 = __get_tcb
];
