/*	$OpenBSD: init_sysent.c,v 1.291 2026/08/12 15:05:21 naddy Exp $	*/

//! System call switch table.
//!
//! DO NOT EDIT: this file is automatically generated by `cargo xtask gen-syscalls`
//! (`tools/xtask/src/syscalls.rs`, what `kern/makesyscalls.sh` does for the C tree)
//! from `sys/kern/syscalls.master`.
//! created from; OpenBSD: syscalls.master,v 1.273 2026/08/12 15:04:45 naddy Exp
//!
//! Upstream: sys/kern/init_sysent.c @ 3ce1f3f79392
//!
//! ## Deviations
//! - An entry points at its `sys_*` function only when `sys/kern` or `sys/uvm` defines
//!   it (`pub fn sys_<name>(`); the others are `sys_nosys` with a note, so the table
//!   always compiles. Rerun the generator after porting a syscall.

use crate::kern::kern_exit::sys_exit;
use crate::kern::kern_sig::sys_nosys;
use crate::kern::sys_generic::sys_write;
use crate::sys::syscall::SYS_MAXSYSCALL;
use crate::sys::syscallargs::{
    SysAccept4Args, SysAcceptArgs, SysAccessArgs, SysAdjfreqArgs, SysAdjtimeArgs, SysBindArgs,
    SysChdirArgs, SysChflagsArgs, SysChflagsatArgs, SysChmodArgs, SysChownArgs, SysChrootArgs,
    SysClockGetresArgs, SysClockGettimeArgs, SysClockSettimeArgs, SysCloseArgs, SysClosefromArgs,
    SysConnectArgs, SysDup2Args, SysDup3Args, SysDupArgs, SysExecveArgs, SysExitArgs,
    SysFaccessatArgs, SysFchdirArgs, SysFchflagsArgs, SysFchmodArgs, SysFchmodatArgs,
    SysFchownArgs, SysFchownatArgs, SysFcntlArgs, SysFhopenArgs, SysFhstatArgs, SysFhstatfsArgs,
    SysFlockArgs, SysFpathconfArgs, SysFstatArgs, SysFstatatArgs, SysFstatfsArgs, SysFsyncArgs,
    SysFtruncateArgs, SysFutexArgs, SysFutimensArgs, SysFutimesArgs, SysGetcwdArgs,
    SysGetdentsArgs, SysGetentropyArgs, SysGetfhArgs, SysGetfsstatArgs, SysGetgroupsArgs,
    SysGetitimerArgs, SysGetloginRArgs, SysGetpeernameArgs, SysGetpgidArgs, SysGetpriorityArgs,
    SysGetresgidArgs, SysGetresuidArgs, SysGetrlimitArgs, SysGetrusageArgs, SysGetsidArgs,
    SysGetsocknameArgs, SysGetsockoptArgs, SysGetthrnameArgs, SysGettimeofdayArgs, SysIoctlArgs,
    SysKbindArgs, SysKeventArgs, SysKillArgs, SysKqueue1Args, SysLchownArgs, SysLinkArgs,
    SysLinkatArgs, SysListenArgs, SysLseekArgs, SysLstatArgs, SysMadviseArgs, SysMimmutableArgs,
    SysMinheritArgs, SysMkdirArgs, SysMkdiratArgs, SysMkfifoArgs, SysMkfifoatArgs, SysMknodArgs,
    SysMknodatArgs, SysMlockArgs, SysMlockallArgs, SysMmapArgs, SysMountArgs, SysMprotectArgs,
    SysMqueryArgs, SysMsyncArgs, SysMunlockArgs, SysMunmapArgs, SysNanosleepArgs, SysObreakArgs,
    SysOpenArgs, SysOpenatArgs, SysPathconfArgs, SysPathconfatArgs, SysPinsyscallsArgs,
    SysPipe2Args, SysPipeArgs, SysPledgeArgs, SysPledgeOpenArgs, SysPollArgs, SysPpollArgs,
    SysPreadArgs, SysPreadvArgs, SysProfilArgs, SysPselectArgs, SysPwriteArgs, SysPwritevArgs,
    SysQuotactlArgs, SysReadArgs, SysReadlinkArgs, SysReadlinkatArgs, SysReadvArgs,
    SysRealpathArgs, SysRebootArgs, SysRecvfromArgs, SysRecvmmsgArgs, SysRecvmsgArgs,
    SysRenameArgs, SysRenameatArgs, SysRevokeArgs, SysRmdirArgs, SysSelectArgs, SysSendmmsgArgs,
    SysSendmsgArgs, SysSendsyslogArgs, SysSendtoArgs, SysSetTcbArgs, SysSetegidArgs,
    SysSeteuidArgs, SysSetgidArgs, SysSetgroupsArgs, SysSetitimerArgs, SysSetloginArgs,
    SysSetpgidArgs, SysSetpriorityArgs, SysSetregidArgs, SysSetresgidArgs, SysSetresuidArgs,
    SysSetreuidArgs, SysSetrlimitArgs, SysSetrtableArgs, SysSetsockoptArgs, SysSetthrnameArgs,
    SysSettimeofdayArgs, SysSetuidArgs, SysShutdownArgs, SysSigactionArgs, SysSigaltstackArgs,
    SysSigprocmaskArgs, SysSigreturnArgs, SysSigsuspendArgs, SysSocketArgs, SysSocketpairArgs,
    SysStatArgs, SysStatfsArgs, SysSwapctlArgs, SysSymlinkArgs, SysSymlinkatArgs, SysSysarchArgs,
    SysSysctlArgs, SysTforkArgs, SysThrexitArgs, SysThrkillArgs, SysThrsigdivertArgs,
    SysThrsleepArgs, SysThrwakeupArgs, SysTruncateArgs, SysUmaskArgs, SysUnlinkArgs,
    SysUnlinkatArgs, SysUnmountArgs, SysUnveilArgs, SysUtimensatArgs, SysUtimesArgs, SysUtraceArgs,
    SysWait4Args, SysWaitidArgs, SysWriteArgs, SysWritevArgs, SysYpconnectArgs,
};
use crate::sys::systm::{SY_NOLOCK, Sysent};

/// `sysent[]`: the system call switch table, indexed by `SYS_*`.
pub static SYSENT: [Sysent; SYS_MAXSYSCALL] = [
    Sysent::new(0, 0, 0, sys_nosys), // 0 = unimplemented syscall
    Sysent::new(1, size_of::<SysExitArgs>(), 0, sys_exit), // 1 = exit
    Sysent::new(0, 0, 0, sys_nosys), // 2 = fork (sys_fork not ported)
    Sysent::new(3, size_of::<SysReadArgs>(), SY_NOLOCK, sys_nosys), // 3 = read (sys_read not ported)
    Sysent::new(3, size_of::<SysWriteArgs>(), SY_NOLOCK, sys_write), // 4 = write
    Sysent::new(3, size_of::<SysOpenArgs>(), SY_NOLOCK, sys_nosys), // 5 = open (sys_open not ported)
    Sysent::new(1, size_of::<SysCloseArgs>(), SY_NOLOCK, sys_nosys), // 6 = close (sys_close not ported)
    Sysent::new(2, size_of::<SysGetentropyArgs>(), SY_NOLOCK, sys_nosys), // 7 = getentropy (sys_getentropy not ported)
    Sysent::new(2, size_of::<SysTforkArgs>(), 0, sys_nosys), // 8 = __tfork (sys___tfork not ported)
    Sysent::new(2, size_of::<SysLinkArgs>(), 0, sys_nosys),  // 9 = link (sys_link not ported)
    Sysent::new(1, size_of::<SysUnlinkArgs>(), 0, sys_nosys), // 10 = unlink (sys_unlink not ported)
    Sysent::new(4, size_of::<SysWait4Args>(), 0, sys_nosys), // 11 = wait4 (sys_wait4 not ported)
    Sysent::new(1, size_of::<SysChdirArgs>(), 0, sys_nosys), // 12 = chdir (sys_chdir not ported)
    Sysent::new(1, size_of::<SysFchdirArgs>(), 0, sys_nosys), // 13 = fchdir (sys_fchdir not ported)
    Sysent::new(3, size_of::<SysMknodArgs>(), 0, sys_nosys), // 14 = mknod (sys_mknod not ported)
    Sysent::new(2, size_of::<SysChmodArgs>(), 0, sys_nosys), // 15 = chmod (sys_chmod not ported)
    Sysent::new(3, size_of::<SysChownArgs>(), 0, sys_nosys), // 16 = chown (sys_chown not ported)
    Sysent::new(1, size_of::<SysObreakArgs>(), 0, sys_nosys), // 17 = break (sys_obreak not ported)
    Sysent::new(0, 0, SY_NOLOCK, sys_nosys), // 18 = getdtablecount (sys_getdtablecount not ported)
    Sysent::new(2, size_of::<SysGetrusageArgs>(), 0, sys_nosys), // 19 = getrusage (sys_getrusage not ported)
    Sysent::new(0, 0, SY_NOLOCK, sys_nosys), // 20 = getpid (sys_getpid not ported)
    Sysent::new(4, size_of::<SysMountArgs>(), 0, sys_nosys), // 21 = mount (sys_mount not ported)
    Sysent::new(2, size_of::<SysUnmountArgs>(), 0, sys_nosys), // 22 = unmount (sys_unmount not ported)
    Sysent::new(1, size_of::<SysSetuidArgs>(), 0, sys_nosys), // 23 = setuid (sys_setuid not ported)
    Sysent::new(0, 0, SY_NOLOCK, sys_nosys),                  // 24 = getuid (sys_getuid not ported)
    Sysent::new(0, 0, SY_NOLOCK, sys_nosys), // 25 = geteuid (sys_geteuid not ported)
    Sysent::new(0, 0, 0, sys_nosys),         // 26 = unimplemented ptrace
    Sysent::new(3, size_of::<SysRecvmsgArgs>(), SY_NOLOCK, sys_nosys), // 27 = recvmsg (sys_recvmsg not ported)
    Sysent::new(3, size_of::<SysSendmsgArgs>(), SY_NOLOCK, sys_nosys), // 28 = sendmsg (sys_sendmsg not ported)
    Sysent::new(6, size_of::<SysRecvfromArgs>(), SY_NOLOCK, sys_nosys), // 29 = recvfrom (sys_recvfrom not ported)
    Sysent::new(3, size_of::<SysAcceptArgs>(), SY_NOLOCK, sys_nosys), // 30 = accept (sys_accept not ported)
    Sysent::new(3, size_of::<SysGetpeernameArgs>(), SY_NOLOCK, sys_nosys), // 31 = getpeername (sys_getpeername not ported)
    Sysent::new(3, size_of::<SysGetsocknameArgs>(), SY_NOLOCK, sys_nosys), // 32 = getsockname (sys_getsockname not ported)
    Sysent::new(2, size_of::<SysAccessArgs>(), 0, sys_nosys), // 33 = access (sys_access not ported)
    Sysent::new(2, size_of::<SysChflagsArgs>(), 0, sys_nosys), // 34 = chflags (sys_chflags not ported)
    Sysent::new(2, size_of::<SysFchflagsArgs>(), 0, sys_nosys), // 35 = fchflags (sys_fchflags not ported)
    Sysent::new(0, 0, 0, sys_nosys),                            // 36 = sync (sys_sync not ported)
    Sysent::new(0, 0, 0, sys_nosys),                            // 37 = obsolete msyscall
    Sysent::new(2, size_of::<SysStatArgs>(), SY_NOLOCK, sys_nosys), // 38 = stat (sys_stat not ported)
    Sysent::new(0, 0, SY_NOLOCK, sys_nosys), // 39 = getppid (sys_getppid not ported)
    Sysent::new(2, size_of::<SysLstatArgs>(), SY_NOLOCK, sys_nosys), // 40 = lstat (sys_lstat not ported)
    Sysent::new(1, size_of::<SysDupArgs>(), SY_NOLOCK, sys_nosys), // 41 = dup (sys_dup not ported)
    Sysent::new(4, size_of::<SysFstatatArgs>(), SY_NOLOCK, sys_nosys), // 42 = fstatat (sys_fstatat not ported)
    Sysent::new(0, 0, SY_NOLOCK, sys_nosys), // 43 = getegid (sys_getegid not ported)
    Sysent::new(0, 0, 0, sys_nosys),         // 44 = unimplemented oprofil
    Sysent::new(0, 0, 0, sys_nosys),         // 45 = unimplemented ktrace
    Sysent::new(3, size_of::<SysSigactionArgs>(), 0, sys_nosys), // 46 = sigaction (sys_sigaction not ported)
    Sysent::new(0, 0, SY_NOLOCK, sys_nosys), // 47 = getgid (sys_getgid not ported)
    Sysent::new(2, size_of::<SysSigprocmaskArgs>(), SY_NOLOCK, sys_nosys), // 48 = sigprocmask (sys_sigprocmask not ported)
    Sysent::new(6, size_of::<SysMmapArgs>(), SY_NOLOCK, sys_nosys), // 49 = mmap (sys_mmap not ported)
    Sysent::new(1, size_of::<SysSetloginArgs>(), 0, sys_nosys), // 50 = setlogin (sys_setlogin not ported)
    Sysent::new(0, 0, 0, sys_nosys),                            // 51 = unimplemented acct
    Sysent::new(0, 0, 0, sys_nosys), // 52 = sigpending (sys_sigpending not ported)
    Sysent::new(2, size_of::<SysFstatArgs>(), SY_NOLOCK, sys_nosys), // 53 = fstat (sys_fstat not ported)
    Sysent::new(3, size_of::<SysIoctlArgs>(), SY_NOLOCK, sys_nosys), // 54 = ioctl (sys_ioctl not ported)
    Sysent::new(1, size_of::<SysRebootArgs>(), 0, sys_nosys), // 55 = reboot (sys_reboot not ported)
    Sysent::new(1, size_of::<SysRevokeArgs>(), 0, sys_nosys), // 56 = revoke (sys_revoke not ported)
    Sysent::new(2, size_of::<SysSymlinkArgs>(), 0, sys_nosys), // 57 = symlink (sys_symlink not ported)
    Sysent::new(3, size_of::<SysReadlinkArgs>(), 0, sys_nosys), // 58 = readlink (sys_readlink not ported)
    Sysent::new(3, size_of::<SysExecveArgs>(), 0, sys_nosys), // 59 = execve (sys_execve not ported)
    Sysent::new(1, size_of::<SysUmaskArgs>(), SY_NOLOCK, sys_nosys), // 60 = umask (sys_umask not ported)
    Sysent::new(1, size_of::<SysChrootArgs>(), 0, sys_nosys), // 61 = chroot (sys_chroot not ported)
    Sysent::new(3, size_of::<SysGetfsstatArgs>(), 0, sys_nosys), // 62 = getfsstat (sys_getfsstat not ported)
    Sysent::new(2, size_of::<SysStatfsArgs>(), 0, sys_nosys), // 63 = statfs (sys_statfs not ported)
    Sysent::new(2, size_of::<SysFstatfsArgs>(), 0, sys_nosys), // 64 = fstatfs (sys_fstatfs not ported)
    Sysent::new(2, size_of::<SysFhstatfsArgs>(), 0, sys_nosys), // 65 = fhstatfs (sys_fhstatfs not ported)
    Sysent::new(0, 0, 0, sys_nosys),                            // 66 = vfork (sys_vfork not ported)
    Sysent::new(2, size_of::<SysGettimeofdayArgs>(), SY_NOLOCK, sys_nosys), // 67 = gettimeofday (sys_gettimeofday not ported)
    Sysent::new(2, size_of::<SysSettimeofdayArgs>(), SY_NOLOCK, sys_nosys), // 68 = settimeofday (sys_settimeofday not ported)
    Sysent::new(3, size_of::<SysSetitimerArgs>(), SY_NOLOCK, sys_nosys), // 69 = setitimer (sys_setitimer not ported)
    Sysent::new(2, size_of::<SysGetitimerArgs>(), SY_NOLOCK, sys_nosys), // 70 = getitimer (sys_getitimer not ported)
    Sysent::new(5, size_of::<SysSelectArgs>(), SY_NOLOCK, sys_nosys), // 71 = select (sys_select not ported)
    Sysent::new(6, size_of::<SysKeventArgs>(), SY_NOLOCK, sys_nosys), // 72 = kevent (sys_kevent not ported)
    Sysent::new(2, size_of::<SysMunmapArgs>(), SY_NOLOCK, sys_nosys), // 73 = munmap (sys_munmap not ported)
    Sysent::new(3, size_of::<SysMprotectArgs>(), SY_NOLOCK, sys_nosys), // 74 = mprotect (sys_mprotect not ported)
    Sysent::new(3, size_of::<SysMadviseArgs>(), 0, sys_nosys), // 75 = madvise (sys_madvise not ported)
    Sysent::new(2, size_of::<SysUtimesArgs>(), 0, sys_nosys), // 76 = utimes (sys_utimes not ported)
    Sysent::new(2, size_of::<SysFutimesArgs>(), 0, sys_nosys), // 77 = futimes (sys_futimes not ported)
    Sysent::new(6, size_of::<SysMqueryArgs>(), 0, sys_nosys), // 78 = mquery (sys_mquery not ported)
    Sysent::new(2, size_of::<SysGetgroupsArgs>(), SY_NOLOCK, sys_nosys), // 79 = getgroups (sys_getgroups not ported)
    Sysent::new(2, size_of::<SysSetgroupsArgs>(), 0, sys_nosys), // 80 = setgroups (sys_setgroups not ported)
    Sysent::new(0, 0, 0, sys_nosys), // 81 = getpgrp (sys_getpgrp not ported)
    Sysent::new(2, size_of::<SysSetpgidArgs>(), 0, sys_nosys), // 82 = setpgid (sys_setpgid not ported)
    Sysent::new(5, size_of::<SysFutexArgs>(), SY_NOLOCK, sys_nosys), // 83 = futex (sys_futex not ported)
    Sysent::new(4, size_of::<SysUtimensatArgs>(), 0, sys_nosys), // 84 = utimensat (sys_utimensat not ported)
    Sysent::new(2, size_of::<SysFutimensArgs>(), 0, sys_nosys), // 85 = futimens (sys_futimens not ported)
    Sysent::new(3, size_of::<SysKbindArgs>(), SY_NOLOCK, sys_nosys), // 86 = kbind (sys_kbind not ported)
    Sysent::new(2, size_of::<SysClockGettimeArgs>(), SY_NOLOCK, sys_nosys), // 87 = clock_gettime (sys_clock_gettime not ported)
    Sysent::new(2, size_of::<SysClockSettimeArgs>(), SY_NOLOCK, sys_nosys), // 88 = clock_settime (sys_clock_settime not ported)
    Sysent::new(2, size_of::<SysClockGetresArgs>(), SY_NOLOCK, sys_nosys), // 89 = clock_getres (sys_clock_getres not ported)
    Sysent::new(2, size_of::<SysDup2Args>(), SY_NOLOCK, sys_nosys), // 90 = dup2 (sys_dup2 not ported)
    Sysent::new(2, size_of::<SysNanosleepArgs>(), SY_NOLOCK, sys_nosys), // 91 = nanosleep (sys_nanosleep not ported)
    Sysent::new(3, size_of::<SysFcntlArgs>(), SY_NOLOCK, sys_nosys), // 92 = fcntl (sys_fcntl not ported)
    Sysent::new(4, size_of::<SysAccept4Args>(), SY_NOLOCK, sys_nosys), // 93 = accept4 (sys_accept4 not ported)
    Sysent::new(5, size_of::<SysThrsleepArgs>(), SY_NOLOCK, sys_nosys), // 94 = __thrsleep (sys___thrsleep not ported)
    Sysent::new(1, size_of::<SysFsyncArgs>(), 0, sys_nosys), // 95 = fsync (sys_fsync not ported)
    Sysent::new(3, size_of::<SysSetpriorityArgs>(), 0, sys_nosys), // 96 = setpriority (sys_setpriority not ported)
    Sysent::new(3, size_of::<SysSocketArgs>(), SY_NOLOCK, sys_nosys), // 97 = socket (sys_socket not ported)
    Sysent::new(3, size_of::<SysConnectArgs>(), SY_NOLOCK, sys_nosys), // 98 = connect (sys_connect not ported)
    Sysent::new(3, size_of::<SysGetdentsArgs>(), 0, sys_nosys), // 99 = getdents (sys_getdents not ported)
    Sysent::new(2, size_of::<SysGetpriorityArgs>(), 0, sys_nosys), // 100 = getpriority (sys_getpriority not ported)
    Sysent::new(2, size_of::<SysPipe2Args>(), SY_NOLOCK, sys_nosys), // 101 = pipe2 (sys_pipe2 not ported)
    Sysent::new(3, size_of::<SysDup3Args>(), SY_NOLOCK, sys_nosys), // 102 = dup3 (sys_dup3 not ported)
    Sysent::new(1, size_of::<SysSigreturnArgs>(), 0, sys_nosys), // 103 = sigreturn (sys_sigreturn not ported)
    Sysent::new(3, size_of::<SysBindArgs>(), SY_NOLOCK, sys_nosys), // 104 = bind (sys_bind not ported)
    Sysent::new(5, size_of::<SysSetsockoptArgs>(), SY_NOLOCK, sys_nosys), // 105 = setsockopt (sys_setsockopt not ported)
    Sysent::new(2, size_of::<SysListenArgs>(), SY_NOLOCK, sys_nosys), // 106 = listen (sys_listen not ported)
    Sysent::new(4, size_of::<SysChflagsatArgs>(), 0, sys_nosys), // 107 = chflagsat (sys_chflagsat not ported)
    Sysent::new(2, size_of::<SysPledgeArgs>(), SY_NOLOCK, sys_nosys), // 108 = pledge (sys_pledge not ported)
    Sysent::new(4, size_of::<SysPpollArgs>(), SY_NOLOCK, sys_nosys), // 109 = ppoll (sys_ppoll not ported)
    Sysent::new(6, size_of::<SysPselectArgs>(), SY_NOLOCK, sys_nosys), // 110 = pselect (sys_pselect not ported)
    Sysent::new(1, size_of::<SysSigsuspendArgs>(), SY_NOLOCK, sys_nosys), // 111 = sigsuspend (sys_sigsuspend not ported)
    Sysent::new(3, size_of::<SysSendsyslogArgs>(), SY_NOLOCK, sys_nosys), // 112 = sendsyslog (sys_sendsyslog not ported)
    Sysent::new(0, 0, 0, sys_nosys), // 113 = unimplemented fktrace
    Sysent::new(2, size_of::<SysUnveilArgs>(), 0, sys_nosys), // 114 = unveil (sys_unveil not ported)
    Sysent::new(2, size_of::<SysRealpathArgs>(), SY_NOLOCK, sys_nosys), // 115 = __realpath (sys___realpath not ported)
    Sysent::new(5, size_of::<SysRecvmmsgArgs>(), SY_NOLOCK, sys_nosys), // 116 = recvmmsg (sys_recvmmsg not ported)
    Sysent::new(4, size_of::<SysSendmmsgArgs>(), SY_NOLOCK, sys_nosys), // 117 = sendmmsg (sys_sendmmsg not ported)
    Sysent::new(5, size_of::<SysGetsockoptArgs>(), SY_NOLOCK, sys_nosys), // 118 = getsockopt (sys_getsockopt not ported)
    Sysent::new(3, size_of::<SysThrkillArgs>(), 0, sys_nosys), // 119 = thrkill (sys_thrkill not ported)
    Sysent::new(3, size_of::<SysReadvArgs>(), SY_NOLOCK, sys_nosys), // 120 = readv (sys_readv not ported)
    Sysent::new(3, size_of::<SysWritevArgs>(), SY_NOLOCK, sys_nosys), // 121 = writev (sys_writev not ported)
    Sysent::new(2, size_of::<SysKillArgs>(), 0, sys_nosys), // 122 = kill (sys_kill not ported)
    Sysent::new(3, size_of::<SysFchownArgs>(), 0, sys_nosys), // 123 = fchown (sys_fchown not ported)
    Sysent::new(2, size_of::<SysFchmodArgs>(), 0, sys_nosys), // 124 = fchmod (sys_fchmod not ported)
    Sysent::new(3, size_of::<SysPledgeOpenArgs>(), SY_NOLOCK, sys_nosys), // 125 = __pledge_open (sys___pledge_open not ported)
    Sysent::new(2, size_of::<SysSetreuidArgs>(), 0, sys_nosys), // 126 = setreuid (sys_setreuid not ported)
    Sysent::new(2, size_of::<SysSetregidArgs>(), 0, sys_nosys), // 127 = setregid (sys_setregid not ported)
    Sysent::new(2, size_of::<SysRenameArgs>(), 0, sys_nosys), // 128 = rename (sys_rename not ported)
    Sysent::new(0, 0, 0, sys_nosys),                          // 129 = obsolete otruncate
    Sysent::new(0, 0, 0, sys_nosys),                          // 130 = obsolete oftruncate
    Sysent::new(2, size_of::<SysFlockArgs>(), SY_NOLOCK, sys_nosys), // 131 = flock (sys_flock not ported)
    Sysent::new(2, size_of::<SysMkfifoArgs>(), 0, sys_nosys), // 132 = mkfifo (sys_mkfifo not ported)
    Sysent::new(6, size_of::<SysSendtoArgs>(), SY_NOLOCK, sys_nosys), // 133 = sendto (sys_sendto not ported)
    Sysent::new(2, size_of::<SysShutdownArgs>(), SY_NOLOCK, sys_nosys), // 134 = shutdown (sys_shutdown not ported)
    Sysent::new(4, size_of::<SysSocketpairArgs>(), SY_NOLOCK, sys_nosys), // 135 = socketpair (sys_socketpair not ported)
    Sysent::new(2, size_of::<SysMkdirArgs>(), 0, sys_nosys), // 136 = mkdir (sys_mkdir not ported)
    Sysent::new(1, size_of::<SysRmdirArgs>(), 0, sys_nosys), // 137 = rmdir (sys_rmdir not ported)
    Sysent::new(0, 0, 0, sys_nosys),                         // 138 = obsolete t32_utimes
    Sysent::new(0, 0, 0, sys_nosys),                         // 139 = obsolete 4.2 sigreturn
    Sysent::new(2, size_of::<SysAdjtimeArgs>(), SY_NOLOCK, sys_nosys), // 140 = adjtime (sys_adjtime not ported)
    Sysent::new(2, size_of::<SysGetloginRArgs>(), 0, sys_nosys), // 141 = getlogin_r (sys_getlogin_r not ported)
    Sysent::new(3, size_of::<SysGetthrnameArgs>(), 0, sys_nosys), // 142 = getthrname (sys_getthrname not ported)
    Sysent::new(2, size_of::<SysSetthrnameArgs>(), 0, sys_nosys), // 143 = setthrname (sys_setthrname not ported)
    Sysent::new(0, 0, 0, sys_nosys),                              // 144 = obsolete ogetrlimit
    Sysent::new(0, 0, 0, sys_nosys),                              // 145 = obsolete osetrlimit
    Sysent::new(0, 0, 0, sys_nosys),                              // 146 = obsolete pinsyscall
    Sysent::new(0, 0, 0, sys_nosys), // 147 = setsid (sys_setsid not ported)
    Sysent::new(4, size_of::<SysQuotactlArgs>(), 0, sys_nosys), // 148 = quotactl (sys_quotactl not ported)
    Sysent::new(0, 0, 0, sys_nosys),                            // 149 = obsolete oquota
    Sysent::new(1, size_of::<SysYpconnectArgs>(), SY_NOLOCK, sys_nosys), // 150 = ypconnect (sys_ypconnect not ported)
    Sysent::new(0, 0, 0, sys_nosys),                                     // 151 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                     // 152 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                     // 153 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                     // 154 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                     // 155 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 156 = obsolete ogetdirentries
    Sysent::new(0, 0, 0, sys_nosys), // 157 = obsolete statfs25
    Sysent::new(4, size_of::<SysPinsyscallsArgs>(), 0, sys_nosys), // 158 = pinsyscalls (sys_pinsyscalls not ported)
    Sysent::new(2, size_of::<SysMimmutableArgs>(), 0, sys_nosys), // 159 = mimmutable (sys_mimmutable not ported)
    Sysent::new(4, size_of::<SysWaitidArgs>(), 0, sys_nosys), // 160 = waitid (sys_waitid not ported)
    Sysent::new(2, size_of::<SysGetfhArgs>(), 0, sys_nosys),  // 161 = getfh (sys_getfh not ported)
    Sysent::new(0, 0, 0, sys_nosys),                          // 162 = obsolete ogetdomainname
    Sysent::new(0, 0, 0, sys_nosys),                          // 163 = obsolete osetdomainname
    Sysent::new(0, 0, 0, sys_nosys),                          // 164 = obsolete __tmpfd
    Sysent::new(2, size_of::<SysSysarchArgs>(), 0, sys_nosys), // 165 = sysarch (sys_sysarch not ported)
    Sysent::new(3, size_of::<SysLseekArgs>(), SY_NOLOCK, sys_nosys), // 166 = lseek (sys_lseek not ported)
    Sysent::new(2, size_of::<SysTruncateArgs>(), 0, sys_nosys), // 167 = truncate (sys_truncate not ported)
    Sysent::new(2, size_of::<SysFtruncateArgs>(), 0, sys_nosys), // 168 = ftruncate (sys_ftruncate not ported)
    Sysent::new(4, size_of::<SysPreadArgs>(), SY_NOLOCK, sys_nosys), // 169 = pread (sys_pread not ported)
    Sysent::new(4, size_of::<SysPwriteArgs>(), SY_NOLOCK, sys_nosys), // 170 = pwrite (sys_pwrite not ported)
    Sysent::new(4, size_of::<SysPreadvArgs>(), SY_NOLOCK, sys_nosys), // 171 = preadv (sys_preadv not ported)
    Sysent::new(4, size_of::<SysPwritevArgs>(), SY_NOLOCK, sys_nosys), // 172 = pwritev (sys_pwritev not ported)
    Sysent::new(0, 0, 0, sys_nosys),                                   // 173 = obsolete pad_pread
    Sysent::new(0, 0, 0, sys_nosys),                                   // 174 = obsolete pad_pwrite
    Sysent::new(6, size_of::<SysProfilArgs>(), 0, sys_nosys), // 175 = profil (sys_profil not ported)
    Sysent::new(0, 0, 0, sys_nosys),                          // 176 = unimplemented ntp_adjtime
    Sysent::new(0, 0, 0, sys_nosys),                          // 177 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                          // 178 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                          // 179 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                          // 180 = unimplemented
    Sysent::new(1, size_of::<SysSetgidArgs>(), 0, sys_nosys), // 181 = setgid (sys_setgid not ported)
    Sysent::new(1, size_of::<SysSetegidArgs>(), 0, sys_nosys), // 182 = setegid (sys_setegid not ported)
    Sysent::new(1, size_of::<SysSeteuidArgs>(), 0, sys_nosys), // 183 = seteuid (sys_seteuid not ported)
    Sysent::new(0, 0, 0, sys_nosys),                           // 184 = obsolete lfs_bmapv
    Sysent::new(0, 0, 0, sys_nosys),                           // 185 = obsolete lfs_markv
    Sysent::new(0, 0, 0, sys_nosys),                           // 186 = obsolete lfs_segclean
    Sysent::new(0, 0, 0, sys_nosys),                           // 187 = obsolete lfs_segwait
    Sysent::new(0, 0, 0, sys_nosys),                           // 188 = obsolete stat35
    Sysent::new(0, 0, 0, sys_nosys),                           // 189 = obsolete fstat35
    Sysent::new(4, size_of::<SysPathconfatArgs>(), 0, sys_nosys), // 190 = pathconfat (sys_pathconfat not ported)
    Sysent::new(2, size_of::<SysPathconfArgs>(), 0, sys_nosys), // 191 = pathconf (sys_pathconf not ported)
    Sysent::new(2, size_of::<SysFpathconfArgs>(), 0, sys_nosys), // 192 = fpathconf (sys_fpathconf not ported)
    Sysent::new(3, size_of::<SysSwapctlArgs>(), 0, sys_nosys), // 193 = swapctl (sys_swapctl not ported)
    Sysent::new(2, size_of::<SysGetrlimitArgs>(), SY_NOLOCK, sys_nosys), // 194 = getrlimit (sys_getrlimit not ported)
    Sysent::new(2, size_of::<SysSetrlimitArgs>(), SY_NOLOCK, sys_nosys), // 195 = setrlimit (sys_setrlimit not ported)
    Sysent::new(0, 0, 0, sys_nosys), // 196 = obsolete ogetdirentries48
    Sysent::new(0, 0, 0, sys_nosys), // 197 = obsolete pad_mmap
    Sysent::new(0, 0, 0, sys_nosys), // 198 = obsolete __syscall
    Sysent::new(0, 0, 0, sys_nosys), // 199 = obsolete pad_lseek
    Sysent::new(0, 0, 0, sys_nosys), // 200 = obsolete pad_truncate
    Sysent::new(0, 0, 0, sys_nosys), // 201 = obsolete pad_ftruncate
    Sysent::new(6, size_of::<SysSysctlArgs>(), SY_NOLOCK, sys_nosys), // 202 = sysctl (sys_sysctl not ported)
    Sysent::new(2, size_of::<SysMlockArgs>(), 0, sys_nosys), // 203 = mlock (sys_mlock not ported)
    Sysent::new(2, size_of::<SysMunlockArgs>(), 0, sys_nosys), // 204 = munlock (sys_munlock not ported)
    Sysent::new(0, 0, 0, sys_nosys),                           // 205 = unimplemented sys_undelete
    Sysent::new(0, 0, 0, sys_nosys),                           // 206 = obsolete t32_futimes
    Sysent::new(1, size_of::<SysGetpgidArgs>(), 0, sys_nosys), // 207 = getpgid (sys_getpgid not ported)
    Sysent::new(0, 0, 0, sys_nosys),                           // 208 = obsolete nnpfspioctl
    Sysent::new(3, size_of::<SysUtraceArgs>(), SY_NOLOCK, sys_nosys), // 209 = utrace (sys_utrace not ported)
    Sysent::new(0, 0, 0, sys_nosys),                                  // 210 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 211 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 212 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 213 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 214 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 215 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 216 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 217 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 218 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 219 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                                  // 220 = unimplemented semctl
    Sysent::new(0, 0, 0, sys_nosys),                                  // 221 = unimplemented semget
    Sysent::new(0, 0, 0, sys_nosys),                                  // 222 = obsolete semop35
    Sysent::new(0, 0, 0, sys_nosys),                                  // 223 = obsolete semconfig35
    Sysent::new(0, 0, 0, sys_nosys),                                  // 224 = unimplemented msgctl
    Sysent::new(0, 0, 0, sys_nosys),                                  // 225 = unimplemented msgget
    Sysent::new(0, 0, 0, sys_nosys),                                  // 226 = unimplemented msgsnd
    Sysent::new(0, 0, 0, sys_nosys),                                  // 227 = unimplemented msgrcv
    Sysent::new(0, 0, 0, sys_nosys),                                  // 228 = unimplemented shmat
    Sysent::new(0, 0, 0, sys_nosys),                                  // 229 = unimplemented shmctl
    Sysent::new(0, 0, 0, sys_nosys),                                  // 230 = unimplemented shmdt
    Sysent::new(0, 0, 0, sys_nosys),                                  // 231 = obsolete shmget35
    Sysent::new(0, 0, 0, sys_nosys), // 232 = obsolete t32_clock_gettime
    Sysent::new(0, 0, 0, sys_nosys), // 233 = obsolete t32_clock_settime
    Sysent::new(0, 0, 0, sys_nosys), // 234 = obsolete t32_clock_getres
    Sysent::new(0, 0, 0, sys_nosys), // 235 = unimplemented timer_create
    Sysent::new(0, 0, 0, sys_nosys), // 236 = unimplemented timer_delete
    Sysent::new(0, 0, 0, sys_nosys), // 237 = unimplemented timer_settime
    Sysent::new(0, 0, 0, sys_nosys), // 238 = unimplemented timer_gettime
    Sysent::new(0, 0, 0, sys_nosys), // 239 = unimplemented timer_getoverrun
    Sysent::new(0, 0, 0, sys_nosys), // 240 = obsolete t32_nanosleep
    Sysent::new(0, 0, 0, sys_nosys), // 241 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 242 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 243 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 244 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 245 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 246 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 247 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 248 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys), // 249 = unimplemented
    Sysent::new(3, size_of::<SysMinheritArgs>(), SY_NOLOCK, sys_nosys), // 250 = minherit (sys_minherit not ported)
    Sysent::new(0, 0, 0, sys_nosys),                                    // 251 = obsolete rfork
    Sysent::new(3, size_of::<SysPollArgs>(), SY_NOLOCK, sys_nosys), // 252 = poll (sys_poll not ported)
    Sysent::new(0, 0, SY_NOLOCK, sys_nosys), // 253 = issetugid (sys_issetugid not ported)
    Sysent::new(3, size_of::<SysLchownArgs>(), 0, sys_nosys), // 254 = lchown (sys_lchown not ported)
    Sysent::new(1, size_of::<SysGetsidArgs>(), 0, sys_nosys), // 255 = getsid (sys_getsid not ported)
    Sysent::new(3, size_of::<SysMsyncArgs>(), 0, sys_nosys),  // 256 = msync (sys_msync not ported)
    Sysent::new(0, 0, 0, sys_nosys),                          // 257 = obsolete semctl35
    Sysent::new(0, 0, 0, sys_nosys),                          // 258 = obsolete shmctl35
    Sysent::new(0, 0, 0, sys_nosys),                          // 259 = obsolete msgctl35
    Sysent::new(0, 0, 0, sys_nosys),                          // 260 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                          // 261 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                          // 262 = unimplemented
    Sysent::new(1, size_of::<SysPipeArgs>(), SY_NOLOCK, sys_nosys), // 263 = pipe (sys_pipe not ported)
    Sysent::new(2, size_of::<SysFhopenArgs>(), 0, sys_nosys), // 264 = fhopen (sys_fhopen not ported)
    Sysent::new(0, 0, 0, sys_nosys),                          // 265 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                          // 266 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                          // 267 = obsolete pad_preadv
    Sysent::new(0, 0, 0, sys_nosys),                          // 268 = obsolete pad_pwritev
    Sysent::new(0, 0, SY_NOLOCK, sys_nosys), // 269 = kqueue (sys_kqueue not ported)
    Sysent::new(1, size_of::<SysKqueue1Args>(), SY_NOLOCK, sys_nosys), // 270 = kqueue1 (sys_kqueue1 not ported)
    Sysent::new(1, size_of::<SysMlockallArgs>(), 0, sys_nosys), // 271 = mlockall (sys_mlockall not ported)
    Sysent::new(0, 0, 0, sys_nosys), // 272 = munlockall (sys_munlockall not ported)
    Sysent::new(0, 0, 0, sys_nosys), // 273 = unimplemented sys_getpeereid
    Sysent::new(0, 0, 0, sys_nosys), // 274 = unimplemented sys_extattrctl
    Sysent::new(0, 0, 0, sys_nosys), // 275 = unimplemented sys_extattr_set_file
    Sysent::new(0, 0, 0, sys_nosys), // 276 = unimplemented sys_extattr_get_file
    Sysent::new(0, 0, 0, sys_nosys), // 277 = unimplemented sys_extattr_delete_file
    Sysent::new(0, 0, 0, sys_nosys), // 278 = unimplemented sys_extattr_set_fd
    Sysent::new(0, 0, 0, sys_nosys), // 279 = unimplemented sys_extattr_get_fd
    Sysent::new(0, 0, 0, sys_nosys), // 280 = unimplemented sys_extattr_delete_fd
    Sysent::new(3, size_of::<SysGetresuidArgs>(), SY_NOLOCK, sys_nosys), // 281 = getresuid (sys_getresuid not ported)
    Sysent::new(3, size_of::<SysSetresuidArgs>(), 0, sys_nosys), // 282 = setresuid (sys_setresuid not ported)
    Sysent::new(3, size_of::<SysGetresgidArgs>(), SY_NOLOCK, sys_nosys), // 283 = getresgid (sys_getresgid not ported)
    Sysent::new(3, size_of::<SysSetresgidArgs>(), 0, sys_nosys), // 284 = setresgid (sys_setresgid not ported)
    Sysent::new(0, 0, 0, sys_nosys),                             // 285 = obsolete sys_omquery
    Sysent::new(0, 0, 0, sys_nosys),                             // 286 = obsolete pad_mquery
    Sysent::new(1, size_of::<SysClosefromArgs>(), SY_NOLOCK, sys_nosys), // 287 = closefrom (sys_closefrom not ported)
    Sysent::new(2, size_of::<SysSigaltstackArgs>(), 0, sys_nosys), // 288 = sigaltstack (sys_sigaltstack not ported)
    Sysent::new(0, 0, 0, sys_nosys),                               // 289 = unimplemented shmget
    Sysent::new(0, 0, 0, sys_nosys),                               // 290 = unimplemented semop
    Sysent::new(0, 0, 0, sys_nosys),                               // 291 = obsolete t32_stat
    Sysent::new(0, 0, 0, sys_nosys),                               // 292 = obsolete t32_fstat
    Sysent::new(0, 0, 0, sys_nosys),                               // 293 = obsolete t32_lstat
    Sysent::new(2, size_of::<SysFhstatArgs>(), 0, sys_nosys), // 294 = fhstat (sys_fhstat not ported)
    Sysent::new(0, 0, 0, sys_nosys),                          // 295 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                          // 296 = unimplemented
    Sysent::new(0, 0, 0, sys_nosys),                          // 297 = unimplemented
    Sysent::new(0, 0, SY_NOLOCK, sys_nosys), // 298 = sched_yield (sys_sched_yield not ported)
    Sysent::new(0, 0, SY_NOLOCK, sys_nosys), // 299 = getthrid (sys_getthrid not ported)
    Sysent::new(0, 0, 0, sys_nosys),         // 300 = obsolete t32___thrsleep
    Sysent::new(2, size_of::<SysThrwakeupArgs>(), SY_NOLOCK, sys_nosys), // 301 = __thrwakeup (sys___thrwakeup not ported)
    Sysent::new(1, size_of::<SysThrexitArgs>(), 0, sys_nosys), // 302 = __threxit (sys___threxit not ported)
    Sysent::new(3, size_of::<SysThrsigdivertArgs>(), SY_NOLOCK, sys_nosys), // 303 = __thrsigdivert (sys___thrsigdivert not ported)
    Sysent::new(2, size_of::<SysGetcwdArgs>(), 0, sys_nosys), // 304 = __getcwd (sys___getcwd not ported)
    Sysent::new(2, size_of::<SysAdjfreqArgs>(), SY_NOLOCK, sys_nosys), // 305 = adjfreq (sys_adjfreq not ported)
    Sysent::new(0, 0, 0, sys_nosys),                                   // 306 = obsolete getfsstat53
    Sysent::new(0, 0, 0, sys_nosys),                                   // 307 = obsolete statfs53
    Sysent::new(0, 0, 0, sys_nosys),                                   // 308 = obsolete fstatfs53
    Sysent::new(0, 0, 0, sys_nosys),                                   // 309 = obsolete fhstatfs53
    Sysent::new(1, size_of::<SysSetrtableArgs>(), SY_NOLOCK, sys_nosys), // 310 = setrtable (sys_setrtable not ported)
    Sysent::new(0, 0, SY_NOLOCK, sys_nosys), // 311 = getrtable (sys_getrtable not ported)
    Sysent::new(0, 0, 0, sys_nosys),         // 312 = obsolete t32_getdirentries
    Sysent::new(4, size_of::<SysFaccessatArgs>(), 0, sys_nosys), // 313 = faccessat (sys_faccessat not ported)
    Sysent::new(4, size_of::<SysFchmodatArgs>(), 0, sys_nosys), // 314 = fchmodat (sys_fchmodat not ported)
    Sysent::new(5, size_of::<SysFchownatArgs>(), 0, sys_nosys), // 315 = fchownat (sys_fchownat not ported)
    Sysent::new(0, 0, 0, sys_nosys),                            // 316 = obsolete t32_fstatat
    Sysent::new(5, size_of::<SysLinkatArgs>(), 0, sys_nosys), // 317 = linkat (sys_linkat not ported)
    Sysent::new(3, size_of::<SysMkdiratArgs>(), 0, sys_nosys), // 318 = mkdirat (sys_mkdirat not ported)
    Sysent::new(3, size_of::<SysMkfifoatArgs>(), 0, sys_nosys), // 319 = mkfifoat (sys_mkfifoat not ported)
    Sysent::new(4, size_of::<SysMknodatArgs>(), 0, sys_nosys), // 320 = mknodat (sys_mknodat not ported)
    Sysent::new(4, size_of::<SysOpenatArgs>(), SY_NOLOCK, sys_nosys), // 321 = openat (sys_openat not ported)
    Sysent::new(4, size_of::<SysReadlinkatArgs>(), 0, sys_nosys), // 322 = readlinkat (sys_readlinkat not ported)
    Sysent::new(4, size_of::<SysRenameatArgs>(), 0, sys_nosys), // 323 = renameat (sys_renameat not ported)
    Sysent::new(3, size_of::<SysSymlinkatArgs>(), 0, sys_nosys), // 324 = symlinkat (sys_symlinkat not ported)
    Sysent::new(3, size_of::<SysUnlinkatArgs>(), 0, sys_nosys), // 325 = unlinkat (sys_unlinkat not ported)
    Sysent::new(0, 0, 0, sys_nosys),                            // 326 = obsolete t32_utimensat
    Sysent::new(0, 0, 0, sys_nosys),                            // 327 = obsolete t32_futimens
    Sysent::new(0, 0, 0, sys_nosys),                            // 328 = obsolete __tfork51
    Sysent::new(1, size_of::<SysSetTcbArgs>(), SY_NOLOCK, sys_nosys), // 329 = __set_tcb (sys___set_tcb not ported)
    Sysent::new(0, 0, SY_NOLOCK, sys_nosys), // 330 = __get_tcb (sys___get_tcb not ported)
];
