/* <LICENSES> */
/*
 * Copyright (c) 2026 Emilio Navarrete Lineros <enavarre@outlook.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/*-
 * Copyright (c) 2008 Damien Bergamini <damien.bergamini@free.fr>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
/* </LICENSES> */

/* <CODE> */
//! HMAC (RFC 2104) over MD5, SHA-1 and SHA-256, with the hash's state kept in the context
//! so that a message can be fed in pieces. (IPsec's `HMAC-*-96` does not use this file: the
//! software crypto driver precomputes the inner and outer states itself, see `cryptosoft.c`.)
//!
//! Upstream: sys/crypto/hmac.h @ 3ce1f3f79392, sys/crypto/hmac.c @ 3ce1f3f79392
//! LZ: sys/crypto/hmac.rs@f5985f1d055a
//!
//! ## Deviations
//! - The header and the file share this module; the contexts are [`HmacMd5Ctx`],
//!   [`HmacSha1Ctx`] and [`HmacSha256Ctx`].
//! - The three families are one `macro_rules!` expansion each, so the three bodies, identical
//!   but for the hash, are written once.
//!
//! ## Redesign
//! - Each context and its three functions are a type with methods (`docs/IDIOMS.md`, "a hash
//!   context"): `HMAC_*_Init(ctx, key, key_len)` is `new(key)`, `HMAC_*_Update` is `update`
//!   over a slice, and `HMAC_*_Final(digest, ctx)` is `finalize`, which returns the MAC. The
//!   old names were generated by the macro in LZ too, so no lineage row records them: they
//!   are `HmacMd5Ctx::new` .. `HmacSha256Ctx::finalize` here.
//! - The macro takes the hash's context type and calls its methods (`new`, `update`,
//!   `finalize`) instead of being handed the hash's three C functions.
//! - The fields are private; `key_len` is a `usize`, so the copies of the key need no casts.
//! - Wiping: `k_ipad` and `k_opad` are wiped with `explicit_bzero` as in the C. In addition
//!   `finalize` wipes the inner digest, the hashed long key, and the whole context (the key
//!   the C leaves in it after `HMAC_*_Final`): more than the C wipes, never less, and no
//!   output changes.

use libkern::explicit_bzero;

use super::md5::{MD5_BLOCK_LENGTH, MD5_DIGEST_LENGTH, Md5Ctx};
use super::sha1::{SHA1_BLOCK_LENGTH, SHA1_DIGEST_LENGTH, Sha1Ctx};
use super::sha2::{SHA256_BLOCK_LENGTH, SHA256_DIGEST_LENGTH, Sha256Ctx};
use super::wipe;

/// Defines one HMAC family: the context type over a hash given by its context type and its
/// block and digest lengths, with `new`, `update` and `finalize`.
macro_rules! hmac_family {
    ($ctx_ty:ident, $hash_ctx:ty, $block:ident, $digest:ident, $name:literal) => {
        #[doc = concat!("`", $name, "`: an HMAC in progress, from `new(key)` to `finalize`.")]
        ///
        /// `Default` is the wiped, all-zero context, not an HMAC under any key.
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub struct $ctx_ty {
            /// `ctx`: the inner hash.
            ctx: $hash_ctx,
            /// `key`: the key, hashed first if it was longer than a block.
            key: [u8; $block],
            /// `key_len`: bytes of `key` in use, at most a block.
            key_len: usize,
        }

        impl Default for $ctx_ty {
            fn default() -> Self {
                Self {
                    ctx: <$hash_ctx>::default(),
                    key: [0; $block],
                    key_len: 0,
                }
            }
        }

        impl $ctx_ty {
            #[doc = concat!("`", $name, "`'s `Init`: starts an HMAC under `key`.")]
            pub fn new(key: &[u8]) -> Self {
                let mut this = Self::default();
                let mut k_ipad = [0u8; $block];

                if key.len() > $block {
                    let mut hash = <$hash_ctx>::new();
                    hash.update(key);
                    let mut hashed = hash.finalize();
                    this.key[..$digest].copy_from_slice(&hashed);
                    this.key_len = $digest;
                    explicit_bzero(&mut hashed);
                } else {
                    this.key[..key.len()].copy_from_slice(key);
                    this.key_len = key.len();
                }

                k_ipad[..this.key_len].copy_from_slice(&this.key[..this.key_len]);
                for b in k_ipad.iter_mut() {
                    *b ^= 0x36;
                }

                this.ctx = <$hash_ctx>::new();
                this.ctx.update(&k_ipad);

                explicit_bzero(&mut k_ipad);
                this
            }

            #[doc = concat!("`", $name, "`'s `Update`: adds `data` to the message.")]
            pub fn update(&mut self, data: &[u8]) {
                self.ctx.update(data);
            }

            #[doc = concat!("`", $name, "`'s `Final`: the MAC of the message; the context is wiped.")]
            pub fn finalize(&mut self) -> [u8; $digest] {
                let mut k_opad = [0u8; $block];

                let mut inner = self.ctx.finalize();

                k_opad[..self.key_len].copy_from_slice(&self.key[..self.key_len]);
                for b in k_opad.iter_mut() {
                    *b ^= 0x5c;
                }

                self.ctx = <$hash_ctx>::new();
                self.ctx.update(&k_opad);
                self.ctx.update(&inner);
                let digest = self.ctx.finalize();

                explicit_bzero(&mut k_opad);
                explicit_bzero(&mut inner);
                wipe(self);
                digest
            }
        }
    };
}

hmac_family!(
    HmacMd5Ctx,
    Md5Ctx,
    MD5_BLOCK_LENGTH,
    MD5_DIGEST_LENGTH,
    "HMAC_MD5_CTX"
);

hmac_family!(
    HmacSha1Ctx,
    Sha1Ctx,
    SHA1_BLOCK_LENGTH,
    SHA1_DIGEST_LENGTH,
    "HMAC_SHA1_CTX"
);

hmac_family!(
    HmacSha256Ctx,
    Sha256Ctx,
    SHA256_BLOCK_LENGTH,
    SHA256_DIGEST_LENGTH,
    "HMAC_SHA256_CTX"
);
/* </CODE> */

/* <TESTS> */
#[cfg(test)]
mod tests {
    // Known-answer tests for HMAC-MD5, HMAC-SHA-1 (RFC 2202, test cases 1 to 7) and
    // HMAC-SHA-256 (RFC 4231, test cases 1 to 7); the cases are the RFCs', their expected
    // values agree with Python's `hmac`; a property test that random keys (shorter and longer
    // than a block) and random splits of the data give the one-shot MAC.

    use super::*;
    use crate::crypto::testutil::{XorShift, hex};

    extern crate std;
    use std::vec;
    use std::vec::Vec;

    /// The key and the data of the seven test cases of RFC 4231; RFC 2202 shares the shapes with
    /// shorter keys (`keylen`: 16 for MD5, 20 for SHA-1, and 80 instead of 131 for the long ones).
    fn cases(
        short_key: usize,
        long_key: usize,
        long_msg_7: &'static [u8],
    ) -> Vec<(Vec<u8>, Vec<u8>)> {
        vec![
            (vec![0x0b; short_key], b"Hi There".to_vec()),
            (b"Jefe".to_vec(), b"what do ya want for nothing?".to_vec()),
            (vec![0xaa; short_key], vec![0xdd; 50]),
            ((1..=25).collect(), vec![0xcd; 50]),
            (vec![0x0c; short_key], b"Test With Truncation".to_vec()),
            (
                vec![0xaa; long_key],
                b"Test Using Larger Than Block-Size Key - Hash Key First".to_vec(),
            ),
            (vec![0xaa; long_key], long_msg_7.to_vec()),
        ]
    }

    fn hmac_md5(key: &[u8], data: &[u8]) -> [u8; MD5_DIGEST_LENGTH] {
        let mut ctx = HmacMd5Ctx::new(key);
        ctx.update(data);
        ctx.finalize()
    }

    fn hmac_sha1(key: &[u8], data: &[u8]) -> [u8; SHA1_DIGEST_LENGTH] {
        let mut ctx = HmacSha1Ctx::new(key);
        ctx.update(data);
        ctx.finalize()
    }

    fn hmac_sha256(key: &[u8], data: &[u8]) -> [u8; SHA256_DIGEST_LENGTH] {
        let mut ctx = HmacSha256Ctx::new(key);
        ctx.update(data);
        ctx.finalize()
    }

    #[test]
    fn rfc2202_hmac_md5() {
        let want = [
            "9294727a3638bb1c13f48ef8158bfc9d",
            "750c783e6ab0b503eaa86e310a5db738",
            "56be34521d144c88dbb8c733f0e8b3f6",
            "697eaf0aca3a3aea3a75164746ffaa79",
            "56461ef2342edc00f9bab995690efd4c",
            "6b1ab7fe4bd7bf8f0b62e6ce61b9d0cd",
            "6f630fad67cda0ee1fb1f562db3aa53e",
        ];
        let c = cases(
            16,
            80,
            b"Test Using Larger Than Block-Size Key and Larger Than One Block-Size Data",
        );
        for (i, ((key, data), want)) in c.iter().zip(want).enumerate() {
            assert_eq!(hmac_md5(key, data).to_vec(), hex(want), "case {}", i + 1);
        }
    }

    #[test]
    fn rfc2202_hmac_sha1() {
        let want = [
            "b617318655057264e28bc0b6fb378c8ef146be00",
            "effcdf6ae5eb2fa2d27416d5f184df9c259a7c79",
            "125d7342b9ac11cd91a39af48aa17b4f63f175d3",
            "4c9007f4026250c6bc8414f9bf50c86c2d7235da",
            "4c1a03424b55e07fe7f27be1d58bb9324a9a5a04",
            "aa4ae5e15272d00e95705637ce8a3b55ed402112",
            "e8e99d0f45237d786d6bbaa7965c7808bbff1a91",
        ];
        let c = cases(
            20,
            80,
            b"Test Using Larger Than Block-Size Key and Larger Than One Block-Size Data",
        );
        for (i, ((key, data), want)) in c.iter().zip(want).enumerate() {
            assert_eq!(hmac_sha1(key, data).to_vec(), hex(want), "case {}", i + 1);
        }
    }

    #[test]
    fn rfc4231_hmac_sha256() {
        let want = [
            "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7",
            "5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843",
            "773ea91e36800e46854db8ebd09181a72959098b3ef8c122d9635514ced565fe",
            "82558a389a443c0ea4cc819899f2083a85f0faa3e578f8077a2e3ff46729665b",
            "a3b6167473100ee06e0c796c2955552bfa6f7c0a6a8aef8b93f860aab0cd20c5",
            "60e431591ee0b67f0d8a26aacbf5b77f8e0bc6213728c5140546040f0ee37f54",
            "9b09ffa71b942fcb27635fbcd5b0e944bfdc63644f0713938a7f51535c3a35e2",
        ];
        let c = cases(
        20,
        131,
        b"This is a test using a larger than block-size key and a larger than block-size data. The key needs to be hashed before being used by the HMAC algorithm.",
    );
        for (i, ((key, data), want)) in c.iter().zip(want).enumerate() {
            assert_eq!(hmac_sha256(key, data).to_vec(), hex(want), "case {}", i + 1);
        }
    }

    #[test]
    fn any_split_of_the_data_gives_the_same_mac() {
        let key = [0x42u8; 40];
        let data: Vec<u8> = (0..200).map(|i| (i * 3) as u8).collect();
        let whole = hmac_sha1(&key, &data);
        for chunk in [1usize, 13, 64, 65] {
            let mut ctx = HmacSha1Ctx::new(&key);
            for piece in data.chunks(chunk) {
                ctx.update(piece);
            }
            assert_eq!(ctx.finalize(), whole, "chunks of {chunk}");
            // finalize wipes the context, key included.
            assert_eq!(ctx, HmacSha1Ctx::default());
        }
    }

    #[test]
    fn random_keys_and_splits_give_the_one_shot_mac() {
        let mut rng = XorShift::new(0x686d_6163_7370_6c74);
        for _ in 0..150 {
            let key_len = rng.below(200);
            let key = rng.bytes(key_len);
            let len = rng.below(400);
            let data = rng.bytes(len);
            let (w5, w1, w256) = (
                hmac_md5(&key, &data),
                hmac_sha1(&key, &data),
                hmac_sha256(&key, &data),
            );
            let mut c5 = HmacMd5Ctx::new(&key);
            for piece in rng.split(&data) {
                c5.update(piece);
            }
            let mut c1 = HmacSha1Ctx::new(&key);
            for piece in rng.split(&data) {
                c1.update(piece);
            }
            let mut c256 = HmacSha256Ctx::new(&key);
            for piece in rng.split(&data) {
                c256.update(piece);
            }
            assert_eq!(c5.finalize(), w5, "md5, key {key_len}, data {len}");
            assert_eq!(c1.finalize(), w1, "sha1, key {key_len}, data {len}");
            assert_eq!(c256.finalize(), w256, "sha256, key {key_len}, data {len}");
        }
    }

    #[test]
    fn a_key_longer_than_the_block_is_hashed_first() {
        // The two are the same key to HMAC (RFC 2104): a long key is replaced by its digest.
        let long = [0x55u8; 100];
        let mut ctx = Sha1Ctx::new();
        ctx.update(&long);
        let digest = ctx.finalize();
        assert_eq!(hmac_sha1(&long, b"data"), hmac_sha1(&digest, b"data"));
        let ctx = HmacSha1Ctx::new(&long);
        assert_eq!(ctx.key_len, SHA1_DIGEST_LENGTH);
    }
}
/* </TESTS> */
