/* <LICENSES> */
/*
 * Copyright (c) 2026 Emilio Navarrete Lineros <enavarre@outlook.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/* *
 * rijndael-alg-fst.h
 *
 * @version 3.0 (December 2000)
 *
 * Optimised ANSI C code for the Rijndael cipher (now AES)
 *
 * @author Vincent Rijmen <vincent.rijmen@esat.kuleuven.ac.be>
 * @author Antoon Bosselaers <antoon.bosselaers@esat.kuleuven.ac.be>
 * @author Paulo Barreto <paulo.barreto@terra.com.br>
 *
 * This code is hereby placed in the public domain.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHORS ''AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* *
 * rijndael-alg-fst.c
 *
 * @version 3.0 (December 2000)
 *
 * Optimised ANSI C code for the Rijndael cipher (now AES)
 *
 * @author Vincent Rijmen <vincent.rijmen@esat.kuleuven.ac.be>
 * @author Antoon Bosselaers <antoon.bosselaers@esat.kuleuven.ac.be>
 * @author Paulo Barreto <paulo.barreto@terra.com.br>
 *
 * This code is hereby placed in the public domain.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHORS ''AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/* </LICENSES> */

/* <CODE> */
//! Rijndael (AES) in the table-driven form of Rijmen, Bosselaers and Barreto's
//! `rijndael-alg-fst`: the cipher `enc_xform_aes_xts` uses for XTS. (`aes.c` is the
//! constant-time implementation the rest of the crypto framework uses.)
//!
//! Upstream: sys/crypto/rijndael.h @ 3ce1f3f79392, sys/crypto/rijndael.c @ 3ce1f3f79392
//! LZ: sys/crypto/rijndael.rs@f5985f1d055a
//!
//! ## Deviations
//! - The header and the file share this module; `rijndael_ctx` is [`RijndaelCtx`].
//! - The eight 1 KiB lookup tables `Te0` to `Te3`, `Td0` to `Td3` and `Td4` are computed at
//!   compile time by `const fn`s from their definition (the comment above them in the C:
//!   `Te0[x] = S[x].[02, 01, 01, 03]` and so on, with `S` the AES S-box generated by the
//!   inversion in GF(2^8) and the affine map); the FIPS 197 vectors in the tests exercise
//!   them.
//! - `rijndaelKeySetupEnc` computes the round function of the key schedule with the S-box
//!   (`SubWord(RotWord(w)) ^ Rcon`) where the C reads the S-box out of masked `Te` words and
//!   unrolls one loop per key size; the schedule is the same. The key setup functions return
//!   `Result` (`EINVAL` for a size other than 128, 192 or 256 bits) instead of a round count
//!   or 0.
//! - `FULL_UNROLL` is not ported: the C leaves it undefined, so the looped rounds are the code
//!   that runs. `rijndaelDecrypt` stays private (`static` in the C).
//!
//! ## Redesign
//! - `rijndael_set_key` and `rijndael_set_key_enc_only` are the constructors
//!   [`RijndaelCtx::new`] and [`RijndaelCtx::new_enc_only`], which return the context or
//!   `EINVAL`; `rijndael_encrypt` and `rijndael_decrypt` are methods that return the output
//!   block (LZ: a `&mut RijndaelCtx` filled and `Result<(), Errno>` returned, `&mut [u8; 16]`
//!   out parameters, so `xform.c`'s in-place calls needed a copy).
//! - The key size is the key slice's length (16, 24 or 32 bytes), where the C (and LZ) took
//!   the key and, beside it, its size in bits; a caller passes exactly the key bytes
//!   (`xform.rs` the halves of the XTS key, `softraid_crypto.rs` the 32-byte mask key). The
//!   check is the same: any other size is `EINVAL`.
//! - `rijndaelKeySetupEnc`/`Dec` fill a `&mut [u32; 60]` and return the round count as a
//!   `usize`; `rijndaelEncrypt` returns the block. `enc_only` is a `bool` and `Nr` the `usize`
//!   field `nr` (LZ: two `i32`s); the rounds walk the schedule as `[u32; 4]` round keys, and
//!   table indices are bytes widened with `From` instead of shifts and `as`.
//! - [`RijndaelCtx`] zeroes its schedules when dropped (`docs/IDIOMS.md`), so it is no longer
//!   `Copy` or `PartialEq`.

use super::wipe;
use crate::sys::errno::Errno;

/// `AES_MAXKEYBITS`.
pub const AES_MAXKEYBITS: usize = 256;
/// `AES_MAXKEYBYTES`.
pub const AES_MAXKEYBYTES: usize = AES_MAXKEYBITS / 8;
/// `AES_MAXROUNDS`: for 256-bit keys, fewer for less.
pub const AES_MAXROUNDS: usize = 14;

/// `rcon`: for 128-bit blocks, Rijndael never uses more than 10 rcon values.
const RCON: [u32; 10] = [
    0x01000000, 0x02000000, 0x04000000, 0x08000000, 0x10000000, 0x20000000, 0x40000000, 0x80000000,
    0x1B000000, 0x36000000,
];

/// Multiplication by x in GF(2^8) modulo x^8 + x^4 + x^3 + x + 1.
const fn xtime(x: u8) -> u8 {
    (x << 1) ^ if x & 0x80 != 0 { 0x1b } else { 0 }
}

/// Multiplication in GF(2^8).
const fn gmul(a: u8, b: u8) -> u8 {
    let mut a = a;
    let mut b = b;
    let mut p = 0u8;
    while b != 0 {
        if b & 1 != 0 {
            p ^= a;
        }
        a = xtime(a);
        b >>= 1;
    }
    p
}

/// The S-box and its inverse: the multiplicative inverse in GF(2^8) followed by the affine
/// transformation, found by walking the powers of 3 (`p`) and their inverses (`q`).
const fn gen_sboxes() -> ([u8; 256], [u8; 256]) {
    let mut sbox = [0u8; 256];
    let mut inv = [0u8; 256];
    let mut p = 1u8;
    let mut q = 1u8;

    loop {
        // multiply p by 3
        p = p ^ (p << 1) ^ if p & 0x80 != 0 { 0x1b } else { 0 };
        // divide q by 3 (equals multiplication by 0xf6)
        q ^= q << 1;
        q ^= q << 2;
        q ^= q << 4;
        if q & 0x80 != 0 {
            q ^= 0x09;
        }
        // the affine transformation
        let x = q ^ q.rotate_left(1) ^ q.rotate_left(2) ^ q.rotate_left(3) ^ q.rotate_left(4);
        sbox[p as usize] = x ^ 0x63;
        if p == 1 {
            break;
        }
    }
    sbox[0] = 0x63;

    let mut i = 0;
    while i < 256 {
        inv[sbox[i] as usize] = i as u8;
        i += 1;
    }
    (sbox, inv)
}

/// `S[x]`.
static SBOX: [u8; 256] = gen_sboxes().0;

/// `Td4[x] = Si[x].[01]`: the inverse S-box.
static TD4: [u8; 256] = gen_sboxes().1;

/// The table `t` with every entry rotated right by `n` bits.
const fn rotr_table(t: [u32; 256], n: u32) -> [u32; 256] {
    let mut r = [0u32; 256];
    let mut x = 0;
    while x < 256 {
        r[x] = t[x].rotate_right(n);
        x += 1;
    }
    r
}

/// `Te0[x] = S[x].[02, 01, 01, 03]`.
const fn gen_te0() -> [u32; 256] {
    let sbox = gen_sboxes().0;
    let mut t = [0u32; 256];
    let mut x = 0;
    while x < 256 {
        let s = sbox[x];
        t[x] = u32::from_be_bytes([gmul(s, 2), s, s, gmul(s, 3)]);
        x += 1;
    }
    t
}

/// `Td0[x] = Si[x].[0e, 09, 0d, 0b]`.
const fn gen_td0() -> [u32; 256] {
    let inv = gen_sboxes().1;
    let mut t = [0u32; 256];
    let mut x = 0;
    while x < 256 {
        let s = inv[x];
        t[x] = u32::from_be_bytes([gmul(s, 0x0e), gmul(s, 0x09), gmul(s, 0x0d), gmul(s, 0x0b)]);
        x += 1;
    }
    t
}

/// `Te0`.
static TE0: [u32; 256] = gen_te0();
/// `Te1[x] = S[x].[03, 02, 01, 01]`.
static TE1: [u32; 256] = rotr_table(gen_te0(), 8);
/// `Te2[x] = S[x].[01, 03, 02, 01]`.
static TE2: [u32; 256] = rotr_table(gen_te0(), 16);
/// `Te3[x] = S[x].[01, 01, 03, 02]`.
static TE3: [u32; 256] = rotr_table(gen_te0(), 24);
/// `Td0`.
static TD0: [u32; 256] = gen_td0();
/// `Td1[x] = Si[x].[0b, 0e, 09, 0d]`.
static TD1: [u32; 256] = rotr_table(gen_td0(), 8);
/// `Td2[x] = Si[x].[0d, 0b, 0e, 09]`.
static TD2: [u32; 256] = rotr_table(gen_td0(), 16);
/// `Td3[x] = Si[x].[09, 0d, 0b, 0e]`.
static TD3: [u32; 256] = rotr_table(gen_td0(), 24);

/// `rijndael_ctx`: the key schedules of one key. Built by [`RijndaelCtx::new`] or
/// [`RijndaelCtx::new_enc_only`]; zeroed when dropped.
#[derive(Clone, Debug)]
pub struct RijndaelCtx {
    /// `enc_only`: context contains only encrypt schedule.
    pub enc_only: bool,
    /// `Nr`: key-length-dependent number of rounds.
    pub nr: usize,
    /// `ek`: encrypt key schedule.
    pub ek: [u32; 4 * (AES_MAXROUNDS + 1)],
    /// `dk`: decrypt key schedule.
    pub dk: [u32; 4 * (AES_MAXROUNDS + 1)],
}

impl Default for RijndaelCtx {
    fn default() -> Self {
        Self {
            enc_only: false,
            nr: 0,
            ek: [0; 4 * (AES_MAXROUNDS + 1)],
            dk: [0; 4 * (AES_MAXROUNDS + 1)],
        }
    }
}

impl Drop for RijndaelCtx {
    /// Wipes the key schedules (`docs/IDIOMS.md`: a key schedule is zeroed when dropped).
    fn drop(&mut self) {
        self.zeroize();
    }
}

impl RijndaelCtx {
    /// Zeroes the key schedules, with stores the compiler keeps (`crate::crypto::wipe`).
    pub(crate) fn zeroize(&mut self) {
        self.ek.iter_mut().chain(self.dk.iter_mut()).for_each(wipe);
        wipe(&mut self.nr);
        wipe(&mut self.enc_only);
    }

    /// `rijndael_set_key_enc_only`: a context for encryption only, for a key of 16, 24 or 32
    /// bytes (`EINVAL` otherwise).
    pub fn new_enc_only(key: &[u8]) -> Result<Self, Errno> {
        let mut ctx = Self::default();
        ctx.nr = rijndaelKeySetupEnc(&mut ctx.ek, key)?;
        ctx.enc_only = true;
        Ok(ctx)
    }

    /// `rijndael_set_key`: a context for both encryption and decryption, for a key of 16, 24
    /// or 32 bytes (`EINVAL` otherwise).
    pub fn new(key: &[u8]) -> Result<Self, Errno> {
        let mut ctx = Self::default();
        let rounds = rijndaelKeySetupEnc(&mut ctx.ek, key)?;
        if rijndaelKeySetupDec(&mut ctx.dk, key)? != rounds {
            return Err(Errno::EINVAL);
        }
        ctx.nr = rounds;
        ctx.enc_only = false;
        Ok(ctx)
    }

    /// `rijndael_decrypt`: the decryption of `src`.
    pub fn decrypt(&self, src: &[u8; 16]) -> [u8; 16] {
        rijndaelDecrypt(&self.dk, self.nr, src)
    }

    /// `rijndael_encrypt`: the encryption of `src`.
    pub fn encrypt(&self, src: &[u8; 16]) -> [u8; 16] {
        rijndaelEncrypt(&self.ek, self.nr, src)
    }
}

/// `GETU32`: the four big-endian words of a block or key, in order.
fn words(b: &[u8]) -> impl Iterator<Item = u32> + '_ {
    b.as_chunks::<4>().0.iter().map(|w| u32::from_be_bytes(*w))
}

/// Byte `i` (0 the most significant) of `x`, as a table index.
fn byte(x: u32, i: usize) -> usize {
    usize::from(x.to_be_bytes()[i])
}

/// `SubWord`: the S-box on each byte of `w`.
fn sub_word(w: u32) -> u32 {
    u32::from_be_bytes(w.to_be_bytes().map(|b| SBOX[usize::from(b)]))
}

/// `rijndaelKeySetupEnc`: expand the cipher key (16, 24 or 32 bytes) into the encryption key
/// schedule `rk` (`4 * (Nr + 1)` words); the number of rounds, or `EINVAL` for another size.
#[allow(non_snake_case)] // the C name
pub fn rijndaelKeySetupEnc(
    rk: &mut [u32; 4 * (AES_MAXROUNDS + 1)],
    cipherKey: &[u8],
) -> Result<usize, Errno> {
    let nk = match cipherKey.len() {
        16 => 4,
        24 => 6,
        32 => 8,
        _ => return Err(Errno::EINVAL),
    };
    let nr = nk + 6;

    for (w, k) in rk.iter_mut().zip(words(cipherKey)) {
        *w = k;
    }
    for i in nk..4 * (nr + 1) {
        let mut temp = rk[i - 1];
        if i % nk == 0 {
            temp = sub_word(temp.rotate_left(8)) ^ RCON[i / nk - 1];
        } else if nk > 6 && i % nk == 4 {
            temp = sub_word(temp);
        }
        rk[i] = rk[i - nk] ^ temp;
    }
    Ok(nr)
}

/// `rijndaelKeySetupDec`: expand the cipher key into the decryption key schedule `rk`; the
/// number of rounds, or `EINVAL` for a key size other than 16, 24 or 32 bytes.
#[allow(non_snake_case)] // the C name
pub fn rijndaelKeySetupDec(
    rk: &mut [u32; 4 * (AES_MAXROUNDS + 1)],
    cipherKey: &[u8],
) -> Result<usize, Errno> {
    // expand the cipher key:
    let nr = rijndaelKeySetupEnc(rk, cipherKey)?;

    // invert the order of the round keys:
    let round_keys = rk[..4 * (nr + 1)].as_chunks_mut::<4>().0;
    round_keys.reverse();
    // apply the inverse MixColumn transform to all round keys but the first and the last:
    for w in round_keys[1..nr].iter_mut().flatten() {
        *w = TD0[usize::from(SBOX[byte(*w, 0)])]
            ^ TD1[usize::from(SBOX[byte(*w, 1)])]
            ^ TD2[usize::from(SBOX[byte(*w, 2)])]
            ^ TD3[usize::from(SBOX[byte(*w, 3)])];
    }
    Ok(nr)
}

/// `rijndaelEncrypt`: the encryption of the block `pt` under the schedule `rk` of `nr` rounds.
#[allow(non_snake_case)] // the C name
pub fn rijndaelEncrypt(rk: &[u32], nr: usize, pt: &[u8; 16]) -> [u8; 16] {
    let round_keys = rk.as_chunks::<4>().0;

    // map byte array block to cipher state and add initial round key:
    let mut s = [0u32; 4];
    for ((w, p), k) in s.iter_mut().zip(words(pt)).zip(round_keys[0]) {
        *w = p ^ k;
    }

    // Nr - 1 full rounds:
    for rk in &round_keys[1..nr] {
        let mut t = [0u32; 4];
        for j in 0..4 {
            t[j] = TE0[byte(s[j], 0)]
                ^ TE1[byte(s[(j + 1) % 4], 1)]
                ^ TE2[byte(s[(j + 2) % 4], 2)]
                ^ TE3[byte(s[(j + 3) % 4], 3)]
                ^ rk[j];
        }
        s = t;
    }

    // apply last round and map cipher state to byte array block:
    let rk = &round_keys[nr];
    let mut ct = [0u8; 16];
    for (j, out) in ct.as_chunks_mut::<4>().0.iter_mut().enumerate() {
        let w = (TE2[byte(s[j], 0)] & 0xff000000)
            ^ (TE3[byte(s[(j + 1) % 4], 1)] & 0x00ff0000)
            ^ (TE0[byte(s[(j + 2) % 4], 2)] & 0x0000ff00)
            ^ (TE1[byte(s[(j + 3) % 4], 3)] & 0x000000ff)
            ^ rk[j];
        *out = w.to_be_bytes();
    }
    ct
}

/// `rijndaelDecrypt`: the decryption of the block `ct` under the decryption schedule `rk`.
#[allow(non_snake_case)] // the C name
fn rijndaelDecrypt(rk: &[u32], nr: usize, ct: &[u8; 16]) -> [u8; 16] {
    let round_keys = rk.as_chunks::<4>().0;

    // map byte array block to cipher state and add initial round key:
    let mut s = [0u32; 4];
    for ((w, c), k) in s.iter_mut().zip(words(ct)).zip(round_keys[0]) {
        *w = c ^ k;
    }

    // Nr - 1 full rounds:
    for rk in &round_keys[1..nr] {
        let mut t = [0u32; 4];
        for j in 0..4 {
            t[j] = TD0[byte(s[j], 0)]
                ^ TD1[byte(s[(j + 3) % 4], 1)]
                ^ TD2[byte(s[(j + 2) % 4], 2)]
                ^ TD3[byte(s[(j + 1) % 4], 3)]
                ^ rk[j];
        }
        s = t;
    }

    // apply last round and map cipher state to byte array block:
    let rk = &round_keys[nr];
    let mut pt = [0u8; 16];
    for (j, out) in pt.as_chunks_mut::<4>().0.iter_mut().enumerate() {
        let w = u32::from_be_bytes([
            TD4[byte(s[j], 0)],
            TD4[byte(s[(j + 3) % 4], 1)],
            TD4[byte(s[(j + 2) % 4], 2)],
            TD4[byte(s[(j + 1) % 4], 3)],
        ]) ^ rk[j];
        *out = w.to_be_bytes();
    }
    pt
}
/* </CODE> */

/* <TESTS> */
#[cfg(test)]
mod tests {
    // Known-answer tests for the table-driven Rijndael: FIPS 197 appendices A.1 (key expansion),
    // B and C (the example vectors for 128, 192 and 256-bit keys), the generated tables, and a
    // reference-backed comparison of every table with the C file's.

    use super::*;
    use crate::crypto::testutil::{c_table, hex, hexn};

    extern crate std;

    fn key() -> [u8; 32] {
        let mut k = [0u8; 32];
        for (i, b) in k.iter_mut().enumerate() {
            *b = i as u8;
        }
        k
    }

    const PT: &str = "00112233445566778899aabbccddeeff";

    #[test]
    fn fips197_appendix_c() {
        let want = [
            (128, "69c4e0d86a7b0430d8cdb78070b4c55a"),
            (192, "dda97ca4864cdfe06eaf70a0ec0d7191"),
            (256, "8ea2b7ca516745bfeafc49904b496089"),
        ];
        for (bits, ct) in want {
            let k = key();
            let ctx = RijndaelCtx::new(&k[..bits / 8]).expect("AES key size");
            assert_eq!(ctx.nr, bits / 32 + 6);
            assert!(!ctx.enc_only);

            let pt: [u8; 16] = hexn(PT);
            let out = ctx.encrypt(&pt);
            assert_eq!(out.to_vec(), hex(ct), "encrypt {bits}");
            assert_eq!(ctx.decrypt(&out), pt, "decrypt {bits}");
        }
    }

    #[test]
    fn fips197_appendix_b() {
        let k: [u8; 16] = hexn("2b7e151628aed2a6abf7158809cf4f3c");
        let pt: [u8; 16] = hexn("3243f6a8885a308d313198a2e0370734");
        let ctx = RijndaelCtx::new(&k).expect("AES key size");
        assert_eq!(
            ctx.encrypt(&pt).to_vec(),
            hex("3925841d02dc09fbdc118597196a0b32")
        );

        // Appendix A.1: the last round key of the expansion.
        assert_eq!(
            &ctx.ek[40..44],
            &[0xd014f9a8, 0xc9ee2589, 0xe13f0cc8, 0xb6630ca6]
        );
    }

    #[test]
    fn encrypt_only_context() {
        let k = key();
        let ctx = RijndaelCtx::new_enc_only(&k[..16]).expect("AES key size");
        assert_eq!((ctx.nr, ctx.enc_only), (10, true));
        let pt: [u8; 16] = hexn(PT);
        assert_eq!(
            ctx.encrypt(&pt).to_vec(),
            hex("69c4e0d86a7b0430d8cdb78070b4c55a")
        );
        // Nothing was put in the decryption schedule.
        assert!(ctx.dk.iter().all(|w| *w == 0));
    }

    #[test]
    fn bad_key_sizes_are_rejected() {
        // The C's sizes in bits other than 128, 192 and 256, as key lengths in bytes (a
        // multiple of 8 bits), and the byte lengths around the good ones.
        for len in [0, 1, 8, 15, 17, 20, 23, 25, 28, 31, 33, 48, 64] {
            assert_eq!(
                RijndaelCtx::new(&[0; 64][..len]).map(drop),
                Err(Errno::EINVAL),
                "{len}"
            );
            assert_eq!(
                RijndaelCtx::new_enc_only(&[0; 64][..len]).map(drop),
                Err(Errno::EINVAL),
                "{len}"
            );
        }
    }

    #[test]
    fn the_decrypt_schedule_is_the_reversed_inverse_mixed_encrypt_schedule() {
        let k = key();
        let mut ek = [0u32; 60];
        let mut dk = [0u32; 60];
        assert_eq!(rijndaelKeySetupEnc(&mut ek, &k), Ok(14));
        assert_eq!(rijndaelKeySetupDec(&mut dk, &k), Ok(14));
        // The first and last round keys swap places unchanged.
        assert_eq!(dk[..4], ek[56..60]);
        assert_eq!(dk[56..60], ek[..4]);
    }

    /// xorshift64: the property tests' generator.
    fn next(state: &mut u64) -> u64 {
        *state ^= *state << 13;
        *state ^= *state >> 7;
        *state ^= *state << 17;
        *state
    }

    #[test]
    fn round_trips_over_random_keys_and_blocks() {
        let mut st = 0x0123_4567_89ab_cdefu64;
        for i in 0..300 {
            let len = [16, 24, 32][i % 3];
            let k: std::vec::Vec<u8> = (0..len).map(|_| next(&mut st) as u8).collect();
            let ctx = RijndaelCtx::new(&k).expect("AES key size");
            let enc = RijndaelCtx::new_enc_only(&k).expect("AES key size");
            let mut pt = [0u8; 16];
            pt[..8].copy_from_slice(&next(&mut st).to_le_bytes());
            pt[8..].copy_from_slice(&next(&mut st).to_le_bytes());
            let ct = ctx.encrypt(&pt);
            assert_eq!(enc.encrypt(&pt), ct);
            assert_eq!(ctx.decrypt(&ct), pt);
            assert_eq!(ctx.encrypt(&ctx.decrypt(&pt)), pt);
        }
    }

    #[test]
    fn zeroize_clears_the_schedules() {
        // What `Drop` runs.
        let mut ctx = RijndaelCtx::new(&key()).expect("AES key size");
        ctx.zeroize();
        assert!(ctx.ek.iter().chain(ctx.dk.iter()).all(|w| *w == 0));
        assert_eq!((ctx.nr, ctx.enc_only), (0, false));
    }

    #[test]
    fn generated_tables_spot_checks() {
        assert_eq!(
            (SBOX[0x00], SBOX[0x01], SBOX[0x53], SBOX[0xff]),
            (0x63, 0x7c, 0xed, 0x16)
        );
        for x in 0..256 {
            assert_eq!(TD4[SBOX[x] as usize] as usize, x);
        }
        assert_eq!((TE0[0], TE0[1]), (0xc66363a5, 0xf87c7c84));
        assert_eq!(TD0[0], 0x51f4a750);
    }

    #[test]
    #[ignore = "reads the C tables from $OPENBSD_SRC (just test-ref)"]
    fn tables_match_the_c_file() {
        let f = "sys/crypto/rijndael.c";
        let check32 = |name: &str, table: &[u32; 256]| {
            let c = c_table(f, name);
            assert_eq!(c.len(), 256, "{name}");
            for (i, (a, b)) in c.iter().zip(table).enumerate() {
                assert_eq!(*a, u64::from(*b), "{name}[{i}]");
            }
        };
        check32("Te0", &TE0);
        check32("Te1", &TE1);
        check32("Te2", &TE2);
        check32("Te3", &TE3);
        check32("Td0", &TD0);
        check32("Td1", &TD1);
        check32("Td2", &TD2);
        check32("Td3", &TD3);

        let c = c_table(f, "Td4");
        assert_eq!(c.len(), 256);
        for (i, (a, b)) in c.iter().zip(TD4.iter()).enumerate() {
            assert_eq!(*a, u64::from(*b), "Td4[{i}]");
        }
        let c = c_table(f, "rcon");
        assert_eq!(c.len(), RCON.len());
        for (a, b) in c.iter().zip(RCON) {
            assert_eq!(*a, u64::from(b));
        }
    }
}
/* </TESTS> */
