use super::*;

#[test]
fn uword_accessors_are_little_endian() {
    let mut w: UWord = [0; 2];
    usetw(&mut w, 0x1234);
    assert_eq!(w, [0x34, 0x12]);
    assert_eq!(ugetw(w), 0x1234);
    usetw2(&mut w, 0xab, 0xcd);
    assert_eq!(w, [0xcd, 0xab]);
    assert_eq!(ugetw(w), 0xabcd);

    let mut d: UDWord = [0; 4];
    usetdw(&mut d, 0x1122_3344);
    assert_eq!(d, [0x44, 0x33, 0x22, 0x11]);
    assert_eq!(ugetdw(d), 0x1122_3344);
}

#[test]
fn endpoint_macros() {
    assert_eq!(ue_get_dir(0x81), UE_DIR_IN);
    assert_eq!(ue_get_dir(0x02), UE_DIR_OUT);
    assert_eq!(ue_set_dir(0x02, 1), 0x82);
    assert_eq!(ue_get_addr(0x83), 3);
    assert_eq!(ue_get_xfertype(0x02), UE_BULK);
    assert_eq!(ue_get_iso_type(0x0d), UE_ISO_SYNC);
    // wMaxPacketSize 0x1400: 2 additional transactions of 1024 bytes.
    assert_eq!(ue_get_trans(0x1400), 2);
    assert_eq!(ue_get_size(0x1400), 0x400);
    assert_eq!(ups_port_ls_get(ups_port_ls_set(UPS_PORT_LS_RX_DETECT)), 5);
}

#[test]
fn wire_views_are_bounds_checked() {
    let bytes = [9u8, UDESC_CONFIG, 0x20, 0x00, 1, 1, 0, 0x80, 50, 0xff];
    let cd = usb_wire_at::<UsbConfigDescriptor>(&bytes, 0).unwrap();
    assert_eq!(ugetw(cd.wTotalLength), 32);
    assert_eq!(cd.bMaxPower, 50);
    assert!(usb_wire_at::<UsbConfigDescriptor>(&bytes, 2).is_none());
    assert!(usb_wire_at::<UsbDescriptor>(&bytes, usize::MAX).is_none());
    let d = UsbDeviceDescriptor::read_from(&bytes[..3]);
    assert_eq!(d.bLength, 9);
    assert_eq!(d.idVendor, [0, 0]);
    let mut hd = UsbHubDescriptor::zeroed();
    hd.DeviceRemovable[1] = 0x04;
    assert_eq!(uhd_not_remov(&hd, 10), 1);
    assert_eq!(uhd_not_remov(&hd, 9), 0);
}

/// The values clang computes for the C header on LP64 (`_IOWR('U', 1, struct
/// usb_ctl_request)` and the others).
#[test]
fn ioctl_commands_have_openbsd_values() {
    for (ours, c) in [
        (USB_REQUEST, 0xc020_5501u64),
        (USB_SETDEBUG, 0x8004_5502),
        (USB_DEVICEINFO, 0xc21c_5504),
        (USB_DEVICESTATS, 0x4020_5505),
        (USB_DEVICE_GET_CDESC, 0xc014_5506),
        (USB_DEVICE_GET_FDESC, 0xc018_5507),
        (USB_DEVICE_GET_DDESC, 0xc014_5508),
        (USB_GET_REPORT_DESC, 0x4404_5515),
        (USB_GET_REPORT, 0xc404_5517),
        (USB_SET_REPORT, 0x8404_5518),
        (USB_GET_REPORT_ID, 0x4004_5519),
        (USB_GET_CONFIG, 0x4004_5564),
        (USB_SET_CONFIG, 0x8004_5565),
        (USB_GET_ALTINTERFACE, 0xc00c_5566),
        (USB_SET_ALTINTERFACE, 0xc00c_5567),
        (USB_GET_NO_ALT, 0xc00c_5568),
        (USB_GET_DEVICE_DESC, 0x4012_5569),
        (USB_GET_CONFIG_DESC, 0xc010_556a),
        (USB_GET_INTERFACE_DESC, 0xc018_556b),
        (USB_GET_ENDPOINT_DESC, 0xc018_556c),
        (USB_GET_FULL_DESC, 0xc010_556d),
        (USB_DO_REQUEST, 0xc020_556f),
        (USB_GET_DEVICEINFO, 0x421c_5570),
        (USB_SET_SHORT_XFER, 0x8004_5571),
        (USB_SET_TIMEOUT, 0x8004_5572),
    ] {
        assert_eq!(ours, c, "{ours:#x}");
    }
}

#[test]
#[ignore = "needs OPENBSD_SRC (just test-ref)"]
fn constants_match_the_c_header() {
    let defs = crate::reftest::defines("sys/dev/usb/usb.h");
    let mut ours = crate::reftest::assert_defines!(defs;
        USB_STACK_VERSION, USB_MAX_DEVICES, USB_START_ADDR, USB_CONTROL_ENDPOINT,
        USB_MAX_ENDPOINTS, USB_FRAMES_PER_SECOND,
        UT_WRITE, UT_READ, UT_STANDARD, UT_CLASS, UT_VENDOR, UT_DEVICE, UT_INTERFACE,
        UT_ENDPOINT, UT_OTHER, UT_READ_DEVICE, UT_READ_INTERFACE, UT_READ_ENDPOINT,
        UT_WRITE_DEVICE, UT_WRITE_INTERFACE, UT_WRITE_ENDPOINT, UT_READ_CLASS_DEVICE,
        UT_READ_CLASS_INTERFACE, UT_READ_CLASS_OTHER, UT_READ_CLASS_ENDPOINT,
        UT_WRITE_CLASS_DEVICE, UT_WRITE_CLASS_INTERFACE, UT_WRITE_CLASS_OTHER,
        UT_WRITE_CLASS_ENDPOINT, UT_READ_VENDOR_DEVICE, UT_READ_VENDOR_INTERFACE,
        UT_READ_VENDOR_OTHER, UT_READ_VENDOR_ENDPOINT, UT_WRITE_VENDOR_DEVICE,
        UT_WRITE_VENDOR_INTERFACE, UT_WRITE_VENDOR_OTHER, UT_WRITE_VENDOR_ENDPOINT,
        UR_GET_STATUS, UR_CLEAR_FEATURE, UR_SET_FEATURE, UR_SET_ADDRESS, UR_GET_DESCRIPTOR,
        UDESC_DEVICE, UDESC_CONFIG, UDESC_STRING, UDESC_INTERFACE, UDESC_ENDPOINT,
        UDESC_DEVICE_QUALIFIER, UDESC_OTHER_SPEED_CONFIGURATION, UDESC_INTERFACE_POWER,
        UDESC_OTG, UDESC_DEBUG, UDESC_IFACE_ASSOC, UDESC_BOS, UDESC_DEVICE_CAPABILITY,
        UDESC_CS_DEVICE, UDESC_CS_CONFIG, UDESC_CS_STRING, UDESC_CS_INTERFACE,
        UDESC_CS_ENDPOINT, UDESC_HUB, UDESC_SS_HUB, UDESC_ENDPOINT_SS_COMP,
        UR_SET_DESCRIPTOR, UR_GET_CONFIG, UR_SET_CONFIG, UR_GET_INTERFACE, UR_SET_INTERFACE,
        UR_SYNCH_FRAME, UF_ENDPOINT_HALT, UF_DEVICE_REMOTE_WAKEUP, UF_TEST_MODE,
        USB_MAX_IPACKET, USB_2_MAX_CTRL_PACKET, USB_2_MAX_BULK_PACKET,
        USB_DEVICE_DESCRIPTOR_SIZE, UC_BUS_POWERED, UC_SELF_POWERED, UC_REMOTE_WAKEUP,
        UC_POWER_FACTOR, USB_CONFIG_DESCRIPTOR_SIZE, USB_INTERFACE_DESCRIPTOR_SIZE,
        USB_INTERFACE_ASSOC_DESCRIPTOR_SIZE, UE_DIR_IN, UE_DIR_OUT, UE_ADDR, UE_XFERTYPE,
        UE_CONTROL, UE_ISOCHRONOUS, UE_BULK, UE_INTERRUPT, UE_ISO_TYPE, UE_ISO_ASYNC,
        UE_ISO_ADAPT, UE_ISO_SYNC, USB_ENDPOINT_DESCRIPTOR_SIZE,
        USB_ENDPOINT_SS_COMP_DESCRIPTOR_SIZE, USB_MAX_STRING_LEN, USB_LANGUAGE_TABLE,
        UR_GET_BUS_STATE, UR_CLEAR_TT_BUFFER, UR_RESET_TT, UR_GET_TT_STATE, UR_STOP_TT,
        UR_SET_DEPTH, UHF_C_HUB_LOCAL_POWER, UHF_C_HUB_OVER_CURRENT, UHF_PORT_CONNECTION,
        UHF_PORT_ENABLE, UHF_PORT_SUSPEND, UHF_PORT_OVER_CURRENT, UHF_PORT_RESET,
        UHF_PORT_POWER, UHF_PORT_LOW_SPEED, UHF_C_PORT_CONNECTION, UHF_C_PORT_ENABLE,
        UHF_C_PORT_SUSPEND, UHF_C_PORT_OVER_CURRENT, UHF_C_PORT_RESET, UHF_PORT_TEST,
        UHF_PORT_INDICATOR, UHF_C_PORT_L1, UHF_PORT_DISOWN_TO_1_1, UHF_PORT_U1_TIMEOUT,
        UHF_PORT_U2_TIMEOUT, UHF_C_PORT_LINK_STATE, UHF_C_PORT_CONFIG_ERROR,
        UHF_PORT_REMOTE_WAKE_MASK, UHF_BH_PORT_RESET, UHF_C_BH_PORT_RESET,
        UHF_FORCE_LINKPM_ACCEPT, UHD_PWR, UHD_PWR_GANGED, UHD_PWR_INDIVIDUAL,
        UHD_PWR_NO_SWITCH, UHD_COMPOUND, UHD_OC, UHD_OC_GLOBAL, UHD_OC_INDIVIDUAL,
        UHD_OC_NONE, UHD_TT_THINK, UHD_TT_THINK_8, UHD_TT_THINK_16, UHD_TT_THINK_24,
        UHD_TT_THINK_32, UHD_PORT_IND, UHD_PWRON_FACTOR, USB_HUB_DESCRIPTOR_SIZE,
        USB_HUB_SS_DESCRIPTOR_SIZE, USB_DEVICE_QUALIFIER_SIZE, UOTG_SRP, UOTG_HNP,
        UOTG_B_HNP_ENABLE, UOTG_A_HNP_SUPPORT, UOTG_A_ALT_HNP_SUPPORT, UDS_SELF_POWERED,
        UDS_REMOTE_WAKEUP, UES_HALT, UHS_LOCAL_POWER, UHS_OVER_CURRENT,
        UPS_CURRENT_CONNECT_STATUS, UPS_PORT_ENABLED, UPS_SUSPEND, UPS_OVERCURRENT_INDICATOR,
        UPS_RESET, UPS_PORT_L1, UPS_PORT_LS_U0, UPS_PORT_LS_U1, UPS_PORT_LS_U2,
        UPS_PORT_LS_U3, UPS_PORT_LS_SS_DISABLED, UPS_PORT_LS_RX_DETECT,
        UPS_PORT_LS_SS_INACTIVE, UPS_PORT_LS_POLLING, UPS_PORT_LS_RECOVERY,
        UPS_PORT_LS_HOT_RESET, UPS_PORT_LS_COMP_MOD, UPS_PORT_LS_LOOPBACK,
        UPS_PORT_LS_RESUME, UPS_PORT_POWER, UPS_PORT_POWER_SS, UPS_FULL_SPEED,
        UPS_LOW_SPEED, UPS_HIGH_SPEED, UPS_PORT_TEST, UPS_PORT_INDICATOR,
        UPS_C_CONNECT_STATUS, UPS_C_PORT_ENABLED, UPS_C_SUSPEND, UPS_C_OVERCURRENT_INDICATOR,
        UPS_C_PORT_RESET, UPS_C_PORT_L1, UPS_C_BH_PORT_RESET, UPS_C_PORT_LINK_STATE,
        UPS_C_PORT_CONFIG_ERROR, UDCLASS_IN_INTERFACE, UDCLASS_COMM, UDCLASS_HUB,
        UDSUBCLASS_HUB, UDPROTO_FSHUB, UDPROTO_HSHUBSTT, UDPROTO_HSHUBMTT, UDPROTO_SSHUB,
        UDCLASS_DIAGNOSTIC, UDCLASS_WIRELESS, UDCLASS_VIDEO, UDSUBCLASS_RF,
        UDPROTO_BLUETOOTH, UDCLASS_VENDOR, UICLASS_UNSPEC, UICLASS_AUDIO,
        UISUBCLASS_AUDIOCONTROL, UISUBCLASS_AUDIOSTREAM, UISUBCLASS_MIDISTREAM, UICLASS_CDC,
        UISUBCLASS_DIRECT_LINE_CONTROL_MODEL, UISUBCLASS_ABSTRACT_CONTROL_MODEL,
        UISUBCLASS_TELEPHONE_CONTROL_MODEL, UISUBCLASS_MULTICHANNEL_CONTROL_MODEL,
        UISUBCLASS_CAPI_CONTROLMODEL, UISUBCLASS_ETHERNET_NETWORKING_CONTROL_MODEL,
        UISUBCLASS_ATM_NETWORKING_CONTROL_MODEL, UISUBCLASS_MOBILE_DIRECT_LINE_MODEL,
        UISUBCLASS_NETWORK_CONTROL_MODEL, UISUBCLASS_MOBILE_BROADBAND_INTERFACE_MODEL,
        UIPROTO_CDC_NOCLASS, UIPROTO_CDC_AT, UICLASS_HID, UISUBCLASS_BOOT,
        UIPROTO_BOOT_KEYBOARD, UIPROTO_BOOT_MOUSE, UICLASS_PHYSICAL, UICLASS_IMAGE,
        UICLASS_PRINTER, UISUBCLASS_PRINTER, UIPROTO_PRINTER_UNI, UIPROTO_PRINTER_BI,
        UIPROTO_PRINTER_1284, UICLASS_MASS, UISUBCLASS_RBC, UISUBCLASS_SFF8020I,
        UISUBCLASS_QIC157, UISUBCLASS_UFI, UISUBCLASS_SFF8070I, UISUBCLASS_SCSI,
        UIPROTO_MASS_CBI_I, UIPROTO_MASS_CBI, UIPROTO_MASS_BBB_OLD, UIPROTO_MASS_BBB,
        UICLASS_HUB, UISUBCLASS_HUB, UIPROTO_FSHUB, UIPROTO_HSHUBSTT, UIPROTO_HSHUBMTT,
        UICLASS_CDC_DATA, UISUBCLASS_DATA, UIPROTO_DATA_MBIM, UIPROTO_DATA_ISDNBRI,
        UIPROTO_DATA_HDLC, UIPROTO_DATA_TRANSPARENT, UIPROTO_DATA_Q921M, UIPROTO_DATA_Q921,
        UIPROTO_DATA_Q921TM, UIPROTO_DATA_V42BIS, UIPROTO_DATA_Q931, UIPROTO_DATA_V120,
        UIPROTO_DATA_CAPI, UIPROTO_DATA_HOST_BASED, UIPROTO_DATA_PUF, UIPROTO_DATA_VENDOR,
        UICLASS_SMARTCARD, UICLASS_SECURITY, UICLASS_VIDEO, UISUBCLASS_VIDEOCONTROL,
        UISUBCLASS_VIDEOSTREAM, UISUBCLASS_VIDEO_IF_COLLECTION, UICLASS_DIAGNOSTIC,
        UICLASS_WIRELESS, UISUBCLASS_RF, UIPROTO_BLUETOOTH, UIPROTO_RNDIS, UICLASS_MISC,
        UISUBCLASS_SYNC, UIPROTO_ACTIVESYNC, UICLASS_APPL_SPEC, UISUBCLASS_FIRMWARE_DOWNLOAD,
        UISUBCLASS_IRDA, UIPROTO_IRDA, UICLASS_VENDOR, USB_HUB_MAX_DEPTH,
        USB_POWER_DOWN_TIME, USB_PORT_POWER_DOWN_TIME, USB_PORT_RESET_DELAY,
        USB_PORT_ROOT_RESET_DELAY, USB_PORT_RESET_RECOVERY, USB_PORT_POWERUP_DELAY,
        USB_SET_ADDRESS_SETTLE, USB_RESUME_DELAY, USB_RESUME_WAIT, USB_RESUME_RECOVERY,
        USB_EXTRA_POWER_UP_TIME, USB_MIN_POWER, USB_MAX_POWER, USB_BUS_RESET_DELAY,
        USB_UNCONFIG_NO, USB_UNCONFIG_INDEX, USBD_SHORT_XFER_OK, USB_CURRENT_CONFIG_INDEX,
        USB_CURRENT_ALT_INDEX, USB_MAX_DEVNAMES, USB_MAX_DEVNAMELEN, USB_SPEED_LOW,
        USB_SPEED_FULL, USB_SPEED_HIGH, USB_SPEED_SUPER,
    );
    // The ioctl commands are `_IO*` expressions the parser does not evaluate; their values
    // are checked by `ioctl_commands_have_openbsd_values`.
    ours.extend([
        "USB_REQUEST",
        "USB_SETDEBUG",
        "USB_DEVICEINFO",
        "USB_DEVICESTATS",
        "USB_DEVICE_GET_CDESC",
        "USB_DEVICE_GET_FDESC",
        "USB_DEVICE_GET_DDESC",
        "USB_GET_REPORT_DESC",
        "USB_GET_REPORT",
        "USB_SET_REPORT",
        "USB_GET_REPORT_ID",
        "USB_GET_CONFIG",
        "USB_SET_CONFIG",
        "USB_GET_ALTINTERFACE",
        "USB_SET_ALTINTERFACE",
        "USB_GET_NO_ALT",
        "USB_GET_DEVICE_DESC",
        "USB_GET_CONFIG_DESC",
        "USB_GET_INTERFACE_DESC",
        "USB_GET_ENDPOINT_DESC",
        "USB_GET_FULL_DESC",
        "USB_DO_REQUEST",
        "USB_GET_DEVICEINFO",
        "USB_SET_SHORT_XFER",
        "USB_SET_TIMEOUT",
    ]);
    for prefix in [
        "UT_",
        "UR_",
        "UDESC_",
        "UF_",
        "UC_",
        "UE_",
        "UHF_",
        "UHD_",
        "UOTG_",
        "UDS_",
        "UES_",
        "UHS_",
        "UPS_",
        "UDCLASS_",
        "UDSUBCLASS_",
        "UDPROTO_",
        "UICLASS_",
        "UISUBCLASS_",
        "UIPROTO_",
        "USB_",
    ] {
        crate::reftest::assert_complete(&defs, prefix, &ours);
    }
}
