/*	$OpenBSD: usbdevs.h,v 1.802 2026/09/09 03:52:55 daniel Exp $	*/

/*
 * THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
 *
 * generated from:
 *	OpenBSD: usbdevs,v 1.789 2026/08/23 23:34:20 jsg Exp
 */
/* $NetBSD: usbdevs,v 1.322 2003/05/10 17:47:14 hamajima Exp $ */
/* <LICENSES> */
/*
 * Copyright (c) 1998, 1999, 2000 The NetBSD Foundation, Inc.
 * All rights reserved.
 *
 * This code is derived from software contributed to The NetBSD Foundation
 * by Lennart Augustsson (lennart@augustsson.net) at
 * Carlstedt Research & Technology.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
/* </LICENSES> */

//! `<dev/usb/usbdevs.h>`: USB vendor and product IDs, the subset the ported code names.
//!
//! Upstream: sys/dev/usb/usbdevs.h @ 3ce1f3f79392
//!
//! OpenBSD generates this header (and `usbdevs_data.h`, the names `USBVERBOSE` prints) from
//! `sys/dev/usb/usbdevs` with `devlist2h.awk`: about 4,800 lines of defines. Here the IDs are
//! added by hand as the code that uses them is ported, with the generated names, values and
//! comments, in the header's order.
//!
//! ## Deviations
//! - Partial: only the IDs some ported file names are present (`usb_quirks.c`'s table). The
//!   whole header, and `usbdevs_data.h` for `option USBVERBOSE` (in GENERIC), wait for a
//!   generator in `tools/xtask`, as `pcidevs.h` does; until then `usb_subr.c` names devices
//!   as a kernel without the option does (`vendor 0x...`, `product 0x...`).
//! - The IDs are `u16`, the type of `idVendor`/`idProduct` once read with `UGETW`.

/// `USB_VENDOR_HP`: Hewlett Packard.
pub const USB_VENDOR_HP: u16 = 0x03f0;
/// `USB_VENDOR_NEC`: NEC.
pub const USB_VENDOR_NEC: u16 = 0x0409;
/// `USB_VENDOR_TI`: Texas Instruments.
pub const USB_VENDOR_TI: u16 = 0x0451;
/// `USB_VENDOR_KYE`: KYE Systems.
pub const USB_VENDOR_KYE: u16 = 0x0458;
/// `USB_VENDOR_MICROSOFT`: Microsoft.
pub const USB_VENDOR_MICROSOFT: u16 = 0x045e;
/// `USB_VENDOR_CHERRY`: Cherry Mikroschalter.
pub const USB_VENDOR_CHERRY: u16 = 0x046a;
/// `USB_VENDOR_LOGITECH`: Logitech.
pub const USB_VENDOR_LOGITECH: u16 = 0x046d;
/// `USB_VENDOR_SANYO`: Sanyo Electric.
pub const USB_VENDOR_SANYO: u16 = 0x0474;
/// `USB_VENDOR_KENSINGTON`: Kensington.
pub const USB_VENDOR_KENSINGTON: u16 = 0x047d;
/// `USB_VENDOR_YAMAHA`: YAMAHA.
pub const USB_VENDOR_YAMAHA: u16 = 0x0499;
/// `USB_VENDOR_CYPRESS`: Cypress Semiconductor.
pub const USB_VENDOR_CYPRESS: u16 = 0x04b4;
/// `USB_VENDOR_MICROCHIP`: Microchip Technology, Inc..
pub const USB_VENDOR_MICROCHIP: u16 = 0x04d8;
/// `USB_VENDOR_CHICONY`: Chicony Electronics.
pub const USB_VENDOR_CHICONY: u16 = 0x04f2;
/// `USB_VENDOR_ALCOR2`: Alcor Micro.
pub const USB_VENDOR_ALCOR2: u16 = 0x0566;
/// `USB_VENDOR_OMRON`: OMRON Corporation.
pub const USB_VENDOR_OMRON: u16 = 0x0590;
/// `USB_VENDOR_APPLE`: Apple Computer.
pub const USB_VENDOR_APPLE: u16 = 0x05ac;
/// `USB_VENDOR_QUALCOMM`: Qualcomm.
pub const USB_VENDOR_QUALCOMM: u16 = 0x05c6;
/// `USB_VENDOR_QTRONIX`: Qtronix.
pub const USB_VENDOR_QTRONIX: u16 = 0x05c7;
/// `USB_VENDOR_SUNTAC`: SUN Corporation.
pub const USB_VENDOR_SUNTAC: u16 = 0x05db;
/// `USB_VENDOR_MUSTEK2`: Mustek Systems.
pub const USB_VENDOR_MUSTEK2: u16 = 0x0665;
/// `USB_VENDOR_SIEMENS2`: Siemens.
pub const USB_VENDOR_SIEMENS2: u16 = 0x0681;
/// `USB_VENDOR_MCT`: MCT.
pub const USB_VENDOR_MCT: u16 = 0x0711;
/// `USB_VENDOR_EICON`: Eicon Networks.
pub const USB_VENDOR_EICON: u16 = 0x0734;
/// `USB_VENDOR_METRICOM`: Metricom.
pub const USB_VENDOR_METRICOM: u16 = 0x0870;
/// `USB_VENDOR_PIXART`: PixArt.
pub const USB_VENDOR_PIXART: u16 = 0x093a;
/// `USB_VENDOR_SHANTOU`: ShanTou.
pub const USB_VENDOR_SHANTOU: u16 = 0x0a46;
/// `USB_VENDOR_TERRATEC`: TerraTec Electronic GmbH.
pub const USB_VENDOR_TERRATEC: u16 = 0x0ccd;
/// `USB_VENDOR_QUALCOMM2`: Qualcomm.
pub const USB_VENDOR_QUALCOMM2: u16 = 0x1004;
/// `USB_VENDOR_VELLEMAN`: Velleman.
pub const USB_VENDOR_VELLEMAN: u16 = 0x10cf;
/// `USB_VENDOR_TENX`: Ten X Technology, Inc..
pub const USB_VENDOR_TENX: u16 = 0x1130;
/// `USB_VENDOR_HUAWEI`: HUAWEI Technologies.
pub const USB_VENDOR_HUAWEI: u16 = 0x12d1;
/// `USB_VENDOR_RALINK`: Ralink Technology.
pub const USB_VENDOR_RALINK: u16 = 0x148f;
/// `USB_VENDOR_INSIDEOUT`: Inside Out Networks.
pub const USB_VENDOR_INSIDEOUT: u16 = 0x1608;
/// `USB_VENDOR_CMOTECH`: CMOTECH.
pub const USB_VENDOR_CMOTECH: u16 = 0x16d8;
/// `USB_VENDOR_MECANIQUE`: Mecanique.
pub const USB_VENDOR_MECANIQUE: u16 = 0x1781;
/// `USB_VENDOR_LENOVO`: Lenovo.
pub const USB_VENDOR_LENOVO: u16 = 0x17ef;
/// `USB_VENDOR_DREAMLINK`: Dream Link.
pub const USB_VENDOR_DREAMLINK: u16 = 0x1d34;
/// `USB_VENDOR_METAGEEK`: MetaGeek.
pub const USB_VENDOR_METAGEEK: u16 = 0x1dd5;
/// `USB_VENDOR_MOTOROLA2`: Motorola.
pub const USB_VENDOR_MOTOROLA2: u16 = 0x22b8;
/// `USB_VENDOR_HAILUCK`: HAILUCK Co., Ltd.
pub const USB_VENDOR_HAILUCK: u16 = 0x258a;
/// `USB_VENDOR_DELL`: Dell.
pub const USB_VENDOR_DELL: u16 = 0x413c;
/// `USB_PRODUCT_ALCOR2_KBD_HUB`: Kbd Hub.
pub const USB_PRODUCT_ALCOR2_KBD_HUB: u16 = 0x2802;
/// `USB_PRODUCT_APPLE_SPEAKERS`: Speakers.
pub const USB_PRODUCT_APPLE_SPEAKERS: u16 = 0x1101;
/// `USB_PRODUCT_APPLE_IPHONE`: iPhone.
pub const USB_PRODUCT_APPLE_IPHONE: u16 = 0x1290;
/// `USB_PRODUCT_APPLE_IPOD_TOUCH`: iPod Touch.
pub const USB_PRODUCT_APPLE_IPOD_TOUCH: u16 = 0x1291;
/// `USB_PRODUCT_APPLE_IPHONE_3G`: iPhone 3G.
pub const USB_PRODUCT_APPLE_IPHONE_3G: u16 = 0x1292;
/// `USB_PRODUCT_APPLE_IPOD_TOUCH_2G`: iPod Touch 2G.
pub const USB_PRODUCT_APPLE_IPOD_TOUCH_2G: u16 = 0x1293;
/// `USB_PRODUCT_APPLE_IPHONE_3GS`: iPhone 3GS.
pub const USB_PRODUCT_APPLE_IPHONE_3GS: u16 = 0x1294;
/// `USB_PRODUCT_APPLE_IPHONE_4_GSM`: iPhone 4 GSM.
pub const USB_PRODUCT_APPLE_IPHONE_4_GSM: u16 = 0x1297;
/// `USB_PRODUCT_APPLE_IPOD_TOUCH_3G`: iPod Touch 3G.
pub const USB_PRODUCT_APPLE_IPOD_TOUCH_3G: u16 = 0x1299;
/// `USB_PRODUCT_APPLE_IPAD`: iPad.
pub const USB_PRODUCT_APPLE_IPAD: u16 = 0x129a;
/// `USB_PRODUCT_APPLE_IPHONE_4_CDMA`: iPhone 4 CDMA.
pub const USB_PRODUCT_APPLE_IPHONE_4_CDMA: u16 = 0x129c;
/// `USB_PRODUCT_APPLE_IPOD_TOUCH_4G`: iPod Touch 4G.
pub const USB_PRODUCT_APPLE_IPOD_TOUCH_4G: u16 = 0x129e;
/// `USB_PRODUCT_APPLE_IPAD2`: iPad 2.
pub const USB_PRODUCT_APPLE_IPAD2: u16 = 0x129f;
/// `USB_PRODUCT_APPLE_IPHONE_4S`: iPhone 4S.
pub const USB_PRODUCT_APPLE_IPHONE_4S: u16 = 0x12a0;
/// `USB_PRODUCT_APPLE_IPHONE_6`: iPhone 6.
pub const USB_PRODUCT_APPLE_IPHONE_6: u16 = 0x12a8;
/// `USB_PRODUCT_CHERRY_MOUSE1`: mouse.
pub const USB_PRODUCT_CHERRY_MOUSE1: u16 = 0xb091;
/// `USB_PRODUCT_CHICONY_OPTMOUSE`: Optical Mouse.
pub const USB_PRODUCT_CHICONY_OPTMOUSE: u16 = 0x0939;
/// `USB_PRODUCT_CMOTECH_CM5100P`: CM-5100P EVDO.
pub const USB_PRODUCT_CMOTECH_CM5100P: u16 = 0x5523;
/// `USB_PRODUCT_CMOTECH_CCU550`: CCU-550 EVDO.
pub const USB_PRODUCT_CMOTECH_CCU550: u16 = 0x5533;
/// `USB_PRODUCT_CMOTECH_CNU550PRO`: CNU-550pro EVDO.
pub const USB_PRODUCT_CMOTECH_CNU550PRO: u16 = 0x5543;
/// `USB_PRODUCT_CYPRESS_SISPM_OLD`: Sispm - old version.
pub const USB_PRODUCT_CYPRESS_SISPM_OLD: u16 = 0xfd10;
/// `USB_PRODUCT_CYPRESS_SISPM`: Sispm.
pub const USB_PRODUCT_CYPRESS_SISPM: u16 = 0xfd11;
/// `USB_PRODUCT_CYPRESS_SISPM_FLASH`: Sispm - flash.
pub const USB_PRODUCT_CYPRESS_SISPM_FLASH: u16 = 0xfd12;
/// `USB_PRODUCT_DELL_PIXARTMOUSE`: Optical Mouse.
pub const USB_PRODUCT_DELL_PIXARTMOUSE: u16 = 0x301a;
/// `USB_PRODUCT_DREAMLINK_ULMB1`: USB LED Message Board v1.0.
pub const USB_PRODUCT_DREAMLINK_ULMB1: u16 = 0x0013;
/// `USB_PRODUCT_EICON_DIVA852`: Diva 852 ISDN TA.
pub const USB_PRODUCT_EICON_DIVA852: u16 = 0x4905;
/// `USB_PRODUCT_HAILUCK_KEYBOARD`: Keyboard.
pub const USB_PRODUCT_HAILUCK_KEYBOARD: u16 = 0x001e;
/// `USB_PRODUCT_HP_895C`: DeskJet 895C.
pub const USB_PRODUCT_HP_895C: u16 = 0x0004;
/// `USB_PRODUCT_HP_880C`: DeskJet 880C.
pub const USB_PRODUCT_HP_880C: u16 = 0x0104;
/// `USB_PRODUCT_HP_815C`: DeskJet 815C.
pub const USB_PRODUCT_HP_815C: u16 = 0x0204;
/// `USB_PRODUCT_HP_1220C`: DeskJet 1220C.
pub const USB_PRODUCT_HP_1220C: u16 = 0x0212;
/// `USB_PRODUCT_HP_810C`: DeskJet 810C/812C.
pub const USB_PRODUCT_HP_810C: u16 = 0x0304;
/// `USB_PRODUCT_HP_830C`: DeskJet 830C.
pub const USB_PRODUCT_HP_830C: u16 = 0x0404;
/// `USB_PRODUCT_HP_885C`: DeskJet 885C.
pub const USB_PRODUCT_HP_885C: u16 = 0x0504;
/// `USB_PRODUCT_HP_840C`: DeskJet 840c.
pub const USB_PRODUCT_HP_840C: u16 = 0x0604;
/// `USB_PRODUCT_HP_816C`: DeskJet 816C.
pub const USB_PRODUCT_HP_816C: u16 = 0x0804;
/// `USB_PRODUCT_HP_959C`: Deskjet 959C.
pub const USB_PRODUCT_HP_959C: u16 = 0x1104;
/// `USB_PRODUCT_HUAWEI_E220`: E220 HSDPA.
pub const USB_PRODUCT_HUAWEI_E220: u16 = 0x1003;
/// `USB_PRODUCT_INSIDEOUT_EDGEPORT4`: EdgePort/4 RS232.
pub const USB_PRODUCT_INSIDEOUT_EDGEPORT4: u16 = 0x0001;
/// `USB_PRODUCT_KENSINGTON_SLIMBLADE`: Slimblade Trackball.
pub const USB_PRODUCT_KENSINGTON_SLIMBLADE: u16 = 0x2041;
/// `USB_PRODUCT_KYE_NICHE`: Niche mouse.
pub const USB_PRODUCT_KYE_NICHE: u16 = 0x0001;
/// `USB_PRODUCT_LENOVO_OPTUSBMOUSE`: Optical Mouse.
pub const USB_PRODUCT_LENOVO_OPTUSBMOUSE: u16 = 0x600e;
/// `USB_PRODUCT_LENOVO_PIXARTMOUSE`: Optical Mouse.
pub const USB_PRODUCT_LENOVO_PIXARTMOUSE: u16 = 0x6019;
/// `USB_PRODUCT_LOGITECH_B100_1`: B100 mouse.
pub const USB_PRODUCT_LOGITECH_B100_1: u16 = 0xc05a;
/// `USB_PRODUCT_LOGITECH_B100_2`: B100 mouse.
pub const USB_PRODUCT_LOGITECH_B100_2: u16 = 0xc077;
/// `USB_PRODUCT_MCT_HUB0100`: Hub.
pub const USB_PRODUCT_MCT_HUB0100: u16 = 0x0100;
/// `USB_PRODUCT_MCT_USB232`: RS232.
pub const USB_PRODUCT_MCT_USB232: u16 = 0x0210;
/// `USB_PRODUCT_MECANIQUE_WISPY`: MetaGeek Wi-Spy.
pub const USB_PRODUCT_MECANIQUE_WISPY: u16 = 0x083e;
/// `USB_PRODUCT_METAGEEK_WISPY24I`: Wi-Spy 2.4i.
pub const USB_PRODUCT_METAGEEK_WISPY24I: u16 = 0x2400;
/// `USB_PRODUCT_METRICOM_RICOCHET_GS`: Ricochet GS.
pub const USB_PRODUCT_METRICOM_RICOCHET_GS: u16 = 0x0001;
/// `USB_PRODUCT_MICROCHIP_USBLCD20X2`: USB-LCD-20x2.
pub const USB_PRODUCT_MICROCHIP_USBLCD20X2: u16 = 0x0002;
/// `USB_PRODUCT_MICROCHIP_USBLCD256X64`: USB-LCD-256x64.
pub const USB_PRODUCT_MICROCHIP_USBLCD256X64: u16 = 0xc002;
/// `USB_PRODUCT_MICROSOFT_WLNOTEBOOK`: Wireless Optical Mouse (Model 1023).
pub const USB_PRODUCT_MICROSOFT_WLNOTEBOOK: u16 = 0x00b9;
/// `USB_PRODUCT_MICROSOFT_PIXARTMOUSE`: Optical Mouse.
pub const USB_PRODUCT_MICROSOFT_PIXARTMOUSE: u16 = 0x00cb;
/// `USB_PRODUCT_MICROSOFT_WLNOTEBOOK2`: Wireless Optical Mouse 3000 (Model 1056).
pub const USB_PRODUCT_MICROSOFT_WLNOTEBOOK2: u16 = 0x00e1;
/// `USB_PRODUCT_MICROSOFT_TYPECOVER`: Surface Go Type Cover.
pub const USB_PRODUCT_MICROSOFT_TYPECOVER: u16 = 0x096f;
/// `USB_PRODUCT_MICROSOFT_TYPECOVER2`: Surface Go Type Cover.
pub const USB_PRODUCT_MICROSOFT_TYPECOVER2: u16 = 0x09b5;
/// `USB_PRODUCT_MOTOROLA2_T720C`: T720c.
pub const USB_PRODUCT_MOTOROLA2_T720C: u16 = 0x2822;
/// `USB_PRODUCT_MUSTEK2_PM800`: PowerMust 800.
pub const USB_PRODUCT_MUSTEK2_PM800: u16 = 0x5161;
/// `USB_PRODUCT_NEC_PICTY760`: Picty760.
pub const USB_PRODUCT_NEC_PICTY760: u16 = 0xbef4;
/// `USB_PRODUCT_NEC_PICTY900`: Picty900.
pub const USB_PRODUCT_NEC_PICTY900: u16 = 0xefbe;
/// `USB_PRODUCT_NEC_PICTY920`: Picty920.
pub const USB_PRODUCT_NEC_PICTY920: u16 = 0xf0be;
/// `USB_PRODUCT_NEC_PICTY800`: Picty800.
pub const USB_PRODUCT_NEC_PICTY800: u16 = 0xf1be;
/// `USB_PRODUCT_OMRON_BX50F`: BX50F UPS.
pub const USB_PRODUCT_OMRON_BX50F: u16 = 0x0057;
/// `USB_PRODUCT_OMRON_BX35F`: BX35F UPS.
pub const USB_PRODUCT_OMRON_BX35F: u16 = 0x0058;
/// `USB_PRODUCT_OMRON_BY35S`: BY35S UPS.
pub const USB_PRODUCT_OMRON_BY35S: u16 = 0x0080;
/// `USB_PRODUCT_PIXART_RPIMOUSE`: Raspberry Pi Mouse.
pub const USB_PRODUCT_PIXART_RPIMOUSE: u16 = 0x2510;
/// `USB_PRODUCT_QTRONIX_980N`: Scorpion-980N.
pub const USB_PRODUCT_QTRONIX_980N: u16 = 0x2011;
/// `USB_PRODUCT_QUALCOMM_MSM_MODEM`: CDMA MSM modem.
pub const USB_PRODUCT_QUALCOMM_MSM_MODEM: u16 = 0x3196;
/// `USB_PRODUCT_QUALCOMM2_MSM_PHONE`: CDMA MSM phone.
pub const USB_PRODUCT_QUALCOMM2_MSM_PHONE: u16 = 0x6000;
/// `USB_PRODUCT_RALINK_RT2573`: RT2573.
pub const USB_PRODUCT_RALINK_RT2573: u16 = 0x2573;
/// `USB_PRODUCT_SANYO_SCP4900`: Sanyo SCP-4900 Phone.
pub const USB_PRODUCT_SANYO_SCP4900: u16 = 0x0701;
/// `USB_PRODUCT_SHANTOU_DM9601`: DM9601.
pub const USB_PRODUCT_SHANTOU_DM9601: u16 = 0x9601;
/// `USB_PRODUCT_SIEMENS2_ES75`: GSM module MC35.
pub const USB_PRODUCT_SIEMENS2_ES75: u16 = 0x0034;
/// `USB_PRODUCT_SUNTAC_AS64LX`: U-Cable type A3.
pub const USB_PRODUCT_SUNTAC_AS64LX: u16 = 0x000b;
/// `USB_PRODUCT_TENX_MISSILE`: Missile Launcher.
pub const USB_PRODUCT_TENX_MISSILE: u16 = 0x0202;
/// `USB_PRODUCT_TERRATEC_AUREON`: Aureon Dual USB.
pub const USB_PRODUCT_TERRATEC_AUREON: u16 = 0x0077;
/// `USB_PRODUCT_TI_UTUSB41`: UT-USB41 hub.
pub const USB_PRODUCT_TI_UTUSB41: u16 = 0x1446;
/// `USB_PRODUCT_TI_MSP430`: MSP-FET430UIF.
pub const USB_PRODUCT_TI_MSP430: u16 = 0xf432;
/// `USB_PRODUCT_VELLEMAN_K8055`: K8055 USB Experiment interface board.
pub const USB_PRODUCT_VELLEMAN_K8055: u16 = 0x5500;
/// `USB_PRODUCT_YAMAHA_RTA54I`: NetVolante RTA54i.
pub const USB_PRODUCT_YAMAHA_RTA54I: u16 = 0x4000;
/// `USB_PRODUCT_YAMAHA_RTW65B`: NetVolante RTW65b.
pub const USB_PRODUCT_YAMAHA_RTW65B: u16 = 0x4001;
/// `USB_PRODUCT_YAMAHA_RTW65I`: NetVolante RTW65i.
pub const USB_PRODUCT_YAMAHA_RTW65I: u16 = 0x4002;
/// `USB_PRODUCT_YAMAHA_RTA55I`: NetVolante RTA55i.
pub const USB_PRODUCT_YAMAHA_RTA55I: u16 = 0x4004;

#[cfg(test)]
mod tests;
