use super::*;

#[test]
#[ignore = "needs OPENBSD_SRC (just test-ref)"]
fn values_match_the_c_header() {
    let defs = crate::reftest::defines("sys/net/if_types.h");
    let ours = crate::reftest::assert_defines!(defs;
        IFT_OTHER, IFT_1822, IFT_HDH1822, IFT_X25DDN, IFT_X25, IFT_ETHER, IFT_ISO88023,
        IFT_ISO88024, IFT_ISO88025, IFT_ISO88026, IFT_STARLAN, IFT_P10, IFT_P80, IFT_HY,
        IFT_FDDI, IFT_LAPB, IFT_SDLC, IFT_T1, IFT_CEPT, IFT_ISDNBASIC, IFT_ISDNPRIMARY,
        IFT_PTPSERIAL, IFT_PPP, IFT_LOOP, IFT_EON, IFT_XETHER, IFT_NSIP, IFT_SLIP, IFT_ULTRA,
        IFT_DS3, IFT_SIP, IFT_FRELAY, IFT_RS232, IFT_PARA, IFT_ARCNET, IFT_ARCNETPLUS,
        IFT_ATM, IFT_MIOX25, IFT_SONET, IFT_X25PLE, IFT_ISO88022LLC, IFT_LOCALTALK,
        IFT_SMDSDXI, IFT_FRELAYDCE, IFT_V35, IFT_HSSI, IFT_HIPPI, IFT_MODEM, IFT_AAL5,
        IFT_SONETPATH, IFT_SONETVT, IFT_SMDSICIP, IFT_PROPVIRTUAL, IFT_PROPMUX, IFT_IEEE80212,
        IFT_FIBRECHANNEL, IFT_HIPPIINTERFACE, IFT_FRAMERELAYINTERCONNECT, IFT_AFLANE8023,
        IFT_AFLANE8025, IFT_CCTEMUL, IFT_FASTETHER, IFT_ISDN, IFT_V11, IFT_V36, IFT_G703AT64K,
        IFT_G703AT2MB, IFT_QLLC, IFT_FASTETHERFX, IFT_CHANNEL, IFT_IEEE80211,
        IFT_IBM370PARCHAN, IFT_ESCON, IFT_DLSW, IFT_ISDNS, IFT_ISDNU, IFT_LAPD, IFT_IPSWITCH,
        IFT_RSRB, IFT_ATMLOGICAL, IFT_DS0, IFT_DS0BUNDLE, IFT_BSC, IFT_ASYNC, IFT_CNR,
        IFT_ISO88025DTR, IFT_EPLRS, IFT_ARAP, IFT_PROPCNLS, IFT_HOSTPAD, IFT_TERMPAD,
        IFT_FRAMERELAYMPI, IFT_X213, IFT_ADSL, IFT_RADSL, IFT_SDSL, IFT_VDSL,
        IFT_ISO88025CRFPINT, IFT_MYRINET, IFT_VOICEEM, IFT_VOICEFXO, IFT_VOICEFXS,
        IFT_VOICEENCAP, IFT_VOICEOVERIP, IFT_ATMDXI, IFT_ATMFUNI, IFT_ATMIMA,
        IFT_PPPMULTILINKBUNDLE, IFT_IPOVERCDLC, IFT_IPOVERCLAW, IFT_STACKTOSTACK,
        IFT_VIRTUALIPADDRESS, IFT_MPC, IFT_IPOVERATM, IFT_ISO88025FIBER, IFT_TDLC,
        IFT_GIGABITETHERNET, IFT_HDLC, IFT_LAPF, IFT_V37, IFT_X25MLP, IFT_X25HUNTGROUP,
        IFT_TRANSPHDLC, IFT_INTERLEAVE, IFT_FAST, IFT_IP, IFT_DOCSCABLEMACLAYER,
        IFT_DOCSCABLEDOWNSTREAM, IFT_DOCSCABLEUPSTREAM, IFT_A12MPPSWITCH, IFT_TUNNEL,
        IFT_COFFEE, IFT_CES, IFT_ATMSUBINTERFACE, IFT_L2VLAN, IFT_L3IPVLAN, IFT_L3IPXVLAN,
        IFT_DIGITALPOWERLINE, IFT_MEDIAMAILOVERIP, IFT_DTM, IFT_DCN, IFT_IPFORWARD, IFT_MSDSL,
        IFT_IEEE1394, IFT_IFGSN, IFT_DVBRCCMACLAYER, IFT_DVBRCCDOWNSTREAM, IFT_DVBRCCUPSTREAM,
        IFT_ATMVIRTUAL, IFT_MPLSTUNNEL, IFT_SRP, IFT_VOICEOVERATM, IFT_VOICEOVERFRAMERELAY,
        IFT_IDSL, IFT_COMPOSITELINK, IFT_SS7SIGLINK, IFT_PROPWIRELESSP2P, IFT_FRFORWARD,
        IFT_RFC1483, IFT_USB, IFT_IEEE8023ADLAG, IFT_BGPPOLICYACCOUNTING, IFT_FRF16MFRBUNDLE,
        IFT_H323GATEKEEPER, IFT_H323PROXY, IFT_MPLS, IFT_MFSIGLINK, IFT_HDSL2, IFT_SHDSL,
        IFT_DS1FDL, IFT_POS, IFT_DVBASILN, IFT_DVBASIOUT, IFT_PLC, IFT_NFAS, IFT_TR008,
        IFT_GR303RDT, IFT_GR303IDT, IFT_ISUP, IFT_PROPDOCSWIRELESSMACLAYER,
        IFT_PROPDOCSWIRELESSDOWNSTREAM, IFT_PROPDOCSWIRELESSUPSTREAM, IFT_HIPERLAN2,
        IFT_PROPBWAP2MP, IFT_SONETOVERHEADCHANNEL, IFT_DIGITALWRAPPEROVERHEADCHANNEL,
        IFT_AAL2, IFT_RADIOMAC, IFT_ATMRADIO, IFT_IMT, IFT_MVL, IFT_REACHDSL, IFT_FRDLCIENDPT,
        IFT_ATMVCIENDPT, IFT_OPTICALCHANNEL, IFT_OPTICALTRANSPORT, IFT_PROPATM,
        IFT_VOICEOVERCABLE, IFT_INFINIBAND, IFT_TELINK, IFT_Q2931, IFT_VIRTUALTG, IFT_SIPTG,
        IFT_SIPSIG, IFT_DOCSCABLEUPSTREAMCHANNEL, IFT_ECONET, IFT_PON155, IFT_PON622,
        IFT_BRIDGE, IFT_LINEGROUP, IFT_VOICEEMFGD, IFT_VOICEFGDEANA, IFT_VOICEDID, IFT_GIF,
        IFT_DUMMY, IFT_PVC, IFT_FAITH, IFT_ENC, IFT_PFLOG, IFT_PFSYNC, IFT_CARP,
        IFT_BLUETOOTH, IFT_PFLOW, IFT_MBIM, IFT_WIREGUARD,
    );
    crate::reftest::assert_complete(&defs, "IFT_", &ours);
}
