# EmiBSD's own test program (see sr6create.c): an OpenBSD-style Makefile that
# tools/xtask/src/userland.rs evaluates like those of the reference tree.

PROG=	sr6create
BINDIR=	/usr/sbin
LDSTATIC=	-static
NOMAN=	yes

.include <bsd.prog.mk>
