use super::*;

#[test]
#[ignore = "needs OPENBSD_SRC (just test-ref)"]
fn values_match_the_c_header() {
    let defs = crate::reftest::defines("sys/dev/pci/if_vmxreg.h");
    let ours = crate::reftest::assert_defines!(defs; UPT1_IMOD_NONE, UPT1_IMOD_HIGHEST,
        UPT1_IMOD_ADAPTIVE, UPT1_F_CSUM, UPT1_F_RSS, UPT1_F_VLAN, UPT1_F_LRO, VMXNET3_BAR1_VRRS,
        VMXNET3_BAR1_UVRS, VMXNET3_BAR1_DSL, VMXNET3_BAR1_DSH, VMXNET3_BAR1_CMD,
        VMXNET3_BAR1_MACL, VMXNET3_BAR1_MACH, VMXNET3_BAR1_INTR, VMXNET3_BAR1_EVENT,
        VMXNET3_CMD_ENABLE, VMXNET3_CMD_DISABLE, VMXNET3_CMD_RESET, VMXNET3_CMD_SET_RXMODE,
        VMXNET3_CMD_SET_FILTER, VMXNET3_CMD_SET_FEATURE, VMXNET3_CMD_GET_STATUS,
        VMXNET3_CMD_GET_STATS, VMXNET3_CMD_GET_LINK, VMXNET3_CMD_GET_MACL, VMXNET3_CMD_GET_MACH,
        VMXNET3_CMD_GET_INTRCFG, VMXNET3_INTRCFG_TYPE_SHIFT, VMXNET3_INTRCFG_TYPE_MASK,
        VMXNET3_INTRCFG_TYPE_AUTO, VMXNET3_INTRCFG_TYPE_INTX, VMXNET3_INTRCFG_TYPE_MSI,
        VMXNET3_INTRCFG_TYPE_MSIX, VMXNET3_INTRCFG_MODE_SHIFT, VMXNET3_INTRCFG_MODE_MASK,
        VMXNET3_INTRCFG_MODE_AUTO, VMXNET3_INTRCFG_MODE_ACTIVE, VMXNET3_INTRCFG_MODE_LAZY,
        VMXNET3_DMADESC_ALIGN, VMXNET3_TX_LEN_M, VMXNET3_TX_LEN_S, VMXNET3_TX_GEN_M,
        VMXNET3_TX_GEN_S, VMXNET3_TX_RES0, VMXNET3_TX_DTYPE_M, VMXNET3_TX_DTYPE_S,
        VMXNET3_TX_RES1, VMXNET3_TX_OP_M, VMXNET3_TX_OP_S, VMXNET3_TX_HLEN_M, VMXNET3_TX_HLEN_S,
        VMXNET3_TX_OM_M, VMXNET3_TX_OM_S, VMXNET3_TX_EOP, VMXNET3_TX_COMPREQ, VMXNET3_TX_RES2,
        VMXNET3_TX_VTAG_MODE, VMXNET3_TX_VLANTAG_M, VMXNET3_TX_VLANTAG_S, VMXNET3_OM_NONE,
        VMXNET3_OM_CSUM, VMXNET3_OM_TSO, VMXNET3_TXC_EOPIDX_M, VMXNET3_TXC_EOPIDX_S,
        VMXNET3_TXC_RES0_M, VMXNET3_TXC_RES0_S, VMXNET3_TXC_RES2_M, VMXNET3_TXC_TYPE_M,
        VMXNET3_TXC_TYPE_S, VMXNET3_TXC_GEN_M, VMXNET3_TXC_GEN_S, VMXNET3_RX_LEN_M,
        VMXNET3_RX_LEN_S, VMXNET3_RX_BTYPE_M, VMXNET3_RX_BTYPE_S, VMXNET3_RX_DTYPE_M,
        VMXNET3_RX_DTYPE_S, VMXNET3_RX_RES0_M, VMXNET3_RX_RES0_S, VMXNET3_RX_GEN_M,
        VMXNET3_RX_GEN_S, VMXNET3_BTYPE_HEAD, VMXNET3_BTYPE_BODY, VMXNET3_RXC_IDX_M,
        VMXNET3_RXC_IDX_S, VMXNET3_RXC_RES0_M, VMXNET3_RXC_RES0_S, VMXNET3_RXC_EOP,
        VMXNET3_RXC_SOP, VMXNET3_RXC_QID_M, VMXNET3_RXC_QID_S, VMXNET3_RXC_RSSTYPE_M,
        VMXNET3_RXC_RSSTYPE_S, VMXNET3_RXC_RSSTYPE_NONE, VMXNET3_RXC_NOCSUM, VMXNET3_RXC_RES1,
        VMXNET3_RXC_RSSHASH_M, VMXNET3_RXC_RSSHASH_S, VMXNET3_RXC_SEG_CNT_M, VMXNET3_RXC_LEN_M,
        VMXNET3_RXC_LEN_S, VMXNET3_RXC_ERROR, VMXNET3_RXC_VLAN, VMXNET3_RXC_VLANTAG_M,
        VMXNET3_RXC_VLANTAG_S, VMXNET3_RXC_CSUM_M, VMXNET3_RXC_CSUM_S, VMXNET3_RXC_CSUM_OK,
        VMXNET3_RXC_UDP, VMXNET3_RXC_TCP, VMXNET3_RXC_IPSUM_OK, VMXNET3_RXC_IPV6,
        VMXNET3_RXC_IPV4, VMXNET3_RXC_FRAGMENT, VMXNET3_RXC_FCS, VMXNET3_RXC_TYPE_M,
        VMXNET3_RXC_TYPE_S, VMXNET3_RXC_GEN_M, VMXNET3_RXC_GEN_S, VMXNET3_REV1_MAGIC,
        VMXNET3_GOS_UNKNOWN, VMXNET3_GOS_LINUX, VMXNET3_GOS_WINDOWS, VMXNET3_GOS_SOLARIS,
        VMXNET3_GOS_FREEBSD, VMXNET3_GOS_PXE, VMXNET3_GOS_32BIT, VMXNET3_GOS_64BIT,
        VMXNET3_MAX_TX_QUEUES, VMXNET3_MAX_RX_QUEUES, VMXNET3_MAX_INTRS, VMXNET3_NINTR,
        VMXNET3_ICTRL_DISABLE_ALL, VMXNET3_RXMODE_UCAST, VMXNET3_RXMODE_MCAST,
        VMXNET3_RXMODE_BCAST, VMXNET3_RXMODE_ALLMULTI, VMXNET3_RXMODE_PROMISC,
        VMXNET3_EVENT_RQERROR, VMXNET3_EVENT_TQERROR, VMXNET3_EVENT_LINK, VMXNET3_EVENT_DIC,
        VMXNET3_EVENT_DEBUG, VMXNET3_MAX_MTU, VMXNET3_MIN_MTU, UPT1_RSS_MAX_KEY_SIZE,
        UPT1_RSS_MAX_IND_TABLE_SIZE, UPT1_RSS_HASH_TYPE_NONE, UPT1_RSS_HASH_TYPE_IPV4,
        UPT1_RSS_HASH_TYPE_TCP_IPV4, UPT1_RSS_HASH_TYPE_IPV6, UPT1_RSS_HASH_TYPE_TCP_IPV6,
        UPT1_RSS_HASH_FUNC_TOEPLITZ);
    crate::reftest::assert_complete(&defs, "VMXNET3_", &ours);
    crate::reftest::assert_complete(&defs, "UPT1_", &ours);
}

#[test]
fn queue_registers_are_eight_bytes_apart() {
    assert_eq!(vmxnet3_bar0_imask(0), 0x000);
    assert_eq!(vmxnet3_bar0_imask(3), 0x018);
    assert_eq!(vmxnet3_bar0_txh(1), 0x608);
    assert_eq!(vmxnet3_bar0_rxh1(2), 0x810);
    assert_eq!(vmxnet3_bar0_rxh2(7), 0xa38);
}

#[test]
fn counters_follow_the_c_enums() {
    assert_eq!(UPT1_TxStat_discard as u8, 9);
    assert_eq!(UPT1_TxStats_count as u8, 10);
    assert_eq!(UPT1_RXStat_error as u8, 9);
    assert_eq!(UPT1_RxStats_count as u8, 10);
}
